// apps/shop-bcd/src/app/upgrade-preview/example-props.ts
// Map of example props for all UI components so upgrade previews can render reliably

const names = [
  // primitive components
  "Button",
  "Card",
  "CardContent",
  "Checkbox",
  "Dialog",
  "DialogContent",
  "DialogDescription",
  "DialogFooter",
  "DialogHeader",
  "DialogOverlay",
  "DialogPortal",
  "DialogTitle",
  "DialogTrigger",
  "Input",
  "Select",
  "SelectContent",
  "SelectGroup",
  "SelectItem",
  "SelectLabel",
  "SelectSeparator",
  "SelectTrigger",
  "SelectValue",
  "Table",
  "TableBody",
  "TableCell",
  "TableHead",
  "TableHeader",
  "TableRow",
  "Textarea",
  "ARViewer",
  "Avatar",
  "Chip",
  "ColorSwatch",
  "Icon",
  "LineChart",
  "Loader",
  "Spinner",
  "Logo",
  "PaginationDot",
  "Popover",
  "PopoverAnchor",
  "PopoverContent",
  "PopoverTrigger",
  "Price",
  "ProductBadge",
  "Progress",
  "Radio",
  "RatingStars",
  "Skeleton",
  "StatCard",
  "StockStatus",
  "Switch",
  "Tag",
  "Toast",
  "Tooltip",
  "VideoPlayer",
  "ZoomImage",
  // generated components
  "ProfileForm",
  "MfaSetup",
  "MfaChallenge",
  "ProductFilters",
  "ProductRowActions",
  "ComponentEditor",
  "ImagePicker",
  "ContactFormEditor",
  "GalleryEditor",
  "ImageBlockEditor",
  "TestimonialsEditor",
  "HeroBannerEditor",
  "ValuePropsEditor",
  "ReviewsCarouselEditor",
  "AnnouncementBarEditor",
  "MapBlockEditor",
  "StoreLocatorBlockEditor",
  "VideoBlockEditor",
  "FAQBlockEditor",
  "PricingTableEditor",
  "NewsletterSignupEditor",
  "ImageSliderEditor",
  "SocialFeedEditor",
  "SocialProofEditor",
  "SearchBarEditor",
  "RecommendationCarouselEditor",
  "ProductComparisonEditor",
  "FeaturedProductEditor",
  "ProductBundleEditor",
  "GiftCardEditor",
  "FormBuilderEditor",
  "ProductFilterEditor",
  "CountdownTimerEditor",
  "SocialLinksEditor",
  "ButtonEditor",
  "TabsEditor",
  "ProductGridEditor",
  "CustomHtmlEditor",
  "CanvasItem",
  "Palette",
  "PageBuilder",
  "PageToolbar",
  "PageCanvas",
  "PageSidebar",
  "FontSelect",
  "NavigationEditor",
  "PagesTable",
  "ProductPageBuilder",
  "RangeInput",
  "StyleEditor",
  "Breadcrumbs",
  "CurrencySwitcher",
  "FormField",
  "Image360Viewer",
  "LanguageSwitcher",
  "MediaSelector",
  "PaginationControl",
  "PaymentMethodSelector",
  "PriceCluster",
  "PromoCodeInput",
  "QuantityInput",
  "RatingSummary",
  "SearchBar",
  "SustainabilityBadgeCluster",
  "Accordion",
  "AccountPanel",
  "CategoryCard",
  "CheckoutStepper",
  "Content",
  "DataTable",
  "DeliveryScheduler",
  "FilterSidebar",
  "Footer",
  "Header",
  "LiveChatWidget",
  "MiniCart",
  "OrderSummary",
  "OrderTrackingTimeline",
  "ProductCard",
  "ProductCarousel",
  "ProductFeatures",
  "ProductGallery",
  "ProductGrid",
  "ProductVariantSelector",
  "QAModule",
  "RecommendationCarousel",
  "ReviewsList",
  "SideNav",
  "StatsGrid",
  "StickyAddToCartBar",
  "StoreLocatorMap",
  "WishlistDrawer",
  "AnnouncementBar",
  "AccountDashboardTemplate",
  "AnalyticsDashboardTemplate",
  "AppShell",
  "CartTemplate",
  "CategoryCollectionTemplate",
  "CheckoutTemplate",
  "DashboardTemplate",
  "Error404Template",
  "Error500Template",
  "FeaturedProductTemplate",
  "HomepageTemplate",
  "LiveShoppingEventTemplate",
  "LoyaltyHubTemplate",
  "MarketingEmailTemplate",
  "OrderConfirmationTemplate",
  "OrderTrackingTemplate",
  "ProductComparisonTemplate",
  "ProductDetailTemplate",
  "ProductGalleryTemplate",
  "ProductMediaGalleryTemplate",
  "SearchResultsTemplate",
  "StoreLocatorTemplate",
  "WishlistTemplate",
  "DynamicRenderer",
  "ThemeToggle",
];

export const exampleProps: Record<string, any> = Object.fromEntries(
  Array.from(new Set(names)).map((n) => [n, {}]),
);

exampleProps.Breadcrumbs = {
  items: [
    { label: "Home", href: "/" },
    { label: "Shop", href: "/shop" },
  ],
};

exampleProps.Button = { children: "Button" };
exampleProps.Tag = { children: "Tag" };
exampleProps.Tooltip = { children: "Info", content: "Tooltip" };
exampleProps.Accordion = {
  items: [{ title: "Item 1", content: "Content" }],
};

export default exampleProps;
