declare module "three-stdlib" {
  export const OrbitControls: any;
  export type OrbitControls = any;
  export const GroundProjectedEnv: any;
  export type GroundProjectedEnv = any;
  export const LineSegmentsGeometry: any;
  export type LineSegmentsGeometry = any;
  export const LineMaterial: any;
  export type LineMaterial = any;
  export type LineMaterialParameters = Record<string, unknown>;
  export const Line2: any;
  export type Line2 = any;
  export const LineSegments2: any;
  export type LineSegments2 = any;
  export const EffectComposer: any;
  export type EffectComposer = any;
  export const RenderPass: any;
  export type RenderPass = any;
  export const ShaderPass: any;
  export type ShaderPass = any;
  export const MarchingCubes: any;
  export type MarchingCubes = any;
  export const Font: any;
  export type Font = any;
  export const TextGeometry: any;
  export type TextGeometry = any;
  export type TextGeometryParameters = Record<string, unknown>;
  export const DeviceOrientationControls: any;
  export type DeviceOrientationControls = any;
  export const PointerLockControls: any;
  export type PointerLockControls = any;
  export const ArcballControls: any;
  export type ArcballControls = any;
  export const FlyControls: any;
  export type FlyControls = any;
  export const GLTFLoader: any;
  export type GLTFLoader = any;
  export type GLTF = Record<string, unknown>;
  export const MapControls: any;
  export type MapControls = any;
  export const Flow: any;
  export type Flow = any;
  export const Sky: any;
  export type Sky = any;
  export const TransformControls: any;
  export type TransformControls = any;
  export const FirstPersonControls: any;
  export type FirstPersonControls = any;
  export const TrackballControls: any;
  export type TrackballControls = any;
}
