import { lazy } from "react";
import type { LazyExoticComponent, ComponentType } from "react";

// eslint-disable-next-line @typescript-eslint/no-explicit-any
const editorRegistry: Record<string, LazyExoticComponent<ComponentType<any>>> = {
  ContactForm: lazy(() => import("./ContactFormEditor")),
  Gallery: lazy(() => import("./GalleryEditor")),
  Image: lazy(() => import("./ImageBlockEditor")),
  Lookbook: lazy(() => import("./LookbookEditor")),
  Testimonials: lazy(() => import("./TestimonialsEditor")),
  PricingTable: lazy(() => import("./PricingTableEditor")),
  HeroBanner: lazy(() => import("./HeroBannerEditor")),
  AnnouncementBar: lazy(() => import("./AnnouncementBarEditor")),
  NewsletterSignup: lazy(() => import("./NewsletterSignupEditor")),
  SearchBar: lazy(() => import("./SearchBarEditor")),
  ImageSlider: lazy(() => import("./ImageSliderEditor")),
  CollectionList: lazy(() => import("./CollectionListEditor")),
  RecommendationCarousel: lazy(() => import("./RecommendationCarouselEditor")),
  ProductComparison: lazy(() => import("./ProductComparisonEditor")),
  ProductBundle: lazy(() => import("./ProductBundleEditor")),
  GiftCardBlock: lazy(() => import("./GiftCardEditor")),
  FormBuilderBlock: lazy(() => import("./FormBuilderEditor")),
  PopupModal: lazy(() => import("./PopupModalEditor")),
  ValueProps: lazy(() => import("./ValuePropsEditor")),
  ReviewsCarousel: lazy(() => import("./ReviewsCarouselEditor")),
  SocialFeed: lazy(() => import("./SocialFeedEditor")),
  SocialProof: lazy(() => import("./SocialProofEditor")),
  MapBlock: lazy(() => import("./MapBlockEditor")),
  StoreLocatorBlock: lazy(() => import("./StoreLocatorBlockEditor")),
  VideoBlock: lazy(() => import("./VideoBlockEditor")),
  FAQBlock: lazy(() => import("./FAQBlockEditor")),
  Header: lazy(() => import("./HeaderEditor")),
  Footer: lazy(() => import("./FooterEditor")),
  ProductFilter: lazy(() => import("./ProductFilterEditor")),
  CountdownTimer: lazy(() => import("./CountdownTimerEditor")),
  SocialLinks: lazy(() => import("./SocialLinksEditor")),
  Button: lazy(() => import("./ButtonEditor")),
  Tabs: lazy(() => import("./TabsEditor")),
  Dataset: lazy(() => import("./DatasetEditor")),
  Repeater: lazy(() => import("./RepeaterEditor")),
  Bind: lazy(() => import("./BindEditor")),
  ProductGrid: lazy(() => import("./ProductGridEditor")),
  ProductCarousel: lazy(() => import("./ProductGridEditor")),
  CustomHtml: lazy(() => import("./CustomHtmlEditor")),
  Section: lazy(() => import("./SectionEditor")),
  StackFlex: lazy(() => import("./StackFlexEditor")),
  Grid: lazy(() => import("./GridContainerEditor")),
  CarouselContainer: lazy(() => import("./CarouselContainerEditor")),
  TabsAccordionContainer: lazy(() => import("./TabsAccordionContainerEditor")),
};

export default editorRegistry;
