// apps/cover-me-pretty/src/app/upgrade-preview/example-props.ts
// Map of example props for all UI components so upgrade previews can render reliably

export const exampleProps: Record<string, unknown> = {
  ProfileForm: {},
  MfaSetup: {},
  MfaChallenge: {},
  ProductFilters: {},
  ProductRowActions: {},
  ComponentEditor: {},
  ImagePicker: {},
  ContactFormEditor: {},
  GalleryEditor: {},
  ImageBlockEditor: {},
  TestimonialsEditor: {},
  HeroBannerEditor: {},
  ValuePropsEditor: {},
  ReviewsCarouselEditor: {},
  AnnouncementBarEditor: {},
  MapBlockEditor: {},
  StoreLocatorBlockEditor: {},
  VideoBlockEditor: {},
  FAQBlockEditor: {},
  PricingTableEditor: {},
  NewsletterSignupEditor: {},
  ImageSliderEditor: {},
  SocialFeedEditor: {},
  SocialProofEditor: {},
  SearchBarEditor: {},
  RecommendationCarouselEditor: {},
  ProductComparisonEditor: {},
  FeaturedProductEditor: {},
  ProductBundleEditor: {},
  GiftCardEditor: {},
  FormBuilderEditor: {},
  ProductFilterEditor: {},
  CountdownTimerEditor: {},
  SocialLinksEditor: {},
  ButtonEditor: {},
  TabsEditor: {},
  ProductGridEditor: {},
  CustomHtmlEditor: {},
  CanvasItem: {},
  Palette: {},
  PageBuilder: {},
  PageToolbar: {},
  PageCanvas: {},
  PageSidebar: {},
  FontSelect: {},
  NavigationEditor: {},
  NavigationPreview: {},
  PagesTable: {},
  ProductPageBuilder: {},
  RangeInput: {},
  StyleEditor: {},
  CardContent: {},
  DialogTrigger: {},
  SelectValue: {},
  TableRow: {},
  ARViewer: {},
  Avatar: {},
  Chip: {},
  ColorSwatch: {},
  Icon: {
    name: "star",
  },
  LineChart: {},
  Spinner: {},
  Logo: {},
  PaginationDot: {},
  PopoverTrigger: {},
  Price: {
    amount: 19.99,
    currency: "USD",
  },
  ProductBadge: {},
  Progress: {},
  Radio: {},
  RatingStars: {
    rating: 4,
  },
  Skeleton: {},
  StatCard: {},
  StockStatus: {
    inStock: true,
  },
  Switch: {},
  Tag: {
    children: "Tag",
  },
  Toast: {},
  Tooltip: {
    children: "Info",
    content: "Tooltip",
  },
  VideoPlayer: {},
  ZoomImage: {},
  Breadcrumbs: {
    items: [
      {
        label: "Home",
        href: "/",
      },
      {
        label: "Shop",
        href: "/shop",
      },
    ],
  },
  CurrencySwitcher: {},
  FormField: {},
  Image360Viewer: {},
  LanguageSwitcher: {},
  MediaSelector: {},
  PaginationControl: {},
  PaymentMethodSelector: {},
  PriceCluster: {},
  PromoCodeInput: {},
  QuantityInput: {},
  RatingSummary: {},
  SearchBar: {
    label: "Search",
    suggestions: ["Apple", "Banana", "Cherry"],
  },
  SustainabilityBadgeCluster: {},
  Accordion: {
    items: [
      {
        title: "Item 1",
        content: "Content",
      },
    ],
  },
  AccountPanel: {},
  CategoryCard: {},
  CheckoutStepper: {},
  Content: {},
  DataTable: {},
  DeliveryScheduler: {},
  FilterSidebar: {},
  Footer: {},
  Header: {},
  LiveChatWidget: {},
  MiniCart: {},
  OrderSummary: {},
  OrderTrackingTimeline: {},
  ProductCard: {},
  ProductCarousel: {},
  ProductFeatures: {},
  ProductGallery: {},
  ProductGrid: {},
  ProductVariantSelector: {},
  QAModule: {},
  RecommendationCarousel: {},
  ReviewsList: {},
  SideNav: {},
  StatsGrid: {},
  StickyAddToCartBar: {},
  StoreLocatorMap: {},
  WishlistDrawer: {},
  AnnouncementBar: {},
  AccountDashboardTemplate: {},
  AnalyticsDashboardTemplate: {},
  AppShell: {},
  CartTemplate: {},
  CategoryCollectionTemplate: {},
  CheckoutTemplate: {},
  DashboardTemplate: {},
  Error404Template: {},
  Error500Template: {},
  FeaturedProductTemplate: {},
  HomepageTemplate: {},
  LiveShoppingEventTemplate: {},
  LoyaltyHubTemplate: {},
  MarketingEmailTemplate: {},
  OrderConfirmationTemplate: {},
  OrderTrackingTemplate: {},
  ProductComparisonTemplate: {},
  ProductDetailTemplate: {},
  ProductGalleryTemplate: {},
  ProductMediaGalleryTemplate: {},
  SearchResultsTemplate: {},
  StoreLocatorTemplate: {},
  WishlistTemplate: {},
  DynamicRenderer: {},
  ThemeToggle: {},
};

export default exampleProps;
