# /pnpm-workspace.yaml

packages:
  # Each top-level app or package
  - "apps/**"
  - "!**/.open-next/**"
  - "!**/.next/**"
  - "packages/platform-machine"
  - "packages/*"
  - "packages/plugins/*"
  - "packages/themes/*" # Include theme packages so @themes/base, etc. resolve
  - "functions"
  - "scripts"
  - "__tests__"
  - "tools/vscode-mcp-server"

onlyBuiltDependencies:
  - "@tailwindcss/oxide"
  - esbuild
  - sharp
  - unrs-resolver
  - workerd
