# /pnpm-workspace.yaml

packages:
  # Each top-level app or package
  - "apps-script"
  - "apps/**"
  - "packages/platform-machine"
  - "packages/*/"
  - "packages/plugins/*"
  - "packages/themes/*" # Include theme packages so @themes/base, etc. resolve

onlyBuiltDependencies:
  - "@tailwindcss/oxide"
  - esbuild
  - sharp
  - unrs-resolver
  - workerd
  - better-sqlite3
