# /pnpm-workspace.yaml   ← full file, copy-paste

packages:
  # Every package or app — one pattern is enough
  - "apps-script"
  - "apps/**"
  - "packages/**"
  - "packages/plugins/sanity"

onlyBuiltDependencies:
  - "@tailwindcss/oxide"
  - esbuild
  - sharp
  - unrs-resolver
  - workerd
