# /pnpm-workspace.yaml   ← full file

packages:
  # Each top-level app or package
  - "apps-script"
  - "apps/**"
  - "packages/platform-machine"
  - "packages/*/"
  # Include every plugin under packages/plugins (paypal, premier-shipping, sanity, etc.)
  - "packages/plugins/*"

onlyBuiltDependencies:
  - "@tailwindcss/oxide"
  - esbuild
  - sharp
  - unrs-resolver
  - workerd
  - better-sqlite3
