/*
 * AUTO-GENERATED by apps/business-os/scripts/generate-contract-migration.mjs
 * Source: docs/business-os/startup-loop/contract-migration.yaml
 *
 * Do not edit this file directly. Edit the YAML source and re-run the generator.
 */

export const CONTRACT_MIGRATION_CONFIG = {
  "version": "1",
  "timebox": {
    "alias_accept_until_utc": "2026-02-14",
    "dual_read_until_utc": "2026-02-14",
    "lint_warn_until_utc": "2026-02-14"
  },
  "stage_aliases": {
    "lp-do-fact-find": "fact-find"
  },
  "filename_aliases": {
    "fact-finding.user.md": "fact-find.user.md"
  },
  "allowlists": {
    "legacy_filename_refs": [],
    "legacy_stage_key_emitters": []
  },
  "stage_addressing": {
    "resolver_module": "scripts/src/startup-loop/stage-addressing.ts",
    "canonical_alias_source": "docs/business-os/startup-loop/_generated/stage-operator-map.json",
    "modes": [
      {
        "id": "id",
        "flag": "--stage",
        "behavior": "canonical-always",
        "fallback": "suggest_alias"
      },
      {
        "id": "alias",
        "flag": "--stage-alias",
        "behavior": "fail-closed",
        "fallback": "deterministic_suggestions"
      },
      {
        "id": "label",
        "flag": "--stage-label",
        "behavior": "exact-match-only",
        "fallback": "canonical_label_list"
      }
    ]
  }
} as const;
