/*
 * AUTO-GENERATED by apps/business-os/scripts/generate-contract-migration.mjs
 * Source: docs/business-os/startup-loop/contract-migration.yaml
 *
 * Do not edit this file directly. Edit the YAML source and re-run the generator.
 */

export const CONTRACT_MIGRATION_CONFIG = {
  "version": "1",
  "timebox": {
    "alias_accept_until_utc": "2026-02-14",
    "dual_read_until_utc": "2026-02-14",
    "lint_warn_until_utc": "2026-02-14"
  },
  "stage_aliases": {
    "lp-fact-find": "fact-find"
  },
  "filename_aliases": {
    "fact-finding.user.md": "fact-find.user.md"
  },
  "allowlists": {
    "legacy_filename_refs": [],
    "legacy_stage_key_emitters": []
  }
} as const;
