/**
 * Recipe CSS Generator
 *
 * Generates optional utility classes from ThemeRecipes definitions.
 * Each recipe produces:
 * - `.recipe-{kebab-name}` base class with CSS properties
 * - `.recipe-{kebab-name}--{variant}` for each variant
 * - `@media` blocks for responsive overrides
 * - Comment with description and usage guidance
 *
 * This is optional — agents can read recipes.ts directly and apply
 * classes/css inline. Generated utility classes make recipes usable
 * without TypeScript imports.
 *
 * Pure function: takes recipe data, returns a CSS string.
 */

import type { RecipeBase, ThemeRecipes } from "./theme-expression";

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/** Convert camelCase to kebab-case */
function toKebab(str: string): string {
  return str.replace(/([a-z0-9])([A-Z])/g, "$1-$2").toLowerCase();
}

/** Standard Tailwind breakpoint values */
const BREAKPOINTS: Record<string, string> = {
  sm: "640px",
  md: "768px",
  lg: "1024px",
  xl: "1280px",
  "2xl": "1536px",
};

/**
 * Emit CSS property declarations from a RecipeBase.
 * Tailwind classes in `classes` are emitted as a comment (they cannot be
 * reliably converted to raw CSS without a Tailwind compiler). The `css`
 * map is emitted as actual property declarations.
 */
function emitRecipeProperties(base: Partial<RecipeBase>, indent: string): string[] {
  const lines: string[] = [];

  if (base.classes) {
    lines.push(`${indent}/* tailwind: ${base.classes} */`);
  }
  if (base.hover) {
    lines.push(`${indent}/* hover: ${base.hover} */`);
  }
  if (base.css) {
    for (const [prop, val] of Object.entries(base.css)) {
      lines.push(`${indent}${toKebab(prop)}: ${val};`);
    }
  }

  return lines;
}

// ---------------------------------------------------------------------------
// Main generator
// ---------------------------------------------------------------------------

/**
 * Generate CSS utility classes from a ThemeRecipes definition.
 *
 * @param recipes - The theme's recipe definitions
 * @returns Complete CSS string with `.recipe-*` utility classes
 */
export function generateRecipeCSS(recipes: ThemeRecipes): string {
  const entries = Object.entries(recipes);

  if (entries.length === 0) {
    return "/* Generated by build-recipes.ts — no recipes defined */\n";
  }

  const sections: string[] = ["/* Generated by build-recipes.ts */\n"];

  for (const [name, recipe] of entries) {
    const kebabName = toKebab(name);
    const className = `recipe-${kebabName}`;

    // Comment block with description and usage
    const commentLines = [
      `/**`,
      ` * .${className}`,
      ` * ${recipe.description}`,
      ` * Modes: ${recipe.applicableModes.join(", ")}`,
      ` * Usage: ${recipe.usage}`,
    ];
    if (recipe.doNotUseWhen) {
      commentLines.push(` * Do not use when: ${recipe.doNotUseWhen}`);
    }
    commentLines.push(` */`);
    sections.push(commentLines.join("\n"));

    // Base class
    const baseProps = emitRecipeProperties(recipe.base, "  ");
    if (baseProps.length > 0) {
      sections.push(`.${className} {\n${baseProps.join("\n")}\n}\n`);
    }

    // Variants
    if (recipe.variants) {
      for (const [variantName, variantBase] of Object.entries(recipe.variants)) {
        const variantProps = emitRecipeProperties(variantBase, "  ");
        if (variantProps.length > 0) {
          sections.push(`.${className}--${toKebab(variantName)} {\n${variantProps.join("\n")}\n}\n`);
        }
      }
    }

    // Responsive overrides
    if (recipe.responsive) {
      for (const [breakpoint, responsiveBase] of Object.entries(recipe.responsive)) {
        const minWidth = BREAKPOINTS[breakpoint] ?? breakpoint;
        const responsiveProps = emitRecipeProperties(responsiveBase, "    ");
        if (responsiveProps.length > 0) {
          sections.push(
            `@media (min-width: ${minWidth}) {\n  .${className} {\n${responsiveProps.join("\n")}\n  }\n}\n`
          );
        }
      }
    }
  }

  return sections.join("\n");
}
