import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import * as React from "react";
import { cn } from "../../utils/style";
import { Price } from "../atoms/Price";
export function OrderConfirmationTemplate({ orderId, cart, className, ...props }) {
    const lines = Object.entries(cart).map(([id, line]) => ({ id, ...line }));
    const subtotal = lines.reduce((s, l) => s + l.sku.price * l.qty, 0);
    const deposit = lines.reduce((s, l) => s + (l.sku.deposit ?? 0) * l.qty, 0);
    return (_jsxs("div", { className: cn("space-y-6", className), ...props, children: [_jsx("h2", { className: "text-xl font-semibold", children: "Order Confirmation" }), _jsxs("p", { children: ["Thank you for your order. Your reference is", _jsxs("span", { className: "font-mono", children: [" ", orderId] }), "."] }), _jsxs("table", { className: "w-full text-sm", children: [_jsx("thead", { children: _jsxs("tr", { className: "border-b text-left", children: [_jsx("th", { className: "py-2", children: "Item" }), _jsx("th", { children: "Qty" }), _jsx("th", { className: "text-right", children: "Price" })] }) }), _jsx("tbody", { children: lines.map((l) => (_jsxs("tr", { className: "border-b last:border-0", children: [_jsxs("td", { className: "py-2", children: [l.sku.title, l.size && (_jsxs("span", { className: "ml-1 text-xs text-muted", "data-token": "--color-muted", children: ["(", l.size, ")"] }))] }), _jsx("td", { children: l.qty }), _jsx("td", { className: "text-right", children: _jsx(Price, { amount: l.sku.price * l.qty }) })] }, l.id))) }), _jsxs("tfoot", { children: [_jsxs("tr", { children: [_jsx("td", {}), _jsx("td", { className: "py-2", children: "Deposit" }), _jsx("td", { className: "text-right", children: _jsx(Price, { amount: deposit }) })] }), _jsxs("tr", { children: [_jsx("td", {}), _jsx("td", { className: "py-2 font-semibold", children: "Total" }), _jsx("td", { className: "text-right font-semibold", children: _jsx(Price, { amount: subtotal + deposit }) })] })] })] })] }));
}
