import { existsSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { createRequire } from "node:module";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { runInNewContext } from "node:vm";
import ts from "typescript";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const require = createRequire(import.meta.url);
const tokensPath = path.resolve(
  __dirname,
  "..",
  "..",
  "packages",
  "themes",
  "base",
  "tokens.js"
);
const { tokens } = require(tokensPath);

function generateStaticCss(map) {
  let css = "/* Generated by build-tokens.ts */\n\n:root {\n";
  const darkEntries = [];
  for (const [name, defs] of Object.entries(map)) {
    css += `  ${name}: ${defs.light};\n`;
    if (defs.dark !== undefined) {
      css += `  ${name}-dark: ${defs.dark};\n`;
      darkEntries.push([name, defs]);
    }
  }
  css += "}\n";

  if (darkEntries.length) {
    css += "\n@media (prefers-color-scheme: dark) {\n  :root {\n";
    for (const [name] of darkEntries) {
      css += `    ${name}: var(${name}-dark);\n`;
    }
    css += "  }\n}\n";

    css += "\nhtml.theme-dark {\n";
    for (const [name] of darkEntries) {
      css += `  ${name}: var(${name}-dark);\n`;
    }
    css += "}\n";
  }
  return css;
}

function generateDynamicCss(map) {
  let css = "/* Generated by build-tokens.ts */\n\n:root {\n";
  const darkEntries = [];
  for (const [name, defs] of Object.entries(map)) {
    const varName = `--token-${name.slice(2)}`;
    css += `  ${name}: var(${varName}, ${defs.light});\n`;
    if (defs.dark !== undefined) {
      const darkVar = `--token-${name.slice(2)}-dark`;
      css += `  ${name}-dark: var(${darkVar}, ${defs.dark});\n`;
      darkEntries.push([name, defs]);
    }
  }
  css += "}\n";

  if (darkEntries.length) {
    css += "\n@media (prefers-color-scheme: dark) {\n  :root {\n";
    for (const [name] of darkEntries) {
      css += `    ${name}: var(${name}-dark);\n`;
    }
    css += "  }\n}\n";

    css += "\nhtml.theme-dark {\n";
    for (const [name] of darkEntries) {
      css += `  ${name}: var(${name}-dark);\n`;
    }
    css += "}\n";
  }
  return css;
}

function writeBaseTokens() {
  const baseDir = path.resolve(
    __dirname,
    "..",
    "..",
    "packages",
    "themes",
    "base"
  );
  writeFileSync(path.join(baseDir, "tokens.static.css"), generateStaticCss(tokens));
  writeFileSync(path.join(baseDir, "tokens.dynamic.css"), generateDynamicCss(tokens));
  console.log("→ tokens.static.css and tokens.dynamic.css generated");
}

function generateThemeCss(map) {
  let css = "/* Generated by build-tokens.ts */\n\n:root {\n";
  const darkEntries = [];
  for (const [name, val] of Object.entries(map)) {
    css += `  ${name}: ${val};\n`;
    if (name.endsWith("-dark")) {
      const base = name.replace(/-dark$/, "");
      if (map[base] !== undefined) {
        darkEntries.push([base, name]);
      }
    }
  }
  css += "}\n";

  if (darkEntries.length) {
    css += "\n@media (prefers-color-scheme: dark) {\n  :root {\n";
    for (const [base, dark] of darkEntries) {
      css += `    ${base}: var(${dark});\n`;
    }
    css += "  }\n}\n";

    css += "\nhtml.theme-dark {\n";
    for (const [base, dark] of darkEntries) {
      css += `  ${base}: var(${dark});\n`;
    }
    css += "}\n";
  }

  return css;
}

async function buildThemeCss() {
  const themesDir = path.resolve(__dirname, "..", "..", "packages", "themes");
  const themes = readdirSync(themesDir, { withFileTypes: true })
    .filter((d) => d.isDirectory() && d.name !== "base")
    .map((d) => d.name);

  for (const theme of themes) {
    const modPath = path.join(themesDir, theme, "src", "tailwind-tokens.ts");
    if (!existsSync(modPath)) continue;
    const source = readFileSync(modPath, "utf8");
    const transpiled = ts.transpileModule(source, {
      compilerOptions: { module: ts.ModuleKind.CommonJS },
    }).outputText;

    const sandbox = {
      module: { exports: {} },
      exports: {},
      require,
    };
    sandbox.exports = sandbox.module.exports;
    runInNewContext(transpiled, sandbox);

    const themeTokens = sandbox.module.exports.tokens;
    const css = generateThemeCss(themeTokens);
    writeFileSync(path.join(themesDir, theme, "src", "tokens.css"), css);
  }
}

writeBaseTokens();
buildThemeCss()
  .then(() => console.log("→ theme tokens generated"))
  .catch((err) => {
    console.error(err);
    process.exit(1);
  });
