// scripts/src/setup-ci.ts
/* i18n-exempt file -- ENG-2001 CLI-only workflow generation messages, not user-facing UI [ttl=2026-12-31] */
/**
 * Generate a GitHub Actions workflow wrapper for a shop. The script validates
 * the shop's `.env` file against `@config` but does not inline env values into
 * the workflow YAML.
 */
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { envSchema } from "@config/src/env";
import {
  getShopAppPackage,
  getShopAppSlug,
  getShopWorkflowName,
} from "@acme/platform-core/shops";

const shopId = process.argv[2];
if (!shopId) {
  console.error(
    "Usage: pnpm ts-node scripts/src/setup-ci.ts <shopId>"
  ); // i18n-exempt -- ENG-2001 developer-facing usage hint for CLI script [ttl=2026-12-31]
  process.exit(1);
}

const appSlug = getShopAppSlug(shopId);
const appPackage = getShopAppPackage(shopId);

const envPath = join("apps", appSlug, ".env");
// eslint-disable-next-line security/detect-non-literal-fs-filename -- SEC-2001: envPath is workspace-relative and derived from a trusted app slug, not HTTP input
if (!existsSync(envPath)) {
  console.error(`Missing ${envPath}`); // i18n-exempt -- ENG-2001 developer-facing missing env file message [ttl=2026-12-31]
  process.exit(1);
}

// eslint-disable-next-line security/detect-non-literal-fs-filename -- SEC-2001: envPath is workspace-relative and derived from a trusted app slug, not HTTP input
const envRaw = readFileSync(envPath, "utf8");
const env: Record<string, string> = {};
for (const line of envRaw.split(/\n+/)) {
  const trimmed = line.trim();
  if (!trimmed || trimmed.startsWith("#")) continue;
  const [key, ...rest] = trimmed.split("=");
  env[key] = rest.join("=");
}

try {
  // Remove empty string values before validation.
  Object.keys(env).forEach((k) => {
    if (env[k] === "") delete env[k];
  });
  envSchema.parse(env);
} catch (err) {
  console.error("Invalid environment variables:\n", err); // i18n-exempt -- ENG-2001 developer-facing env validation error label [ttl=2026-12-31]
  process.exit(1);
}

const wfPath = join(".github", "workflows", getShopWorkflowName(shopId));
const branchRef = "${{ github.ref_name }}";
const workflow = `# AUTO-GENERATED by scripts/src/setup-ci.ts. Manual edits will be overwritten.
name: Deploy ${appSlug}

on:
  push:
    paths:
      - 'apps/${appSlug}/**'
      - 'packages/**'
      - '.github/workflows/${getShopWorkflowName(shopId)}'
  workflow_dispatch:

jobs:
  deploy:
    uses: ./.github/workflows/reusable-app.yml
    with:
      app-filter: "${appPackage}"
      build-cmd: "pnpm --filter ${appPackage}... build"
      deploy-cmd: "pnpm exec next-on-pages deploy --project-name ${appSlug} --branch ${branchRef}"
      project-name: "${appSlug}"
    secrets: inherit
`;

// eslint-disable-next-line security/detect-non-literal-fs-filename -- SEC-2001: wfPath is workspace-relative under .github/workflows; script is CLI-only
writeFileSync(wfPath, workflow);
console.log(`Created workflow ${wfPath}`);
