// scripts/src/setup-ci.ts
/* i18n-exempt file -- ENG-2001 CLI-only workflow generation messages, not user-facing UI [ttl=2026-12-31] */
/**
 * Generate a GitHub Actions workflow wrapper for a shop. The script validates
 * the shop's `.env` file against `@config` but does not inline env values into
 * the workflow YAML.
 */
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

import { envSchema } from "@config/src/env";

import {
  getShopAppPackage,
  getShopAppSlug,
  getShopWorkflowName,
} from "@acme/platform-core/shops";

const shopId = process.argv[2];
if (!shopId) {
  console.error(
    "Usage: pnpm ts-node scripts/src/setup-ci.ts <shopId>"
  ); // i18n-exempt -- ENG-2001 developer-facing usage hint for CLI script [ttl=2026-12-31]
  process.exit(1);
}

const appSlug = getShopAppSlug(shopId);
const appPackage = getShopAppPackage(shopId);

const envPath = join("apps", appSlug, ".env");
 
if (!existsSync(envPath)) {
  console.error(`Missing ${envPath}`); // i18n-exempt -- ENG-2001 developer-facing missing env file message [ttl=2026-12-31]
  process.exit(1);
}

 
const envRaw = readFileSync(envPath, "utf8");
const env: Record<string, string> = {};
for (const line of envRaw.split(/\n+/)) {
  const trimmed = line.trim();
  if (!trimmed || trimmed.startsWith("#")) continue;
  const [key, ...rest] = trimmed.split("=");
  env[key] = rest.join("=");
}

try {
  // Remove empty string values before validation.
  Object.keys(env).forEach((k) => {
    if (env[k] === "") delete env[k];
  });
  envSchema.parse(env);
} catch (err) {
  console.error("Invalid environment variables:\n", err); // i18n-exempt -- ENG-2001 developer-facing env validation error label [ttl=2026-12-31]
  process.exit(1);
}

const wfPath = join(".github", "workflows", getShopWorkflowName(shopId));
const branchRef = "${{ github.ref_name }}";
const gitSha = "${{ github.sha }}";
const workflow = `# AUTO-GENERATED by launch-shop / setup-ci.ts. Manual edits will be overwritten.
name: Deploy ${appSlug}

on:
  push:
    branches:
      - main
      - 'work/**'
    paths:
      - 'apps/${appSlug}/**'
      - 'packages/**'
      - '.github/workflows/${getShopWorkflowName(shopId)}'
  pull_request:
    paths:
      - 'apps/${appSlug}/**'
      - 'packages/**'
  workflow_dispatch:

concurrency:
  group: ${appSlug}-deploy-\${{ github.ref }}
  cancel-in-progress: true

jobs:
  validate-and-build:
    name: Validate & Build
    uses: ./.github/workflows/reusable-app.yml
    with:
      app-filter: "${appPackage}"
      build-cmd: "pnpm --filter ${appPackage}... build"
      project-name: "${appSlug}"
    secrets: inherit

  deploy-preview:
    name: Deploy Preview
    if: github.ref != 'refs/heads/main' && github.event_name == 'push'
    needs: validate-and-build
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: ./.github/actions/setup-repo
        with:
          turbo-token: \${{ secrets.TURBO_TOKEN }}
          turbo-team: \${{ vars.TURBO_TEAM }}

      - name: Deploy to Preview
        id: deploy
        env:
          CLOUDFLARE_API_TOKEN: \${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: \${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        run: |
          cd apps/${appSlug}
          OUTPUT=$(pnpm exec next-on-pages deploy --project-name ${appSlug} --branch ${branchRef} 2>&1) || true
          echo "$OUTPUT"
          # Extract deploy URL from output
          DEPLOY_URL=$(echo "$OUTPUT" | grep -oE 'https://[a-z0-9-]+\\.${appSlug}\\.pages\\.dev' | head -1 || echo "")
          if [ -z "$DEPLOY_URL" ]; then
            DEPLOY_URL="https://${branchRef}.${appSlug}.pages.dev"
          fi
          echo "deploy_url=$DEPLOY_URL" >> $GITHUB_OUTPUT

      - name: Write deploy metadata
        run: |
          mkdir -p .deploy-metadata
          cat > .deploy-metadata/deploy-metadata.json << 'EOF'
          {
            "deployUrl": "\${{ steps.deploy.outputs.deploy_url }}",
            "productionUrl": "https://${appSlug}.pages.dev",
            "gitSha": "${gitSha}",
            "environment": "preview",
            "timestamp": "$(date -u +%Y-%m-%dT%H:%M:%SZ)",
            "shopId": "${shopId}",
            "appSlug": "${appSlug}"
          }
          EOF

      - name: Upload deploy metadata
        uses: actions/upload-artifact@v4
        with:
          name: deploy-metadata
          path: .deploy-metadata/deploy-metadata.json
          retention-days: 7

      - name: Post-Deploy Health Check
        run: |
          chmod +x scripts/post-deploy-health-check.sh
          BASE_URL="\${{ steps.deploy.outputs.deploy_url }}" ./scripts/post-deploy-health-check.sh ${appSlug}
        env:
          EXTRA_ROUTES: "/api/health"
          MAX_RETRIES: "10"
          RETRY_DELAY: "6"

  deploy-production:
    name: Deploy Production
    if: github.ref == 'refs/heads/main'
    needs: validate-and-build
    runs-on: ubuntu-latest
    timeout-minutes: 15
    environment:
      name: production
      url: https://${appSlug}.pages.dev
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: ./.github/actions/setup-repo
        with:
          turbo-token: \${{ secrets.TURBO_TOKEN }}
          turbo-team: \${{ vars.TURBO_TEAM }}

      - name: Deploy to Production
        id: deploy
        env:
          CLOUDFLARE_API_TOKEN: \${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: \${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        run: |
          cd apps/${appSlug}
          pnpm exec next-on-pages deploy --project-name ${appSlug} --branch main

      - name: Write deploy metadata
        run: |
          mkdir -p .deploy-metadata
          cat > .deploy-metadata/deploy-metadata.json << 'EOF'
          {
            "deployUrl": "https://${appSlug}.pages.dev",
            "productionUrl": "https://${appSlug}.pages.dev",
            "gitSha": "${gitSha}",
            "environment": "production",
            "timestamp": "$(date -u +%Y-%m-%dT%H:%M:%SZ)",
            "shopId": "${shopId}",
            "appSlug": "${appSlug}"
          }
          EOF

      - name: Upload deploy metadata
        uses: actions/upload-artifact@v4
        with:
          name: deploy-metadata
          path: .deploy-metadata/deploy-metadata.json
          retention-days: 7

      - name: Post-Deploy Health Check
        run: |
          chmod +x scripts/post-deploy-health-check.sh
          ./scripts/post-deploy-health-check.sh ${appSlug}
        env:
          EXTRA_ROUTES: "/api/health"
          MAX_RETRIES: "10"
          RETRY_DELAY: "6"
`;

 
writeFileSync(wfPath, workflow);
console.log(`Created workflow ${wfPath}`);
