import { z } from "zod";
export declare const baseEnvSchema: z.ZodObject<{
    NODE_ENV: z.ZodOptional<z.ZodEnum<["development", "test", "production"]>>;
    OUTPUT_EXPORT: z.ZodOptional<z.ZodBoolean>;
    NEXT_PUBLIC_PHASE: z.ZodOptional<z.ZodString>;
    NEXT_PUBLIC_DEFAULT_SHOP: z.ZodOptional<z.ZodString>;
    NEXT_PUBLIC_SHOP_ID: z.ZodOptional<z.ZodString>;
    SHOP_CODE: z.ZodOptional<z.ZodString>;
    CART_COOKIE_SECRET: z.ZodString | z.ZodDefault<z.ZodString>;
    CART_TTL: z.ZodOptional<z.ZodNumber>;
    CHROMATIC_PROJECT_TOKEN: z.ZodOptional<z.ZodString>;
    GA_API_SECRET: z.ZodOptional<z.ZodString>;
    DATABASE_URL: z.ZodOptional<z.ZodString>;
    CLOUDFLARE_ACCOUNT_ID: z.ZodOptional<z.ZodString>;
    CLOUDFLARE_API_TOKEN: z.ZodOptional<z.ZodString>;
    LUXURY_FEATURES_RA_TICKETING: z.ZodOptional<z.ZodBoolean>;
    LUXURY_FEATURES_FRAUD_REVIEW_THRESHOLD: z.ZodOptional<z.ZodNumber>;
    LUXURY_FEATURES_REQUIRE_STRONG_CUSTOMER_AUTH: z.ZodOptional<z.ZodBoolean>;
    LUXURY_FEATURES_TRACKING_DASHBOARD: z.ZodOptional<z.ZodBoolean>;
    LUXURY_FEATURES_RETURNS: z.ZodOptional<z.ZodBoolean>;
    DEPOSIT_RELEASE_ENABLED: z.ZodOptional<z.ZodEffects<z.ZodEffects<z.ZodString, "true" | "false", string>, boolean, string>>;
    DEPOSIT_RELEASE_INTERVAL_MS: z.ZodOptional<z.ZodEffects<z.ZodEffects<z.ZodString, string, string>, number, string>>;
    REVERSE_LOGISTICS_ENABLED: z.ZodOptional<z.ZodEffects<z.ZodEffects<z.ZodString, "true" | "false", string>, boolean, string>>;
    REVERSE_LOGISTICS_INTERVAL_MS: z.ZodOptional<z.ZodEffects<z.ZodEffects<z.ZodString, string, string>, number, string>>;
    LATE_FEE_ENABLED: z.ZodOptional<z.ZodEffects<z.ZodEffects<z.ZodString, "true" | "false", string>, boolean, string>>;
    LATE_FEE_INTERVAL_MS: z.ZodOptional<z.ZodEffects<z.ZodEffects<z.ZodString, string, string>, number, string>>;
    OPENAI_API_KEY: z.ZodOptional<z.ZodString>;
    NEXT_PUBLIC_BASE_URL: z.ZodOptional<z.ZodString>;
    STOCK_ALERT_RECIPIENTS: z.ZodOptional<z.ZodString>;
    STOCK_ALERT_WEBHOOK: z.ZodOptional<z.ZodString>;
    STOCK_ALERT_DEFAULT_THRESHOLD: z.ZodOptional<z.ZodNumber>;
    STOCK_ALERT_RECIPIENT: z.ZodOptional<z.ZodString>;
    TRYON_PROVIDER: z.ZodDefault<z.ZodEnum<["workers-ai", "external-api"]>>;
    TRYON_HEAVY_API_URL: z.ZodOptional<z.ZodString>;
    CLOUDFLARE_AI_GATEWAY_ID: z.ZodOptional<z.ZodString>;
    R2_BUCKET_TRYON: z.ZodOptional<z.ZodString>;
    R2_PUBLIC_BASE_URL: z.ZodOptional<z.ZodString>;
    R2_ACCESS_KEY_ID: z.ZodOptional<z.ZodString>;
    R2_SECRET_ACCESS_KEY: z.ZodOptional<z.ZodString>;
}, "passthrough", z.ZodTypeAny, z.objectOutputType<{
    NODE_ENV: z.ZodOptional<z.ZodEnum<["development", "test", "production"]>>;
    OUTPUT_EXPORT: z.ZodOptional<z.ZodBoolean>;
    NEXT_PUBLIC_PHASE: z.ZodOptional<z.ZodString>;
    NEXT_PUBLIC_DEFAULT_SHOP: z.ZodOptional<z.ZodString>;
    NEXT_PUBLIC_SHOP_ID: z.ZodOptional<z.ZodString>;
    SHOP_CODE: z.ZodOptional<z.ZodString>;
    CART_COOKIE_SECRET: z.ZodString | z.ZodDefault<z.ZodString>;
    CART_TTL: z.ZodOptional<z.ZodNumber>;
    CHROMATIC_PROJECT_TOKEN: z.ZodOptional<z.ZodString>;
    GA_API_SECRET: z.ZodOptional<z.ZodString>;
    DATABASE_URL: z.ZodOptional<z.ZodString>;
    CLOUDFLARE_ACCOUNT_ID: z.ZodOptional<z.ZodString>;
    CLOUDFLARE_API_TOKEN: z.ZodOptional<z.ZodString>;
    LUXURY_FEATURES_RA_TICKETING: z.ZodOptional<z.ZodBoolean>;
    LUXURY_FEATURES_FRAUD_REVIEW_THRESHOLD: z.ZodOptional<z.ZodNumber>;
    LUXURY_FEATURES_REQUIRE_STRONG_CUSTOMER_AUTH: z.ZodOptional<z.ZodBoolean>;
    LUXURY_FEATURES_TRACKING_DASHBOARD: z.ZodOptional<z.ZodBoolean>;
    LUXURY_FEATURES_RETURNS: z.ZodOptional<z.ZodBoolean>;
    DEPOSIT_RELEASE_ENABLED: z.ZodOptional<z.ZodEffects<z.ZodEffects<z.ZodString, "true" | "false", string>, boolean, string>>;
    DEPOSIT_RELEASE_INTERVAL_MS: z.ZodOptional<z.ZodEffects<z.ZodEffects<z.ZodString, string, string>, number, string>>;
    REVERSE_LOGISTICS_ENABLED: z.ZodOptional<z.ZodEffects<z.ZodEffects<z.ZodString, "true" | "false", string>, boolean, string>>;
    REVERSE_LOGISTICS_INTERVAL_MS: z.ZodOptional<z.ZodEffects<z.ZodEffects<z.ZodString, string, string>, number, string>>;
    LATE_FEE_ENABLED: z.ZodOptional<z.ZodEffects<z.ZodEffects<z.ZodString, "true" | "false", string>, boolean, string>>;
    LATE_FEE_INTERVAL_MS: z.ZodOptional<z.ZodEffects<z.ZodEffects<z.ZodString, string, string>, number, string>>;
    OPENAI_API_KEY: z.ZodOptional<z.ZodString>;
    NEXT_PUBLIC_BASE_URL: z.ZodOptional<z.ZodString>;
    STOCK_ALERT_RECIPIENTS: z.ZodOptional<z.ZodString>;
    STOCK_ALERT_WEBHOOK: z.ZodOptional<z.ZodString>;
    STOCK_ALERT_DEFAULT_THRESHOLD: z.ZodOptional<z.ZodNumber>;
    STOCK_ALERT_RECIPIENT: z.ZodOptional<z.ZodString>;
    TRYON_PROVIDER: z.ZodDefault<z.ZodEnum<["workers-ai", "external-api"]>>;
    TRYON_HEAVY_API_URL: z.ZodOptional<z.ZodString>;
    CLOUDFLARE_AI_GATEWAY_ID: z.ZodOptional<z.ZodString>;
    R2_BUCKET_TRYON: z.ZodOptional<z.ZodString>;
    R2_PUBLIC_BASE_URL: z.ZodOptional<z.ZodString>;
    R2_ACCESS_KEY_ID: z.ZodOptional<z.ZodString>;
    R2_SECRET_ACCESS_KEY: z.ZodOptional<z.ZodString>;
}, z.ZodTypeAny, "passthrough">, z.objectInputType<{
    NODE_ENV: z.ZodOptional<z.ZodEnum<["development", "test", "production"]>>;
    OUTPUT_EXPORT: z.ZodOptional<z.ZodBoolean>;
    NEXT_PUBLIC_PHASE: z.ZodOptional<z.ZodString>;
    NEXT_PUBLIC_DEFAULT_SHOP: z.ZodOptional<z.ZodString>;
    NEXT_PUBLIC_SHOP_ID: z.ZodOptional<z.ZodString>;
    SHOP_CODE: z.ZodOptional<z.ZodString>;
    CART_COOKIE_SECRET: z.ZodString | z.ZodDefault<z.ZodString>;
    CART_TTL: z.ZodOptional<z.ZodNumber>;
    CHROMATIC_PROJECT_TOKEN: z.ZodOptional<z.ZodString>;
    GA_API_SECRET: z.ZodOptional<z.ZodString>;
    DATABASE_URL: z.ZodOptional<z.ZodString>;
    CLOUDFLARE_ACCOUNT_ID: z.ZodOptional<z.ZodString>;
    CLOUDFLARE_API_TOKEN: z.ZodOptional<z.ZodString>;
    LUXURY_FEATURES_RA_TICKETING: z.ZodOptional<z.ZodBoolean>;
    LUXURY_FEATURES_FRAUD_REVIEW_THRESHOLD: z.ZodOptional<z.ZodNumber>;
    LUXURY_FEATURES_REQUIRE_STRONG_CUSTOMER_AUTH: z.ZodOptional<z.ZodBoolean>;
    LUXURY_FEATURES_TRACKING_DASHBOARD: z.ZodOptional<z.ZodBoolean>;
    LUXURY_FEATURES_RETURNS: z.ZodOptional<z.ZodBoolean>;
    DEPOSIT_RELEASE_ENABLED: z.ZodOptional<z.ZodEffects<z.ZodEffects<z.ZodString, "true" | "false", string>, boolean, string>>;
    DEPOSIT_RELEASE_INTERVAL_MS: z.ZodOptional<z.ZodEffects<z.ZodEffects<z.ZodString, string, string>, number, string>>;
    REVERSE_LOGISTICS_ENABLED: z.ZodOptional<z.ZodEffects<z.ZodEffects<z.ZodString, "true" | "false", string>, boolean, string>>;
    REVERSE_LOGISTICS_INTERVAL_MS: z.ZodOptional<z.ZodEffects<z.ZodEffects<z.ZodString, string, string>, number, string>>;
    LATE_FEE_ENABLED: z.ZodOptional<z.ZodEffects<z.ZodEffects<z.ZodString, "true" | "false", string>, boolean, string>>;
    LATE_FEE_INTERVAL_MS: z.ZodOptional<z.ZodEffects<z.ZodEffects<z.ZodString, string, string>, number, string>>;
    OPENAI_API_KEY: z.ZodOptional<z.ZodString>;
    NEXT_PUBLIC_BASE_URL: z.ZodOptional<z.ZodString>;
    STOCK_ALERT_RECIPIENTS: z.ZodOptional<z.ZodString>;
    STOCK_ALERT_WEBHOOK: z.ZodOptional<z.ZodString>;
    STOCK_ALERT_DEFAULT_THRESHOLD: z.ZodOptional<z.ZodNumber>;
    STOCK_ALERT_RECIPIENT: z.ZodOptional<z.ZodString>;
    TRYON_PROVIDER: z.ZodDefault<z.ZodEnum<["workers-ai", "external-api"]>>;
    TRYON_HEAVY_API_URL: z.ZodOptional<z.ZodString>;
    CLOUDFLARE_AI_GATEWAY_ID: z.ZodOptional<z.ZodString>;
    R2_BUCKET_TRYON: z.ZodOptional<z.ZodString>;
    R2_PUBLIC_BASE_URL: z.ZodOptional<z.ZodString>;
    R2_ACCESS_KEY_ID: z.ZodOptional<z.ZodString>;
    R2_SECRET_ACCESS_KEY: z.ZodOptional<z.ZodString>;
}, z.ZodTypeAny, "passthrough">>;
