import { z } from "zod";
export declare const coreEnvPreprocessedSchema: z.ZodEffects<z.ZodObject<Omit<{
    NEXTAUTH_SECRET: z.ZodEffects<z.ZodString, string, string> | z.ZodDefault<z.ZodEffects<z.ZodString, string, string>>;
    PREVIEW_TOKEN_SECRET: z.ZodOptional<z.ZodEffects<z.ZodString, string, string>>;
    UPGRADE_PREVIEW_TOKEN_SECRET: z.ZodOptional<z.ZodEffects<z.ZodString, string, string>>;
    SESSION_SECRET: z.ZodEffects<z.ZodString, string, string> | z.ZodDefault<z.ZodEffects<z.ZodString, string, string>>;
    COOKIE_DOMAIN: z.ZodOptional<z.ZodString>;
    LOGIN_RATE_LIMIT_REDIS_URL: z.ZodOptional<z.ZodString>;
    LOGIN_RATE_LIMIT_REDIS_TOKEN: z.ZodOptional<z.ZodEffects<z.ZodString, string, string>>;
    RATE_LIMIT_STORE_PROVIDER: z.ZodOptional<z.ZodEnum<["redis", "kv"]>>;
    CART_STORE_PROVIDER: z.ZodOptional<z.ZodEnum<["redis", "cloudflare", "memory"]>>;
    SESSION_STORE_PROVIDER: z.ZodOptional<z.ZodEnum<["redis", "cloudflare", "memory"]>>;
    SESSION_STORE: z.ZodOptional<z.ZodEnum<["memory", "redis"]>>;
    UPSTASH_REDIS_REST_URL: z.ZodOptional<z.ZodString>;
    UPSTASH_REDIS_REST_TOKEN: z.ZodOptional<z.ZodEffects<z.ZodString, string, string>>;
    AUTH_PROVIDER: z.ZodDefault<z.ZodEnum<["local", "jwt", "oauth"]>>;
    JWT_SECRET: z.ZodOptional<z.ZodEffects<z.ZodString, string, string>>;
    OAUTH_ISSUER: z.ZodOptional<z.ZodString>;
    OAUTH_CLIENT_ID: z.ZodOptional<z.ZodString>;
    OAUTH_CLIENT_SECRET: z.ZodOptional<z.ZodEffects<z.ZodString, string, string>>;
    OAUTH_REDIRECT_ORIGIN: z.ZodOptional<z.ZodString>;
    OAUTH_ENFORCE_PKCE: z.ZodOptional<z.ZodEffects<z.ZodBoolean, boolean, unknown>>;
    AUTH_TOKEN_TTL: z.ZodEffects<z.ZodEffects<z.ZodDefault<z.ZodEffects<z.ZodOptional<z.ZodString>, string | undefined, unknown>>, string, unknown>, number, unknown>;
    TOKEN_ALGORITHM: z.ZodDefault<z.ZodEnum<["HS256", "RS256"]>>;
    TOKEN_AUDIENCE: z.ZodDefault<z.ZodString>;
    TOKEN_ISSUER: z.ZodDefault<z.ZodString>;
    ALLOW_GUEST: z.ZodDefault<z.ZodEffects<z.ZodBoolean, boolean, unknown>>;
    ENFORCE_2FA: z.ZodDefault<z.ZodEffects<z.ZodBoolean, boolean, unknown>>;
}, "AUTH_TOKEN_TTL"> & {
    CMS_SPACE_URL: z.ZodString | z.ZodDefault<z.ZodString>;
    CMS_ACCESS_TOKEN: z.ZodString | z.ZodDefault<z.ZodString>;
    SANITY_API_VERSION: z.ZodEffects<z.ZodDefault<z.ZodEffects<z.ZodString, string, string>>, string, unknown>;
    SANITY_PROJECT_ID: z.ZodString | z.ZodDefault<z.ZodString>;
    SANITY_DATASET: z.ZodString | z.ZodDefault<z.ZodString>;
    SANITY_API_TOKEN: z.ZodString | z.ZodDefault<z.ZodString>;
    SANITY_PREVIEW_SECRET: z.ZodString | z.ZodDefault<z.ZodString>;
    SANITY_BASE_URL: z.ZodOptional<z.ZodEffects<z.ZodString, string, string>>;
    CMS_BASE_URL: z.ZodOptional<z.ZodEffects<z.ZodString, string, string>>;
    CMS_PAGINATION_LIMIT: z.ZodDefault<z.ZodNumber>;
    CMS_DRAFTS_ENABLED: z.ZodDefault<z.ZodEffects<z.ZodBoolean, boolean, unknown>>;
    CMS_DRAFTS_DISABLED_PATHS: z.ZodEffects<z.ZodDefault<z.ZodString>, string[], string | undefined>;
    CMS_SEARCH_ENABLED: z.ZodDefault<z.ZodEffects<z.ZodBoolean, boolean, unknown>>;
    CMS_SEARCH_DISABLED_PATHS: z.ZodEffects<z.ZodDefault<z.ZodString>, string[], string | undefined>;
} & {
    EMAIL_FROM: z.ZodOptional<z.ZodEffects<z.ZodString, string, string>>;
    EMAIL_SENDER_NAME: z.ZodOptional<z.ZodString>;
    GMAIL_USER: z.ZodOptional<z.ZodString>;
    GMAIL_PASS: z.ZodOptional<z.ZodString>;
    SMTP_URL: z.ZodOptional<z.ZodString>;
    SMTP_PORT: z.ZodOptional<z.ZodEffects<z.ZodEffects<z.ZodString, string, string>, number, string>>;
    SMTP_SECURE: z.ZodOptional<z.ZodEffects<z.ZodEffects<z.ZodEffects<z.ZodString, string, string>, string, string>, boolean, string>>;
    CAMPAIGN_FROM: z.ZodOptional<z.ZodEffects<z.ZodString, string, string>>;
    EMAIL_PROVIDER: z.ZodDefault<z.ZodEnum<["sendgrid", "resend", "smtp", "noop"]>>;
    SENDGRID_API_KEY: z.ZodOptional<z.ZodString>;
    SENDGRID_MARKETING_KEY: z.ZodOptional<z.ZodString>;
    RESEND_API_KEY: z.ZodOptional<z.ZodString>;
    EMAIL_BATCH_SIZE: z.ZodOptional<z.ZodNumber>;
    EMAIL_BATCH_DELAY_MS: z.ZodOptional<z.ZodNumber>;
} & {
    PAYMENTS_PROVIDER: z.ZodOptional<z.ZodEnum<["stripe"]>>;
    PAYMENTS_SANDBOX: z.ZodEffects<z.ZodEffects<z.ZodOptional<z.ZodString>, string | undefined, string | undefined>, boolean, string | undefined>;
    PAYMENTS_CURRENCY: z.ZodEffects<z.ZodDefault<z.ZodString>, string, string | undefined>;
    STRIPE_SECRET_KEY: z.ZodDefault<z.ZodString>;
    NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY: z.ZodDefault<z.ZodString>;
    STRIPE_WEBHOOK_SECRET: z.ZodDefault<z.ZodString>;
} & {
    TAXJAR_KEY: z.ZodOptional<z.ZodString>;
    UPS_KEY: z.ZodOptional<z.ZodString>;
    DHL_KEY: z.ZodOptional<z.ZodString>;
    SHIPPING_PROVIDER: z.ZodOptional<z.ZodEnum<["none", "external", "shippo", "ups", "dhl"]>>;
    ALLOWED_COUNTRIES: z.ZodEffects<z.ZodOptional<z.ZodArray<z.ZodString, "many">>, string[] | undefined, unknown>;
    LOCAL_PICKUP_ENABLED: z.ZodEffects<z.ZodEffects<z.ZodEffects<z.ZodOptional<z.ZodString>, string | undefined, unknown>, string | undefined, unknown>, boolean | undefined, unknown>;
    DEFAULT_COUNTRY: z.ZodEffects<z.ZodEffects<z.ZodOptional<z.ZodString>, string | undefined, unknown>, string | undefined, unknown>;
    DEFAULT_SHIPPING_ZONE: z.ZodOptional<z.ZodEnum<["domestic", "eu", "international"]>>;
    FREE_SHIPPING_THRESHOLD: z.ZodEffects<z.ZodOptional<z.ZodNumber>, number | undefined, unknown>;
} & {
    NODE_ENV: z.ZodOptional<z.ZodEnum<["development", "test", "production"]>>;
    OUTPUT_EXPORT: z.ZodOptional<z.ZodBoolean>;
    NEXT_PUBLIC_PHASE: z.ZodOptional<z.ZodString>;
    NEXT_PUBLIC_DEFAULT_SHOP: z.ZodOptional<z.ZodString>;
    NEXT_PUBLIC_SHOP_ID: z.ZodOptional<z.ZodString>;
    SHOP_CODE: z.ZodOptional<z.ZodString>;
    CART_COOKIE_SECRET: z.ZodString | z.ZodDefault<z.ZodString>;
    CART_TTL: z.ZodOptional<z.ZodNumber>;
    CHROMATIC_PROJECT_TOKEN: z.ZodOptional<z.ZodString>;
    GA_API_SECRET: z.ZodOptional<z.ZodString>;
    DATABASE_URL: z.ZodOptional<z.ZodString>;
    CLOUDFLARE_ACCOUNT_ID: z.ZodOptional<z.ZodString>;
    CLOUDFLARE_API_TOKEN: z.ZodOptional<z.ZodString>;
    LUXURY_FEATURES_RA_TICKETING: z.ZodOptional<z.ZodBoolean>;
    LUXURY_FEATURES_FRAUD_REVIEW_THRESHOLD: z.ZodOptional<z.ZodNumber>;
    LUXURY_FEATURES_REQUIRE_STRONG_CUSTOMER_AUTH: z.ZodOptional<z.ZodBoolean>;
    LUXURY_FEATURES_TRACKING_DASHBOARD: z.ZodOptional<z.ZodBoolean>;
    LUXURY_FEATURES_RETURNS: z.ZodOptional<z.ZodBoolean>;
    DEPOSIT_RELEASE_ENABLED: z.ZodOptional<z.ZodEffects<z.ZodEffects<z.ZodString, "true" | "false", string>, boolean, string>>;
    DEPOSIT_RELEASE_INTERVAL_MS: z.ZodOptional<z.ZodEffects<z.ZodEffects<z.ZodString, string, string>, number, string>>;
    REVERSE_LOGISTICS_ENABLED: z.ZodOptional<z.ZodEffects<z.ZodEffects<z.ZodString, "true" | "false", string>, boolean, string>>;
    REVERSE_LOGISTICS_INTERVAL_MS: z.ZodOptional<z.ZodEffects<z.ZodEffects<z.ZodString, string, string>, number, string>>;
    LATE_FEE_ENABLED: z.ZodOptional<z.ZodEffects<z.ZodEffects<z.ZodString, "true" | "false", string>, boolean, string>>;
    LATE_FEE_INTERVAL_MS: z.ZodOptional<z.ZodEffects<z.ZodEffects<z.ZodString, string, string>, number, string>>;
    OPENAI_API_KEY: z.ZodOptional<z.ZodString>;
    NEXT_PUBLIC_BASE_URL: z.ZodOptional<z.ZodString>;
    STOCK_ALERT_RECIPIENTS: z.ZodOptional<z.ZodString>;
    STOCK_ALERT_WEBHOOK: z.ZodOptional<z.ZodString>;
    STOCK_ALERT_DEFAULT_THRESHOLD: z.ZodOptional<z.ZodNumber>;
    STOCK_ALERT_RECIPIENT: z.ZodOptional<z.ZodString>;
    TRYON_PROVIDER: z.ZodDefault<z.ZodEnum<["workers-ai", "external-api"]>>;
    TRYON_HEAVY_API_URL: z.ZodOptional<z.ZodString>;
    CLOUDFLARE_AI_GATEWAY_ID: z.ZodOptional<z.ZodString>;
    R2_BUCKET_TRYON: z.ZodOptional<z.ZodString>;
    R2_PUBLIC_BASE_URL: z.ZodOptional<z.ZodString>;
    R2_ACCESS_KEY_ID: z.ZodOptional<z.ZodString>;
    R2_SECRET_ACCESS_KEY: z.ZodOptional<z.ZodString>;
} & {
    AUTH_TOKEN_TTL: z.ZodOptional<z.ZodUnion<[z.ZodString, z.ZodNumber]>>;
}, "passthrough", z.ZodTypeAny, z.objectOutputType<Omit<{
    NEXTAUTH_SECRET: z.ZodEffects<z.ZodString, string, string> | z.ZodDefault<z.ZodEffects<z.ZodString, string, string>>;
    PREVIEW_TOKEN_SECRET: z.ZodOptional<z.ZodEffects<z.ZodString, string, string>>;
    UPGRADE_PREVIEW_TOKEN_SECRET: z.ZodOptional<z.ZodEffects<z.ZodString, string, string>>;
    SESSION_SECRET: z.ZodEffects<z.ZodString, string, string> | z.ZodDefault<z.ZodEffects<z.ZodString, string, string>>;
    COOKIE_DOMAIN: z.ZodOptional<z.ZodString>;
    LOGIN_RATE_LIMIT_REDIS_URL: z.ZodOptional<z.ZodString>;
    LOGIN_RATE_LIMIT_REDIS_TOKEN: z.ZodOptional<z.ZodEffects<z.ZodString, string, string>>;
    RATE_LIMIT_STORE_PROVIDER: z.ZodOptional<z.ZodEnum<["redis", "kv"]>>;
    CART_STORE_PROVIDER: z.ZodOptional<z.ZodEnum<["redis", "cloudflare", "memory"]>>;
    SESSION_STORE_PROVIDER: z.ZodOptional<z.ZodEnum<["redis", "cloudflare", "memory"]>>;
    SESSION_STORE: z.ZodOptional<z.ZodEnum<["memory", "redis"]>>;
    UPSTASH_REDIS_REST_URL: z.ZodOptional<z.ZodString>;
    UPSTASH_REDIS_REST_TOKEN: z.ZodOptional<z.ZodEffects<z.ZodString, string, string>>;
    AUTH_PROVIDER: z.ZodDefault<z.ZodEnum<["local", "jwt", "oauth"]>>;
    JWT_SECRET: z.ZodOptional<z.ZodEffects<z.ZodString, string, string>>;
    OAUTH_ISSUER: z.ZodOptional<z.ZodString>;
    OAUTH_CLIENT_ID: z.ZodOptional<z.ZodString>;
    OAUTH_CLIENT_SECRET: z.ZodOptional<z.ZodEffects<z.ZodString, string, string>>;
    OAUTH_REDIRECT_ORIGIN: z.ZodOptional<z.ZodString>;
    OAUTH_ENFORCE_PKCE: z.ZodOptional<z.ZodEffects<z.ZodBoolean, boolean, unknown>>;
    AUTH_TOKEN_TTL: z.ZodEffects<z.ZodEffects<z.ZodDefault<z.ZodEffects<z.ZodOptional<z.ZodString>, string | undefined, unknown>>, string, unknown>, number, unknown>;
    TOKEN_ALGORITHM: z.ZodDefault<z.ZodEnum<["HS256", "RS256"]>>;
    TOKEN_AUDIENCE: z.ZodDefault<z.ZodString>;
    TOKEN_ISSUER: z.ZodDefault<z.ZodString>;
    ALLOW_GUEST: z.ZodDefault<z.ZodEffects<z.ZodBoolean, boolean, unknown>>;
    ENFORCE_2FA: z.ZodDefault<z.ZodEffects<z.ZodBoolean, boolean, unknown>>;
}, "AUTH_TOKEN_TTL"> & {
    CMS_SPACE_URL: z.ZodString | z.ZodDefault<z.ZodString>;
    CMS_ACCESS_TOKEN: z.ZodString | z.ZodDefault<z.ZodString>;
    SANITY_API_VERSION: z.ZodEffects<z.ZodDefault<z.ZodEffects<z.ZodString, string, string>>, string, unknown>;
    SANITY_PROJECT_ID: z.ZodString | z.ZodDefault<z.ZodString>;
    SANITY_DATASET: z.ZodString | z.ZodDefault<z.ZodString>;
    SANITY_API_TOKEN: z.ZodString | z.ZodDefault<z.ZodString>;
    SANITY_PREVIEW_SECRET: z.ZodString | z.ZodDefault<z.ZodString>;
    SANITY_BASE_URL: z.ZodOptional<z.ZodEffects<z.ZodString, string, string>>;
    CMS_BASE_URL: z.ZodOptional<z.ZodEffects<z.ZodString, string, string>>;
    CMS_PAGINATION_LIMIT: z.ZodDefault<z.ZodNumber>;
    CMS_DRAFTS_ENABLED: z.ZodDefault<z.ZodEffects<z.ZodBoolean, boolean, unknown>>;
    CMS_DRAFTS_DISABLED_PATHS: z.ZodEffects<z.ZodDefault<z.ZodString>, string[], string | undefined>;
    CMS_SEARCH_ENABLED: z.ZodDefault<z.ZodEffects<z.ZodBoolean, boolean, unknown>>;
    CMS_SEARCH_DISABLED_PATHS: z.ZodEffects<z.ZodDefault<z.ZodString>, string[], string | undefined>;
} & {
    EMAIL_FROM: z.ZodOptional<z.ZodEffects<z.ZodString, string, string>>;
    EMAIL_SENDER_NAME: z.ZodOptional<z.ZodString>;
    GMAIL_USER: z.ZodOptional<z.ZodString>;
    GMAIL_PASS: z.ZodOptional<z.ZodString>;
    SMTP_URL: z.ZodOptional<z.ZodString>;
    SMTP_PORT: z.ZodOptional<z.ZodEffects<z.ZodEffects<z.ZodString, string, string>, number, string>>;
    SMTP_SECURE: z.ZodOptional<z.ZodEffects<z.ZodEffects<z.ZodEffects<z.ZodString, string, string>, string, string>, boolean, string>>;
    CAMPAIGN_FROM: z.ZodOptional<z.ZodEffects<z.ZodString, string, string>>;
    EMAIL_PROVIDER: z.ZodDefault<z.ZodEnum<["sendgrid", "resend", "smtp", "noop"]>>;
    SENDGRID_API_KEY: z.ZodOptional<z.ZodString>;
    SENDGRID_MARKETING_KEY: z.ZodOptional<z.ZodString>;
    RESEND_API_KEY: z.ZodOptional<z.ZodString>;
    EMAIL_BATCH_SIZE: z.ZodOptional<z.ZodNumber>;
    EMAIL_BATCH_DELAY_MS: z.ZodOptional<z.ZodNumber>;
} & {
    PAYMENTS_PROVIDER: z.ZodOptional<z.ZodEnum<["stripe"]>>;
    PAYMENTS_SANDBOX: z.ZodEffects<z.ZodEffects<z.ZodOptional<z.ZodString>, string | undefined, string | undefined>, boolean, string | undefined>;
    PAYMENTS_CURRENCY: z.ZodEffects<z.ZodDefault<z.ZodString>, string, string | undefined>;
    STRIPE_SECRET_KEY: z.ZodDefault<z.ZodString>;
    NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY: z.ZodDefault<z.ZodString>;
    STRIPE_WEBHOOK_SECRET: z.ZodDefault<z.ZodString>;
} & {
    TAXJAR_KEY: z.ZodOptional<z.ZodString>;
    UPS_KEY: z.ZodOptional<z.ZodString>;
    DHL_KEY: z.ZodOptional<z.ZodString>;
    SHIPPING_PROVIDER: z.ZodOptional<z.ZodEnum<["none", "external", "shippo", "ups", "dhl"]>>;
    ALLOWED_COUNTRIES: z.ZodEffects<z.ZodOptional<z.ZodArray<z.ZodString, "many">>, string[] | undefined, unknown>;
    LOCAL_PICKUP_ENABLED: z.ZodEffects<z.ZodEffects<z.ZodEffects<z.ZodOptional<z.ZodString>, string | undefined, unknown>, string | undefined, unknown>, boolean | undefined, unknown>;
    DEFAULT_COUNTRY: z.ZodEffects<z.ZodEffects<z.ZodOptional<z.ZodString>, string | undefined, unknown>, string | undefined, unknown>;
    DEFAULT_SHIPPING_ZONE: z.ZodOptional<z.ZodEnum<["domestic", "eu", "international"]>>;
    FREE_SHIPPING_THRESHOLD: z.ZodEffects<z.ZodOptional<z.ZodNumber>, number | undefined, unknown>;
} & {
    NODE_ENV: z.ZodOptional<z.ZodEnum<["development", "test", "production"]>>;
    OUTPUT_EXPORT: z.ZodOptional<z.ZodBoolean>;
    NEXT_PUBLIC_PHASE: z.ZodOptional<z.ZodString>;
    NEXT_PUBLIC_DEFAULT_SHOP: z.ZodOptional<z.ZodString>;
    NEXT_PUBLIC_SHOP_ID: z.ZodOptional<z.ZodString>;
    SHOP_CODE: z.ZodOptional<z.ZodString>;
    CART_COOKIE_SECRET: z.ZodString | z.ZodDefault<z.ZodString>;
    CART_TTL: z.ZodOptional<z.ZodNumber>;
    CHROMATIC_PROJECT_TOKEN: z.ZodOptional<z.ZodString>;
    GA_API_SECRET: z.ZodOptional<z.ZodString>;
    DATABASE_URL: z.ZodOptional<z.ZodString>;
    CLOUDFLARE_ACCOUNT_ID: z.ZodOptional<z.ZodString>;
    CLOUDFLARE_API_TOKEN: z.ZodOptional<z.ZodString>;
    LUXURY_FEATURES_RA_TICKETING: z.ZodOptional<z.ZodBoolean>;
    LUXURY_FEATURES_FRAUD_REVIEW_THRESHOLD: z.ZodOptional<z.ZodNumber>;
    LUXURY_FEATURES_REQUIRE_STRONG_CUSTOMER_AUTH: z.ZodOptional<z.ZodBoolean>;
    LUXURY_FEATURES_TRACKING_DASHBOARD: z.ZodOptional<z.ZodBoolean>;
    LUXURY_FEATURES_RETURNS: z.ZodOptional<z.ZodBoolean>;
    DEPOSIT_RELEASE_ENABLED: z.ZodOptional<z.ZodEffects<z.ZodEffects<z.ZodString, "true" | "false", string>, boolean, string>>;
    DEPOSIT_RELEASE_INTERVAL_MS: z.ZodOptional<z.ZodEffects<z.ZodEffects<z.ZodString, string, string>, number, string>>;
    REVERSE_LOGISTICS_ENABLED: z.ZodOptional<z.ZodEffects<z.ZodEffects<z.ZodString, "true" | "false", string>, boolean, string>>;
    REVERSE_LOGISTICS_INTERVAL_MS: z.ZodOptional<z.ZodEffects<z.ZodEffects<z.ZodString, string, string>, number, string>>;
    LATE_FEE_ENABLED: z.ZodOptional<z.ZodEffects<z.ZodEffects<z.ZodString, "true" | "false", string>, boolean, string>>;
    LATE_FEE_INTERVAL_MS: z.ZodOptional<z.ZodEffects<z.ZodEffects<z.ZodString, string, string>, number, string>>;
    OPENAI_API_KEY: z.ZodOptional<z.ZodString>;
    NEXT_PUBLIC_BASE_URL: z.ZodOptional<z.ZodString>;
    STOCK_ALERT_RECIPIENTS: z.ZodOptional<z.ZodString>;
    STOCK_ALERT_WEBHOOK: z.ZodOptional<z.ZodString>;
    STOCK_ALERT_DEFAULT_THRESHOLD: z.ZodOptional<z.ZodNumber>;
    STOCK_ALERT_RECIPIENT: z.ZodOptional<z.ZodString>;
    TRYON_PROVIDER: z.ZodDefault<z.ZodEnum<["workers-ai", "external-api"]>>;
    TRYON_HEAVY_API_URL: z.ZodOptional<z.ZodString>;
    CLOUDFLARE_AI_GATEWAY_ID: z.ZodOptional<z.ZodString>;
    R2_BUCKET_TRYON: z.ZodOptional<z.ZodString>;
    R2_PUBLIC_BASE_URL: z.ZodOptional<z.ZodString>;
    R2_ACCESS_KEY_ID: z.ZodOptional<z.ZodString>;
    R2_SECRET_ACCESS_KEY: z.ZodOptional<z.ZodString>;
} & {
    AUTH_TOKEN_TTL: z.ZodOptional<z.ZodUnion<[z.ZodString, z.ZodNumber]>>;
}, z.ZodTypeAny, "passthrough">, z.objectInputType<Omit<{
    NEXTAUTH_SECRET: z.ZodEffects<z.ZodString, string, string> | z.ZodDefault<z.ZodEffects<z.ZodString, string, string>>;
    PREVIEW_TOKEN_SECRET: z.ZodOptional<z.ZodEffects<z.ZodString, string, string>>;
    UPGRADE_PREVIEW_TOKEN_SECRET: z.ZodOptional<z.ZodEffects<z.ZodString, string, string>>;
    SESSION_SECRET: z.ZodEffects<z.ZodString, string, string> | z.ZodDefault<z.ZodEffects<z.ZodString, string, string>>;
    COOKIE_DOMAIN: z.ZodOptional<z.ZodString>;
    LOGIN_RATE_LIMIT_REDIS_URL: z.ZodOptional<z.ZodString>;
    LOGIN_RATE_LIMIT_REDIS_TOKEN: z.ZodOptional<z.ZodEffects<z.ZodString, string, string>>;
    RATE_LIMIT_STORE_PROVIDER: z.ZodOptional<z.ZodEnum<["redis", "kv"]>>;
    CART_STORE_PROVIDER: z.ZodOptional<z.ZodEnum<["redis", "cloudflare", "memory"]>>;
    SESSION_STORE_PROVIDER: z.ZodOptional<z.ZodEnum<["redis", "cloudflare", "memory"]>>;
    SESSION_STORE: z.ZodOptional<z.ZodEnum<["memory", "redis"]>>;
    UPSTASH_REDIS_REST_URL: z.ZodOptional<z.ZodString>;
    UPSTASH_REDIS_REST_TOKEN: z.ZodOptional<z.ZodEffects<z.ZodString, string, string>>;
    AUTH_PROVIDER: z.ZodDefault<z.ZodEnum<["local", "jwt", "oauth"]>>;
    JWT_SECRET: z.ZodOptional<z.ZodEffects<z.ZodString, string, string>>;
    OAUTH_ISSUER: z.ZodOptional<z.ZodString>;
    OAUTH_CLIENT_ID: z.ZodOptional<z.ZodString>;
    OAUTH_CLIENT_SECRET: z.ZodOptional<z.ZodEffects<z.ZodString, string, string>>;
    OAUTH_REDIRECT_ORIGIN: z.ZodOptional<z.ZodString>;
    OAUTH_ENFORCE_PKCE: z.ZodOptional<z.ZodEffects<z.ZodBoolean, boolean, unknown>>;
    AUTH_TOKEN_TTL: z.ZodEffects<z.ZodEffects<z.ZodDefault<z.ZodEffects<z.ZodOptional<z.ZodString>, string | undefined, unknown>>, string, unknown>, number, unknown>;
    TOKEN_ALGORITHM: z.ZodDefault<z.ZodEnum<["HS256", "RS256"]>>;
    TOKEN_AUDIENCE: z.ZodDefault<z.ZodString>;
    TOKEN_ISSUER: z.ZodDefault<z.ZodString>;
    ALLOW_GUEST: z.ZodDefault<z.ZodEffects<z.ZodBoolean, boolean, unknown>>;
    ENFORCE_2FA: z.ZodDefault<z.ZodEffects<z.ZodBoolean, boolean, unknown>>;
}, "AUTH_TOKEN_TTL"> & {
    CMS_SPACE_URL: z.ZodString | z.ZodDefault<z.ZodString>;
    CMS_ACCESS_TOKEN: z.ZodString | z.ZodDefault<z.ZodString>;
    SANITY_API_VERSION: z.ZodEffects<z.ZodDefault<z.ZodEffects<z.ZodString, string, string>>, string, unknown>;
    SANITY_PROJECT_ID: z.ZodString | z.ZodDefault<z.ZodString>;
    SANITY_DATASET: z.ZodString | z.ZodDefault<z.ZodString>;
    SANITY_API_TOKEN: z.ZodString | z.ZodDefault<z.ZodString>;
    SANITY_PREVIEW_SECRET: z.ZodString | z.ZodDefault<z.ZodString>;
    SANITY_BASE_URL: z.ZodOptional<z.ZodEffects<z.ZodString, string, string>>;
    CMS_BASE_URL: z.ZodOptional<z.ZodEffects<z.ZodString, string, string>>;
    CMS_PAGINATION_LIMIT: z.ZodDefault<z.ZodNumber>;
    CMS_DRAFTS_ENABLED: z.ZodDefault<z.ZodEffects<z.ZodBoolean, boolean, unknown>>;
    CMS_DRAFTS_DISABLED_PATHS: z.ZodEffects<z.ZodDefault<z.ZodString>, string[], string | undefined>;
    CMS_SEARCH_ENABLED: z.ZodDefault<z.ZodEffects<z.ZodBoolean, boolean, unknown>>;
    CMS_SEARCH_DISABLED_PATHS: z.ZodEffects<z.ZodDefault<z.ZodString>, string[], string | undefined>;
} & {
    EMAIL_FROM: z.ZodOptional<z.ZodEffects<z.ZodString, string, string>>;
    EMAIL_SENDER_NAME: z.ZodOptional<z.ZodString>;
    GMAIL_USER: z.ZodOptional<z.ZodString>;
    GMAIL_PASS: z.ZodOptional<z.ZodString>;
    SMTP_URL: z.ZodOptional<z.ZodString>;
    SMTP_PORT: z.ZodOptional<z.ZodEffects<z.ZodEffects<z.ZodString, string, string>, number, string>>;
    SMTP_SECURE: z.ZodOptional<z.ZodEffects<z.ZodEffects<z.ZodEffects<z.ZodString, string, string>, string, string>, boolean, string>>;
    CAMPAIGN_FROM: z.ZodOptional<z.ZodEffects<z.ZodString, string, string>>;
    EMAIL_PROVIDER: z.ZodDefault<z.ZodEnum<["sendgrid", "resend", "smtp", "noop"]>>;
    SENDGRID_API_KEY: z.ZodOptional<z.ZodString>;
    SENDGRID_MARKETING_KEY: z.ZodOptional<z.ZodString>;
    RESEND_API_KEY: z.ZodOptional<z.ZodString>;
    EMAIL_BATCH_SIZE: z.ZodOptional<z.ZodNumber>;
    EMAIL_BATCH_DELAY_MS: z.ZodOptional<z.ZodNumber>;
} & {
    PAYMENTS_PROVIDER: z.ZodOptional<z.ZodEnum<["stripe"]>>;
    PAYMENTS_SANDBOX: z.ZodEffects<z.ZodEffects<z.ZodOptional<z.ZodString>, string | undefined, string | undefined>, boolean, string | undefined>;
    PAYMENTS_CURRENCY: z.ZodEffects<z.ZodDefault<z.ZodString>, string, string | undefined>;
    STRIPE_SECRET_KEY: z.ZodDefault<z.ZodString>;
    NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY: z.ZodDefault<z.ZodString>;
    STRIPE_WEBHOOK_SECRET: z.ZodDefault<z.ZodString>;
} & {
    TAXJAR_KEY: z.ZodOptional<z.ZodString>;
    UPS_KEY: z.ZodOptional<z.ZodString>;
    DHL_KEY: z.ZodOptional<z.ZodString>;
    SHIPPING_PROVIDER: z.ZodOptional<z.ZodEnum<["none", "external", "shippo", "ups", "dhl"]>>;
    ALLOWED_COUNTRIES: z.ZodEffects<z.ZodOptional<z.ZodArray<z.ZodString, "many">>, string[] | undefined, unknown>;
    LOCAL_PICKUP_ENABLED: z.ZodEffects<z.ZodEffects<z.ZodEffects<z.ZodOptional<z.ZodString>, string | undefined, unknown>, string | undefined, unknown>, boolean | undefined, unknown>;
    DEFAULT_COUNTRY: z.ZodEffects<z.ZodEffects<z.ZodOptional<z.ZodString>, string | undefined, unknown>, string | undefined, unknown>;
    DEFAULT_SHIPPING_ZONE: z.ZodOptional<z.ZodEnum<["domestic", "eu", "international"]>>;
    FREE_SHIPPING_THRESHOLD: z.ZodEffects<z.ZodOptional<z.ZodNumber>, number | undefined, unknown>;
} & {
    NODE_ENV: z.ZodOptional<z.ZodEnum<["development", "test", "production"]>>;
    OUTPUT_EXPORT: z.ZodOptional<z.ZodBoolean>;
    NEXT_PUBLIC_PHASE: z.ZodOptional<z.ZodString>;
    NEXT_PUBLIC_DEFAULT_SHOP: z.ZodOptional<z.ZodString>;
    NEXT_PUBLIC_SHOP_ID: z.ZodOptional<z.ZodString>;
    SHOP_CODE: z.ZodOptional<z.ZodString>;
    CART_COOKIE_SECRET: z.ZodString | z.ZodDefault<z.ZodString>;
    CART_TTL: z.ZodOptional<z.ZodNumber>;
    CHROMATIC_PROJECT_TOKEN: z.ZodOptional<z.ZodString>;
    GA_API_SECRET: z.ZodOptional<z.ZodString>;
    DATABASE_URL: z.ZodOptional<z.ZodString>;
    CLOUDFLARE_ACCOUNT_ID: z.ZodOptional<z.ZodString>;
    CLOUDFLARE_API_TOKEN: z.ZodOptional<z.ZodString>;
    LUXURY_FEATURES_RA_TICKETING: z.ZodOptional<z.ZodBoolean>;
    LUXURY_FEATURES_FRAUD_REVIEW_THRESHOLD: z.ZodOptional<z.ZodNumber>;
    LUXURY_FEATURES_REQUIRE_STRONG_CUSTOMER_AUTH: z.ZodOptional<z.ZodBoolean>;
    LUXURY_FEATURES_TRACKING_DASHBOARD: z.ZodOptional<z.ZodBoolean>;
    LUXURY_FEATURES_RETURNS: z.ZodOptional<z.ZodBoolean>;
    DEPOSIT_RELEASE_ENABLED: z.ZodOptional<z.ZodEffects<z.ZodEffects<z.ZodString, "true" | "false", string>, boolean, string>>;
    DEPOSIT_RELEASE_INTERVAL_MS: z.ZodOptional<z.ZodEffects<z.ZodEffects<z.ZodString, string, string>, number, string>>;
    REVERSE_LOGISTICS_ENABLED: z.ZodOptional<z.ZodEffects<z.ZodEffects<z.ZodString, "true" | "false", string>, boolean, string>>;
    REVERSE_LOGISTICS_INTERVAL_MS: z.ZodOptional<z.ZodEffects<z.ZodEffects<z.ZodString, string, string>, number, string>>;
    LATE_FEE_ENABLED: z.ZodOptional<z.ZodEffects<z.ZodEffects<z.ZodString, "true" | "false", string>, boolean, string>>;
    LATE_FEE_INTERVAL_MS: z.ZodOptional<z.ZodEffects<z.ZodEffects<z.ZodString, string, string>, number, string>>;
    OPENAI_API_KEY: z.ZodOptional<z.ZodString>;
    NEXT_PUBLIC_BASE_URL: z.ZodOptional<z.ZodString>;
    STOCK_ALERT_RECIPIENTS: z.ZodOptional<z.ZodString>;
    STOCK_ALERT_WEBHOOK: z.ZodOptional<z.ZodString>;
    STOCK_ALERT_DEFAULT_THRESHOLD: z.ZodOptional<z.ZodNumber>;
    STOCK_ALERT_RECIPIENT: z.ZodOptional<z.ZodString>;
    TRYON_PROVIDER: z.ZodDefault<z.ZodEnum<["workers-ai", "external-api"]>>;
    TRYON_HEAVY_API_URL: z.ZodOptional<z.ZodString>;
    CLOUDFLARE_AI_GATEWAY_ID: z.ZodOptional<z.ZodString>;
    R2_BUCKET_TRYON: z.ZodOptional<z.ZodString>;
    R2_PUBLIC_BASE_URL: z.ZodOptional<z.ZodString>;
    R2_ACCESS_KEY_ID: z.ZodOptional<z.ZodString>;
    R2_SECRET_ACCESS_KEY: z.ZodOptional<z.ZodString>;
} & {
    AUTH_TOKEN_TTL: z.ZodOptional<z.ZodUnion<[z.ZodString, z.ZodNumber]>>;
}, z.ZodTypeAny, "passthrough">>, z.objectOutputType<Omit<{
    NEXTAUTH_SECRET: z.ZodEffects<z.ZodString, string, string> | z.ZodDefault<z.ZodEffects<z.ZodString, string, string>>;
    PREVIEW_TOKEN_SECRET: z.ZodOptional<z.ZodEffects<z.ZodString, string, string>>;
    UPGRADE_PREVIEW_TOKEN_SECRET: z.ZodOptional<z.ZodEffects<z.ZodString, string, string>>;
    SESSION_SECRET: z.ZodEffects<z.ZodString, string, string> | z.ZodDefault<z.ZodEffects<z.ZodString, string, string>>;
    COOKIE_DOMAIN: z.ZodOptional<z.ZodString>;
    LOGIN_RATE_LIMIT_REDIS_URL: z.ZodOptional<z.ZodString>;
    LOGIN_RATE_LIMIT_REDIS_TOKEN: z.ZodOptional<z.ZodEffects<z.ZodString, string, string>>;
    RATE_LIMIT_STORE_PROVIDER: z.ZodOptional<z.ZodEnum<["redis", "kv"]>>;
    CART_STORE_PROVIDER: z.ZodOptional<z.ZodEnum<["redis", "cloudflare", "memory"]>>;
    SESSION_STORE_PROVIDER: z.ZodOptional<z.ZodEnum<["redis", "cloudflare", "memory"]>>;
    SESSION_STORE: z.ZodOptional<z.ZodEnum<["memory", "redis"]>>;
    UPSTASH_REDIS_REST_URL: z.ZodOptional<z.ZodString>;
    UPSTASH_REDIS_REST_TOKEN: z.ZodOptional<z.ZodEffects<z.ZodString, string, string>>;
    AUTH_PROVIDER: z.ZodDefault<z.ZodEnum<["local", "jwt", "oauth"]>>;
    JWT_SECRET: z.ZodOptional<z.ZodEffects<z.ZodString, string, string>>;
    OAUTH_ISSUER: z.ZodOptional<z.ZodString>;
    OAUTH_CLIENT_ID: z.ZodOptional<z.ZodString>;
    OAUTH_CLIENT_SECRET: z.ZodOptional<z.ZodEffects<z.ZodString, string, string>>;
    OAUTH_REDIRECT_ORIGIN: z.ZodOptional<z.ZodString>;
    OAUTH_ENFORCE_PKCE: z.ZodOptional<z.ZodEffects<z.ZodBoolean, boolean, unknown>>;
    AUTH_TOKEN_TTL: z.ZodEffects<z.ZodEffects<z.ZodDefault<z.ZodEffects<z.ZodOptional<z.ZodString>, string | undefined, unknown>>, string, unknown>, number, unknown>;
    TOKEN_ALGORITHM: z.ZodDefault<z.ZodEnum<["HS256", "RS256"]>>;
    TOKEN_AUDIENCE: z.ZodDefault<z.ZodString>;
    TOKEN_ISSUER: z.ZodDefault<z.ZodString>;
    ALLOW_GUEST: z.ZodDefault<z.ZodEffects<z.ZodBoolean, boolean, unknown>>;
    ENFORCE_2FA: z.ZodDefault<z.ZodEffects<z.ZodBoolean, boolean, unknown>>;
}, "AUTH_TOKEN_TTL"> & {
    CMS_SPACE_URL: z.ZodString | z.ZodDefault<z.ZodString>;
    CMS_ACCESS_TOKEN: z.ZodString | z.ZodDefault<z.ZodString>;
    SANITY_API_VERSION: z.ZodEffects<z.ZodDefault<z.ZodEffects<z.ZodString, string, string>>, string, unknown>;
    SANITY_PROJECT_ID: z.ZodString | z.ZodDefault<z.ZodString>;
    SANITY_DATASET: z.ZodString | z.ZodDefault<z.ZodString>;
    SANITY_API_TOKEN: z.ZodString | z.ZodDefault<z.ZodString>;
    SANITY_PREVIEW_SECRET: z.ZodString | z.ZodDefault<z.ZodString>;
    SANITY_BASE_URL: z.ZodOptional<z.ZodEffects<z.ZodString, string, string>>;
    CMS_BASE_URL: z.ZodOptional<z.ZodEffects<z.ZodString, string, string>>;
    CMS_PAGINATION_LIMIT: z.ZodDefault<z.ZodNumber>;
    CMS_DRAFTS_ENABLED: z.ZodDefault<z.ZodEffects<z.ZodBoolean, boolean, unknown>>;
    CMS_DRAFTS_DISABLED_PATHS: z.ZodEffects<z.ZodDefault<z.ZodString>, string[], string | undefined>;
    CMS_SEARCH_ENABLED: z.ZodDefault<z.ZodEffects<z.ZodBoolean, boolean, unknown>>;
    CMS_SEARCH_DISABLED_PATHS: z.ZodEffects<z.ZodDefault<z.ZodString>, string[], string | undefined>;
} & {
    EMAIL_FROM: z.ZodOptional<z.ZodEffects<z.ZodString, string, string>>;
    EMAIL_SENDER_NAME: z.ZodOptional<z.ZodString>;
    GMAIL_USER: z.ZodOptional<z.ZodString>;
    GMAIL_PASS: z.ZodOptional<z.ZodString>;
    SMTP_URL: z.ZodOptional<z.ZodString>;
    SMTP_PORT: z.ZodOptional<z.ZodEffects<z.ZodEffects<z.ZodString, string, string>, number, string>>;
    SMTP_SECURE: z.ZodOptional<z.ZodEffects<z.ZodEffects<z.ZodEffects<z.ZodString, string, string>, string, string>, boolean, string>>;
    CAMPAIGN_FROM: z.ZodOptional<z.ZodEffects<z.ZodString, string, string>>;
    EMAIL_PROVIDER: z.ZodDefault<z.ZodEnum<["sendgrid", "resend", "smtp", "noop"]>>;
    SENDGRID_API_KEY: z.ZodOptional<z.ZodString>;
    SENDGRID_MARKETING_KEY: z.ZodOptional<z.ZodString>;
    RESEND_API_KEY: z.ZodOptional<z.ZodString>;
    EMAIL_BATCH_SIZE: z.ZodOptional<z.ZodNumber>;
    EMAIL_BATCH_DELAY_MS: z.ZodOptional<z.ZodNumber>;
} & {
    PAYMENTS_PROVIDER: z.ZodOptional<z.ZodEnum<["stripe"]>>;
    PAYMENTS_SANDBOX: z.ZodEffects<z.ZodEffects<z.ZodOptional<z.ZodString>, string | undefined, string | undefined>, boolean, string | undefined>;
    PAYMENTS_CURRENCY: z.ZodEffects<z.ZodDefault<z.ZodString>, string, string | undefined>;
    STRIPE_SECRET_KEY: z.ZodDefault<z.ZodString>;
    NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY: z.ZodDefault<z.ZodString>;
    STRIPE_WEBHOOK_SECRET: z.ZodDefault<z.ZodString>;
} & {
    TAXJAR_KEY: z.ZodOptional<z.ZodString>;
    UPS_KEY: z.ZodOptional<z.ZodString>;
    DHL_KEY: z.ZodOptional<z.ZodString>;
    SHIPPING_PROVIDER: z.ZodOptional<z.ZodEnum<["none", "external", "shippo", "ups", "dhl"]>>;
    ALLOWED_COUNTRIES: z.ZodEffects<z.ZodOptional<z.ZodArray<z.ZodString, "many">>, string[] | undefined, unknown>;
    LOCAL_PICKUP_ENABLED: z.ZodEffects<z.ZodEffects<z.ZodEffects<z.ZodOptional<z.ZodString>, string | undefined, unknown>, string | undefined, unknown>, boolean | undefined, unknown>;
    DEFAULT_COUNTRY: z.ZodEffects<z.ZodEffects<z.ZodOptional<z.ZodString>, string | undefined, unknown>, string | undefined, unknown>;
    DEFAULT_SHIPPING_ZONE: z.ZodOptional<z.ZodEnum<["domestic", "eu", "international"]>>;
    FREE_SHIPPING_THRESHOLD: z.ZodEffects<z.ZodOptional<z.ZodNumber>, number | undefined, unknown>;
} & {
    NODE_ENV: z.ZodOptional<z.ZodEnum<["development", "test", "production"]>>;
    OUTPUT_EXPORT: z.ZodOptional<z.ZodBoolean>;
    NEXT_PUBLIC_PHASE: z.ZodOptional<z.ZodString>;
    NEXT_PUBLIC_DEFAULT_SHOP: z.ZodOptional<z.ZodString>;
    NEXT_PUBLIC_SHOP_ID: z.ZodOptional<z.ZodString>;
    SHOP_CODE: z.ZodOptional<z.ZodString>;
    CART_COOKIE_SECRET: z.ZodString | z.ZodDefault<z.ZodString>;
    CART_TTL: z.ZodOptional<z.ZodNumber>;
    CHROMATIC_PROJECT_TOKEN: z.ZodOptional<z.ZodString>;
    GA_API_SECRET: z.ZodOptional<z.ZodString>;
    DATABASE_URL: z.ZodOptional<z.ZodString>;
    CLOUDFLARE_ACCOUNT_ID: z.ZodOptional<z.ZodString>;
    CLOUDFLARE_API_TOKEN: z.ZodOptional<z.ZodString>;
    LUXURY_FEATURES_RA_TICKETING: z.ZodOptional<z.ZodBoolean>;
    LUXURY_FEATURES_FRAUD_REVIEW_THRESHOLD: z.ZodOptional<z.ZodNumber>;
    LUXURY_FEATURES_REQUIRE_STRONG_CUSTOMER_AUTH: z.ZodOptional<z.ZodBoolean>;
    LUXURY_FEATURES_TRACKING_DASHBOARD: z.ZodOptional<z.ZodBoolean>;
    LUXURY_FEATURES_RETURNS: z.ZodOptional<z.ZodBoolean>;
    DEPOSIT_RELEASE_ENABLED: z.ZodOptional<z.ZodEffects<z.ZodEffects<z.ZodString, "true" | "false", string>, boolean, string>>;
    DEPOSIT_RELEASE_INTERVAL_MS: z.ZodOptional<z.ZodEffects<z.ZodEffects<z.ZodString, string, string>, number, string>>;
    REVERSE_LOGISTICS_ENABLED: z.ZodOptional<z.ZodEffects<z.ZodEffects<z.ZodString, "true" | "false", string>, boolean, string>>;
    REVERSE_LOGISTICS_INTERVAL_MS: z.ZodOptional<z.ZodEffects<z.ZodEffects<z.ZodString, string, string>, number, string>>;
    LATE_FEE_ENABLED: z.ZodOptional<z.ZodEffects<z.ZodEffects<z.ZodString, "true" | "false", string>, boolean, string>>;
    LATE_FEE_INTERVAL_MS: z.ZodOptional<z.ZodEffects<z.ZodEffects<z.ZodString, string, string>, number, string>>;
    OPENAI_API_KEY: z.ZodOptional<z.ZodString>;
    NEXT_PUBLIC_BASE_URL: z.ZodOptional<z.ZodString>;
    STOCK_ALERT_RECIPIENTS: z.ZodOptional<z.ZodString>;
    STOCK_ALERT_WEBHOOK: z.ZodOptional<z.ZodString>;
    STOCK_ALERT_DEFAULT_THRESHOLD: z.ZodOptional<z.ZodNumber>;
    STOCK_ALERT_RECIPIENT: z.ZodOptional<z.ZodString>;
    TRYON_PROVIDER: z.ZodDefault<z.ZodEnum<["workers-ai", "external-api"]>>;
    TRYON_HEAVY_API_URL: z.ZodOptional<z.ZodString>;
    CLOUDFLARE_AI_GATEWAY_ID: z.ZodOptional<z.ZodString>;
    R2_BUCKET_TRYON: z.ZodOptional<z.ZodString>;
    R2_PUBLIC_BASE_URL: z.ZodOptional<z.ZodString>;
    R2_ACCESS_KEY_ID: z.ZodOptional<z.ZodString>;
    R2_SECRET_ACCESS_KEY: z.ZodOptional<z.ZodString>;
} & {
    AUTH_TOKEN_TTL: z.ZodOptional<z.ZodUnion<[z.ZodString, z.ZodNumber]>>;
}, z.ZodTypeAny, "passthrough">, unknown>;
