/**
 * Reception theme token overrides.
 *
 * Reception is a dark-first hospitality POS interface used in hostel
 * environments. Green-on-black terminal aesthetic with high-contrast
 * status signals for operational awareness.
 *
 * Only tokens that differ from base are defined here.
 */

import type { Token, TokenMap } from '@themes/base';

export const tokens: TokenMap = {
  // Brand: hospitality green primary (operational readiness signal)
  // Values in oklch() format — generated by scripts/src/themes/hsl-to-oklch.ts
  // Consumed via var() in @theme {} (no hsl() wrapper needed with pre-wrapped oklch)
  '--color-primary': { light: 'oklch(0.538 0.141 149.79)', dark: 'oklch(0.753 0.2001 149.55)' },
  '--color-primary-fg': { light: 'oklch(1 0 89.88)', dark: 'oklch(0.147 0.003 174.11)' },
  '--color-primary-soft': { light: 'oklch(0.971 0.0205 158.25)', dark: 'oklch(0.298 0.0583 153.17)' },
  '--color-primary-hover': { light: 'oklch(0.472 0.1222 150.01)', dark: 'oklch(0.789 0.196 150.64)' },
  '--color-primary-active': { light: 'oklch(0.405 0.1026 150.33)', dark: 'oklch(0.802 0.1836 151.69)' },

  // Accent: warm amber/orange (hospitality warning signal)
  '--color-accent': { light: 'oklch(0.752 0.1641 66.87)', dark: 'oklch(0.778 0.1463 72.77)' },
  '--color-accent-fg': { light: 'oklch(0.216 0 89.88)', dark: 'oklch(0.216 0 89.88)' },
  '--color-accent-soft': { light: 'oklch(0.971 0.0184 78.24)', dark: 'oklch(0.316 0.052 74.85)' },

  // Surfaces: slightly warm-tinted for hospitality feel
  '--surface-1': { light: 'oklch(1 0 89.88)', dark: 'oklch(0.147 0.003 174.11)' },
  '--surface-2': { light: 'oklch(0.97 0.001 165.11)', dark: 'oklch(0.196 0.0055 173.75)' },
  '--surface-3': { light: 'oklch(0.94 0.0021 165.09)', dark: 'oklch(0.241 0.0059 173.86)' },
  '--surface-input': { light: 'oklch(0.978 0.0008 165.12)', dark: 'oklch(0.219 0.005 173.9)' },

  // Background with slight green tint in dark mode
  '--color-bg': { light: 'oklch(1 0 89.88)', dark: 'oklch(0.147 0.003 174.11)' },
  '--color-fg': { light: 'oklch(0.216 0 89.88)', dark: 'oklch(0.941 0.0051 165)' },
  '--color-fg-muted': { light: 'oklch(0.51 0 89.88)', dark: 'oklch(0.73 0.0119 164.71)' },

  // Panel and inset surfaces
  '--color-panel': { light: 'oklch(0.978 0.0008 165.12)', dark: 'oklch(0.219 0.005 173.9)' },
  '--color-inset': { light: 'oklch(0.985 0.0005 165.13)', dark: 'oklch(0.172 0.0043 173.85)' },

  // Borders: subtle green tint in dark mode
  '--color-border': { light: 'oklch(0.845 0 89.88)', dark: 'oklch(0.347 0.0108 164.3)' },
  '--color-border-strong': { light: 'oklch(0.724 0 89.88)', dark: 'oklch(0.473 0.0158 164.24)' },
  '--color-border-muted': { light: 'oklch(0.908 0 89.88)', dark: 'oklch(0.284 0.0069 164.49)' },

  // Focus ring: matches primary green
  '--color-focus-ring': { light: 'oklch(0.538 0.141 149.79)', dark: 'oklch(0.753 0.2001 149.55)' },
  '--ring': { light: 'oklch(0.538 0.141 149.79)', dark: 'oklch(0.753 0.2001 149.55)' },

  // Link color: green-tinted
  '--color-link': { light: 'oklch(0.489 0.117 151.16)', dark: 'oklch(0.798 0.1668 152.62)' },

  // Muted: green-tinted neutral
  '--color-muted': { light: 'oklch(0.909 0.0031 165.05)', dark: 'oklch(0.366 0.0097 164.43)' },
  '--color-muted-fg': { light: 'oklch(0.321 0 89.88)', dark: 'oklch(0.887 0.0049 165)' },

  // Typography: Inter for UI, JetBrains Mono for data/code
  '--font-sans': { light: 'var(--font-inter)' },
  '--font-mono': { light: 'var(--font-jetbrains-mono)' },

  // ── Category shade families (bar/POS product grid) ──────────────────
  // Stored as full oklch() values so CSS var resolves to a valid color directly.
  // This makes them safe for `@theme inline {}` in globals.css — Tailwind reads
  // the resolved value as-is without adding any wrapper.
  // Values generated by scripts/src/themes/hsl-to-oklch.ts from original HSL sources.
  // Pink shades (Sweet, Gelato)
  '--color-pinkShades-row1': { light: 'oklch(0.694 0.1309 349.72)', dark: 'oklch(0.325 0.0468 348.64)' },
  '--color-pinkShades-row2': { light: 'oklch(0.645 0.1543 351.06)', dark: 'oklch(0.362 0.0538 348.75)' },
  '--color-pinkShades-row3': { light: 'oklch(0.598 0.1619 351.99)', dark: 'oklch(0.4 0.0534 348.39)' },
  '--color-pinkShades-row4': { light: 'oklch(0.55 0.1543 352.32)', dark: 'oklch(0.437 0.0538 348.15)' },

  // Coffee shades
  '--color-coffeeShades-row1': { light: 'oklch(0.698 0.0744 56.69)', dark: 'oklch(0.346 0.0269 57.22)' },
  '--color-coffeeShades-row2': { light: 'oklch(0.637 0.0906 55.84)', dark: 'oklch(0.405 0.0329 57.17)' },
  '--color-coffeeShades-row3': { light: 'oklch(0.563 0.0751 56.08)', dark: 'oklch(0.462 0.0352 57.25)' },

  // Beer shades
  '--color-beerShades-row1': { light: 'oklch(0.735 0.1375 83.68)', dark: 'oklch(0.371 0.0395 87.26)' },
  '--color-beerShades-row2': { light: 'oklch(0.637 0.1142 84.51)', dark: 'oklch(0.434 0.0452 87.29)' },

  // Wine shades
  '--color-wineShades-row1': { light: 'oklch(0.498 0.1314 13.16)', dark: 'oklch(0.34 0.0456 8.91)' },
  '--color-wineShades-row2': { light: 'oklch(0.423 0.0973 11.87)', dark: 'oklch(0.396 0.0482 8.58)' },
  '--color-wineShades-row3': { light: 'oklch(0.354 0.0685 10.65)', dark: 'oklch(0.45 0.0508 8.34)' },

  // Tea shades
  '--color-teaShades-row1': { light: 'oklch(0.774 0.1115 124.03)', dark: 'oklch(0.373 0.0414 123.37)' },
  '--color-teaShades-row2': { light: 'oklch(0.723 0.1257 124.72)', dark: 'oklch(0.435 0.0462 123.28)' },

  // Green shades (Savory)
  '--color-greenShades-row1': { light: 'oklch(0.747 0.1129 153.61)', dark: 'oklch(0.363 0.0418 154.63)' },
  '--color-greenShades-row2': { light: 'oklch(0.694 0.1278 152.55)', dark: 'oklch(0.403 0.0439 154.79)' },
  '--color-greenShades-row3': { light: 'oklch(0.614 0.1115 152.64)', dark: 'oklch(0.441 0.0447 154.98)' },

  // Blue shades (Mixed Drinks)
  '--color-blueShades-row1': { light: 'oklch(0.668 0.0848 249.2)', dark: 'oklch(0.335 0.0311 248.78)' },
  '--color-blueShades-row2': { light: 'oklch(0.601 0.0964 249.71)', dark: 'oklch(0.374 0.0315 248.68)' },
  '--color-blueShades-row3': { light: 'oklch(0.533 0.0867 249.74)', dark: 'oklch(0.411 0.0323 248.62)' },
  '--color-blueShades-row4': { light: 'oklch(0.463 0.0701 249.56)', dark: 'oklch(0.449 0.0323 248.55)' },
  '--color-blueShades-row5': { light: 'oklch(0.391 0.0527 249.31)', dark: 'oklch(0.485 0.0315 248.48)' },

  // Purple shades (Cocktails)
  '--color-purpleShades-row1': { light: 'oklch(0.581 0.1397 305.57)', dark: 'oklch(0.335 0.0494 306.79)' },
  '--color-purpleShades-row2': { light: 'oklch(0.512 0.1468 304.85)', dark: 'oklch(0.39 0.0541 306.9)' },

  // Spritz shades
  '--color-spritzShades-row1': { light: 'oklch(0.652 0.1561 44.78)', dark: 'oklch(0.362 0.0407 47.56)' },
  '--color-spritzShades-row2': { light: 'oklch(0.582 0.1424 44.55)', dark: 'oklch(0.419 0.0458 47.6)' },

  // Orange shades (Juices/Smoothies/Soda)
  '--color-orangeShades-row1': { light: 'oklch(0.735 0.115 64.33)', dark: 'oklch(0.354 0.034 66.36)' },
  '--color-orangeShades-row2': { light: 'oklch(0.691 0.1215 63.25)', dark: 'oklch(0.394 0.0363 66.44)' },
  '--color-orangeShades-row3': { light: 'oklch(0.639 0.1174 62.72)', dark: 'oklch(0.432 0.0379 66.54)' },
  '--color-orangeShades-row4': { light: 'oklch(0.574 0.0975 63.62)', dark: 'oklch(0.47 0.0386 66.65)' },
  '--color-orangeShades-row5': { light: 'oklch(0.509 0.0786 64.43)', dark: 'oklch(0.506 0.0386 66.77)' },

  // Grayish shades (Other, Gelato)
  '--color-grayishShades-row1': { light: 'oklch(0.671 0.0216 264.42)', dark: 'oklch(0.336 0.0084 264.45)' },
  '--color-grayishShades-row2': { light: 'oklch(0.603 0.0213 264.4)', dark: 'oklch(0.394 0.0086 264.47)' },
  '--color-grayishShades-row3': { light: 'oklch(0.537 0.015 264.44)', dark: 'oklch(0.451 0.0081 264.49)' },
  '--color-grayishShades-row4': { light: 'oklch(0.468 0.0106 264.47)', dark: 'oklch(0.506 0.0069 264.5)' },

  // Chart palette: dark-mode-aware colours for Chart.js/Recharts datasets
  '--chart-1': { light: 'oklch(0.404 0.2037 272.54)', dark: 'oklch(0.655 0.1349 282.02)' },
  '--chart-2': { light: 'oklch(0.72 0.192 149.49)', dark: 'oklch(0.812 0.1789 152.1)' },
  '--chart-3': { light: 'oklch(0.707 0.186 48.13)', dark: 'oklch(0.786 0.1345 54.89)' },
  '--chart-4': { light: 'oklch(0.587 0.2224 17.72)', dark: 'oklch(0.673 0.1712 9.58)' },
  '--chart-5': { light: 'oklch(0.666 0.1127 184.18)', dark: 'oklch(0.83 0.124 185.68)' },
  '--chart-6': { light: 'oklch(0.678 0.1481 238.1)', dark: 'oklch(0.763 0.1272 232.06)' },
  '--chart-7': { light: 'oklch(0.69 0.1481 162.37)', dark: 'oklch(0.84 0.171 164.04)' },
};

export type { Token, TokenMap };
