import "@acme/zod-utils/initZod";
import { z } from "zod";
export declare const authEnvSchema: z.ZodEffects<z.ZodObject<{
    NEXTAUTH_SECRET: z.ZodEffects<z.ZodString, string, string> | z.ZodDefault<z.ZodEffects<z.ZodString, string, string>>;
    PREVIEW_TOKEN_SECRET: z.ZodOptional<z.ZodEffects<z.ZodString, string, string>>;
    UPGRADE_PREVIEW_TOKEN_SECRET: z.ZodOptional<z.ZodEffects<z.ZodString, string, string>>;
    SESSION_SECRET: z.ZodEffects<z.ZodString, string, string> | z.ZodDefault<z.ZodEffects<z.ZodString, string, string>>;
    COOKIE_DOMAIN: z.ZodOptional<z.ZodString>;
    LOGIN_RATE_LIMIT_REDIS_URL: z.ZodOptional<z.ZodString>;
    LOGIN_RATE_LIMIT_REDIS_TOKEN: z.ZodOptional<z.ZodEffects<z.ZodString, string, string>>;
    RATE_LIMIT_STORE_PROVIDER: z.ZodOptional<z.ZodEnum<["redis", "kv"]>>;
    CART_STORE_PROVIDER: z.ZodOptional<z.ZodEnum<["redis", "cloudflare", "memory"]>>;
    SESSION_STORE_PROVIDER: z.ZodOptional<z.ZodEnum<["redis", "cloudflare", "memory"]>>;
    SESSION_STORE: z.ZodOptional<z.ZodEnum<["memory", "redis"]>>;
    UPSTASH_REDIS_REST_URL: z.ZodOptional<z.ZodString>;
    UPSTASH_REDIS_REST_TOKEN: z.ZodOptional<z.ZodEffects<z.ZodString, string, string>>;
    AUTH_PROVIDER: z.ZodDefault<z.ZodEnum<["local", "jwt", "oauth"]>>;
    JWT_SECRET: z.ZodOptional<z.ZodEffects<z.ZodString, string, string>>;
    OAUTH_ISSUER: z.ZodOptional<z.ZodString>;
    OAUTH_CLIENT_ID: z.ZodOptional<z.ZodString>;
    OAUTH_CLIENT_SECRET: z.ZodOptional<z.ZodEffects<z.ZodString, string, string>>;
    OAUTH_REDIRECT_ORIGIN: z.ZodOptional<z.ZodString>;
    OAUTH_ENFORCE_PKCE: z.ZodOptional<z.ZodEffects<z.ZodBoolean, boolean, unknown>>;
    AUTH_TOKEN_TTL: z.ZodEffects<z.ZodEffects<z.ZodDefault<z.ZodEffects<z.ZodOptional<z.ZodString>, string | undefined, unknown>>, string, unknown>, number, unknown>;
    TOKEN_ALGORITHM: z.ZodDefault<z.ZodEnum<["HS256", "RS256"]>>;
    TOKEN_AUDIENCE: z.ZodDefault<z.ZodString>;
    TOKEN_ISSUER: z.ZodDefault<z.ZodString>;
    ALLOW_GUEST: z.ZodDefault<z.ZodEffects<z.ZodBoolean, boolean, unknown>>;
    ENFORCE_2FA: z.ZodDefault<z.ZodEffects<z.ZodBoolean, boolean, unknown>>;
}, "strip", z.ZodTypeAny, {
    AUTH_TOKEN_TTL: number;
    NEXTAUTH_SECRET: string;
    SESSION_SECRET: string;
    AUTH_PROVIDER: "local" | "jwt" | "oauth";
    TOKEN_ALGORITHM: "HS256" | "RS256";
    TOKEN_AUDIENCE: string;
    TOKEN_ISSUER: string;
    ALLOW_GUEST: boolean;
    ENFORCE_2FA: boolean;
    PREVIEW_TOKEN_SECRET?: string | undefined;
    UPGRADE_PREVIEW_TOKEN_SECRET?: string | undefined;
    COOKIE_DOMAIN?: string | undefined;
    LOGIN_RATE_LIMIT_REDIS_URL?: string | undefined;
    LOGIN_RATE_LIMIT_REDIS_TOKEN?: string | undefined;
    RATE_LIMIT_STORE_PROVIDER?: "redis" | "kv" | undefined;
    CART_STORE_PROVIDER?: "redis" | "cloudflare" | "memory" | undefined;
    SESSION_STORE_PROVIDER?: "redis" | "cloudflare" | "memory" | undefined;
    SESSION_STORE?: "redis" | "memory" | undefined;
    UPSTASH_REDIS_REST_URL?: string | undefined;
    UPSTASH_REDIS_REST_TOKEN?: string | undefined;
    JWT_SECRET?: string | undefined;
    OAUTH_ISSUER?: string | undefined;
    OAUTH_CLIENT_ID?: string | undefined;
    OAUTH_CLIENT_SECRET?: string | undefined;
    OAUTH_REDIRECT_ORIGIN?: string | undefined;
    OAUTH_ENFORCE_PKCE?: boolean | undefined;
}, {
    AUTH_TOKEN_TTL?: unknown;
    NEXTAUTH_SECRET?: string | undefined;
    PREVIEW_TOKEN_SECRET?: string | undefined;
    UPGRADE_PREVIEW_TOKEN_SECRET?: string | undefined;
    SESSION_SECRET?: string | undefined;
    COOKIE_DOMAIN?: string | undefined;
    LOGIN_RATE_LIMIT_REDIS_URL?: string | undefined;
    LOGIN_RATE_LIMIT_REDIS_TOKEN?: string | undefined;
    RATE_LIMIT_STORE_PROVIDER?: "redis" | "kv" | undefined;
    CART_STORE_PROVIDER?: "redis" | "cloudflare" | "memory" | undefined;
    SESSION_STORE_PROVIDER?: "redis" | "cloudflare" | "memory" | undefined;
    SESSION_STORE?: "redis" | "memory" | undefined;
    UPSTASH_REDIS_REST_URL?: string | undefined;
    UPSTASH_REDIS_REST_TOKEN?: string | undefined;
    AUTH_PROVIDER?: "local" | "jwt" | "oauth" | undefined;
    JWT_SECRET?: string | undefined;
    OAUTH_ISSUER?: string | undefined;
    OAUTH_CLIENT_ID?: string | undefined;
    OAUTH_CLIENT_SECRET?: string | undefined;
    OAUTH_REDIRECT_ORIGIN?: string | undefined;
    OAUTH_ENFORCE_PKCE?: unknown;
    TOKEN_ALGORITHM?: "HS256" | "RS256" | undefined;
    TOKEN_AUDIENCE?: string | undefined;
    TOKEN_ISSUER?: string | undefined;
    ALLOW_GUEST?: unknown;
    ENFORCE_2FA?: unknown;
}>, {
    AUTH_TOKEN_TTL: number;
    NEXTAUTH_SECRET: string;
    SESSION_SECRET: string;
    AUTH_PROVIDER: "local" | "jwt" | "oauth";
    TOKEN_ALGORITHM: "HS256" | "RS256";
    TOKEN_AUDIENCE: string;
    TOKEN_ISSUER: string;
    ALLOW_GUEST: boolean;
    ENFORCE_2FA: boolean;
    PREVIEW_TOKEN_SECRET?: string | undefined;
    UPGRADE_PREVIEW_TOKEN_SECRET?: string | undefined;
    COOKIE_DOMAIN?: string | undefined;
    LOGIN_RATE_LIMIT_REDIS_URL?: string | undefined;
    LOGIN_RATE_LIMIT_REDIS_TOKEN?: string | undefined;
    RATE_LIMIT_STORE_PROVIDER?: "redis" | "kv" | undefined;
    CART_STORE_PROVIDER?: "redis" | "cloudflare" | "memory" | undefined;
    SESSION_STORE_PROVIDER?: "redis" | "cloudflare" | "memory" | undefined;
    SESSION_STORE?: "redis" | "memory" | undefined;
    UPSTASH_REDIS_REST_URL?: string | undefined;
    UPSTASH_REDIS_REST_TOKEN?: string | undefined;
    JWT_SECRET?: string | undefined;
    OAUTH_ISSUER?: string | undefined;
    OAUTH_CLIENT_ID?: string | undefined;
    OAUTH_CLIENT_SECRET?: string | undefined;
    OAUTH_REDIRECT_ORIGIN?: string | undefined;
    OAUTH_ENFORCE_PKCE?: boolean | undefined;
}, {
    AUTH_TOKEN_TTL?: unknown;
    NEXTAUTH_SECRET?: string | undefined;
    PREVIEW_TOKEN_SECRET?: string | undefined;
    UPGRADE_PREVIEW_TOKEN_SECRET?: string | undefined;
    SESSION_SECRET?: string | undefined;
    COOKIE_DOMAIN?: string | undefined;
    LOGIN_RATE_LIMIT_REDIS_URL?: string | undefined;
    LOGIN_RATE_LIMIT_REDIS_TOKEN?: string | undefined;
    RATE_LIMIT_STORE_PROVIDER?: "redis" | "kv" | undefined;
    CART_STORE_PROVIDER?: "redis" | "cloudflare" | "memory" | undefined;
    SESSION_STORE_PROVIDER?: "redis" | "cloudflare" | "memory" | undefined;
    SESSION_STORE?: "redis" | "memory" | undefined;
    UPSTASH_REDIS_REST_URL?: string | undefined;
    UPSTASH_REDIS_REST_TOKEN?: string | undefined;
    AUTH_PROVIDER?: "local" | "jwt" | "oauth" | undefined;
    JWT_SECRET?: string | undefined;
    OAUTH_ISSUER?: string | undefined;
    OAUTH_CLIENT_ID?: string | undefined;
    OAUTH_CLIENT_SECRET?: string | undefined;
    OAUTH_REDIRECT_ORIGIN?: string | undefined;
    OAUTH_ENFORCE_PKCE?: unknown;
    TOKEN_ALGORITHM?: "HS256" | "RS256" | undefined;
    TOKEN_AUDIENCE?: string | undefined;
    TOKEN_ISSUER?: string | undefined;
    ALLOW_GUEST?: unknown;
    ENFORCE_2FA?: unknown;
}>;
type ParsedAuthEnv = z.infer<typeof authEnvSchema>;
export type AuthEnv = ParsedAuthEnv & {
    AUTH_TOKEN_EXPIRES_AT: Date;
};
export declare function loadAuthEnv(raw?: NodeJS.ProcessEnv, opts?: {
    allowNumericTtl?: boolean;
}): AuthEnv;
export declare const authEnv: AuthEnv;
export {};
