import "@acme/lib/initZod";
import { z } from "zod";
export declare const coreEnvBaseSchema: z.ZodObject<{
    NEXTAUTH_SECRET: z.ZodString;
    PREVIEW_TOKEN_SECRET: z.ZodOptional<z.ZodString>;
    UPGRADE_PREVIEW_TOKEN_SECRET: z.ZodOptional<z.ZodString>;
    NODE_ENV: z.ZodOptional<z.ZodEnum<["development", "test", "production"]>>;
    OUTPUT_EXPORT: z.ZodOptional<z.ZodBoolean>;
    NEXT_PUBLIC_PHASE: z.ZodOptional<z.ZodString>;
    NEXT_PUBLIC_DEFAULT_SHOP: z.ZodOptional<z.ZodString>;
    NEXT_PUBLIC_SHOP_ID: z.ZodOptional<z.ZodString>;
    SHOP_CODE: z.ZodOptional<z.ZodString>;
    CART_COOKIE_SECRET: z.ZodString;
    CART_TTL: z.ZodOptional<z.ZodNumber>;
    CMS_SPACE_URL: z.ZodOptional<z.ZodString>;
    CMS_ACCESS_TOKEN: z.ZodOptional<z.ZodString>;
    CHROMATIC_PROJECT_TOKEN: z.ZodOptional<z.ZodString>;
    GMAIL_USER: z.ZodOptional<z.ZodString>;
    GMAIL_PASS: z.ZodOptional<z.ZodString>;
    GA_API_SECRET: z.ZodOptional<z.ZodString>;
    SMTP_URL: z.ZodOptional<z.ZodString>;
    CAMPAIGN_FROM: z.ZodOptional<z.ZodString>;
    EMAIL_PROVIDER: z.ZodOptional<z.ZodEnum<["sendgrid", "resend", "smtp"]>>;
    SENDGRID_API_KEY: z.ZodOptional<z.ZodString>;
    SENDGRID_MARKETING_KEY: z.ZodOptional<z.ZodString>;
    RESEND_API_KEY: z.ZodOptional<z.ZodString>;
    EMAIL_BATCH_SIZE: z.ZodOptional<z.ZodNumber>;
    EMAIL_BATCH_DELAY_MS: z.ZodOptional<z.ZodNumber>;
    DATABASE_URL: z.ZodOptional<z.ZodString>;
    SANITY_API_VERSION: z.ZodOptional<z.ZodString>;
    CLOUDFLARE_ACCOUNT_ID: z.ZodOptional<z.ZodString>;
    CLOUDFLARE_API_TOKEN: z.ZodOptional<z.ZodString>;
    LUXURY_FEATURES_RA_TICKETING: z.ZodOptional<z.ZodBoolean>;
    LUXURY_FEATURES_FRAUD_REVIEW_THRESHOLD: z.ZodOptional<z.ZodNumber>;
    LUXURY_FEATURES_REQUIRE_STRONG_CUSTOMER_AUTH: z.ZodOptional<z.ZodBoolean>;
    LUXURY_FEATURES_TRACKING_DASHBOARD: z.ZodOptional<z.ZodBoolean>;
    LUXURY_FEATURES_RETURNS: z.ZodOptional<z.ZodBoolean>;
    DEPOSIT_RELEASE_ENABLED: z.ZodOptional<z.ZodEffects<z.ZodEffects<z.ZodString, "true" | "false", string>, boolean, string>>;
    DEPOSIT_RELEASE_INTERVAL_MS: z.ZodOptional<z.ZodEffects<z.ZodEffects<z.ZodString, string, string>, number, string>>;
    REVERSE_LOGISTICS_ENABLED: z.ZodOptional<z.ZodEffects<z.ZodEffects<z.ZodString, "true" | "false", string>, boolean, string>>;
    REVERSE_LOGISTICS_INTERVAL_MS: z.ZodOptional<z.ZodEffects<z.ZodEffects<z.ZodString, string, string>, number, string>>;
    LATE_FEE_ENABLED: z.ZodOptional<z.ZodEffects<z.ZodEffects<z.ZodString, "true" | "false", string>, boolean, string>>;
    LATE_FEE_INTERVAL_MS: z.ZodOptional<z.ZodEffects<z.ZodEffects<z.ZodString, string, string>, number, string>>;
    OPENAI_API_KEY: z.ZodOptional<z.ZodString>;
    SESSION_SECRET: z.ZodString;
    COOKIE_DOMAIN: z.ZodOptional<z.ZodString>;
    LOGIN_RATE_LIMIT_REDIS_URL: z.ZodOptional<z.ZodString>;
    LOGIN_RATE_LIMIT_REDIS_TOKEN: z.ZodOptional<z.ZodString>;
    NEXT_PUBLIC_BASE_URL: z.ZodOptional<z.ZodString>;
    STOCK_ALERT_RECIPIENTS: z.ZodOptional<z.ZodString>;
    STOCK_ALERT_WEBHOOK: z.ZodOptional<z.ZodString>;
    STOCK_ALERT_DEFAULT_THRESHOLD: z.ZodOptional<z.ZodNumber>;
    STOCK_ALERT_RECIPIENT: z.ZodOptional<z.ZodString>;
    SESSION_STORE: z.ZodOptional<z.ZodEnum<["memory", "redis"]>>;
    UPSTASH_REDIS_REST_URL: z.ZodOptional<z.ZodString>;
    UPSTASH_REDIS_REST_TOKEN: z.ZodOptional<z.ZodString>;
}, "passthrough", z.ZodTypeAny, z.objectOutputType<{
    NEXTAUTH_SECRET: z.ZodString;
    PREVIEW_TOKEN_SECRET: z.ZodOptional<z.ZodString>;
    UPGRADE_PREVIEW_TOKEN_SECRET: z.ZodOptional<z.ZodString>;
    NODE_ENV: z.ZodOptional<z.ZodEnum<["development", "test", "production"]>>;
    OUTPUT_EXPORT: z.ZodOptional<z.ZodBoolean>;
    NEXT_PUBLIC_PHASE: z.ZodOptional<z.ZodString>;
    NEXT_PUBLIC_DEFAULT_SHOP: z.ZodOptional<z.ZodString>;
    NEXT_PUBLIC_SHOP_ID: z.ZodOptional<z.ZodString>;
    SHOP_CODE: z.ZodOptional<z.ZodString>;
    CART_COOKIE_SECRET: z.ZodString;
    CART_TTL: z.ZodOptional<z.ZodNumber>;
    CMS_SPACE_URL: z.ZodOptional<z.ZodString>;
    CMS_ACCESS_TOKEN: z.ZodOptional<z.ZodString>;
    CHROMATIC_PROJECT_TOKEN: z.ZodOptional<z.ZodString>;
    GMAIL_USER: z.ZodOptional<z.ZodString>;
    GMAIL_PASS: z.ZodOptional<z.ZodString>;
    GA_API_SECRET: z.ZodOptional<z.ZodString>;
    SMTP_URL: z.ZodOptional<z.ZodString>;
    CAMPAIGN_FROM: z.ZodOptional<z.ZodString>;
    EMAIL_PROVIDER: z.ZodOptional<z.ZodEnum<["sendgrid", "resend", "smtp"]>>;
    SENDGRID_API_KEY: z.ZodOptional<z.ZodString>;
    SENDGRID_MARKETING_KEY: z.ZodOptional<z.ZodString>;
    RESEND_API_KEY: z.ZodOptional<z.ZodString>;
    EMAIL_BATCH_SIZE: z.ZodOptional<z.ZodNumber>;
    EMAIL_BATCH_DELAY_MS: z.ZodOptional<z.ZodNumber>;
    DATABASE_URL: z.ZodOptional<z.ZodString>;
    SANITY_API_VERSION: z.ZodOptional<z.ZodString>;
    CLOUDFLARE_ACCOUNT_ID: z.ZodOptional<z.ZodString>;
    CLOUDFLARE_API_TOKEN: z.ZodOptional<z.ZodString>;
    LUXURY_FEATURES_RA_TICKETING: z.ZodOptional<z.ZodBoolean>;
    LUXURY_FEATURES_FRAUD_REVIEW_THRESHOLD: z.ZodOptional<z.ZodNumber>;
    LUXURY_FEATURES_REQUIRE_STRONG_CUSTOMER_AUTH: z.ZodOptional<z.ZodBoolean>;
    LUXURY_FEATURES_TRACKING_DASHBOARD: z.ZodOptional<z.ZodBoolean>;
    LUXURY_FEATURES_RETURNS: z.ZodOptional<z.ZodBoolean>;
    DEPOSIT_RELEASE_ENABLED: z.ZodOptional<z.ZodEffects<z.ZodEffects<z.ZodString, "true" | "false", string>, boolean, string>>;
    DEPOSIT_RELEASE_INTERVAL_MS: z.ZodOptional<z.ZodEffects<z.ZodEffects<z.ZodString, string, string>, number, string>>;
    REVERSE_LOGISTICS_ENABLED: z.ZodOptional<z.ZodEffects<z.ZodEffects<z.ZodString, "true" | "false", string>, boolean, string>>;
    REVERSE_LOGISTICS_INTERVAL_MS: z.ZodOptional<z.ZodEffects<z.ZodEffects<z.ZodString, string, string>, number, string>>;
    LATE_FEE_ENABLED: z.ZodOptional<z.ZodEffects<z.ZodEffects<z.ZodString, "true" | "false", string>, boolean, string>>;
    LATE_FEE_INTERVAL_MS: z.ZodOptional<z.ZodEffects<z.ZodEffects<z.ZodString, string, string>, number, string>>;
    OPENAI_API_KEY: z.ZodOptional<z.ZodString>;
    SESSION_SECRET: z.ZodString;
    COOKIE_DOMAIN: z.ZodOptional<z.ZodString>;
    LOGIN_RATE_LIMIT_REDIS_URL: z.ZodOptional<z.ZodString>;
    LOGIN_RATE_LIMIT_REDIS_TOKEN: z.ZodOptional<z.ZodString>;
    NEXT_PUBLIC_BASE_URL: z.ZodOptional<z.ZodString>;
    STOCK_ALERT_RECIPIENTS: z.ZodOptional<z.ZodString>;
    STOCK_ALERT_WEBHOOK: z.ZodOptional<z.ZodString>;
    STOCK_ALERT_DEFAULT_THRESHOLD: z.ZodOptional<z.ZodNumber>;
    STOCK_ALERT_RECIPIENT: z.ZodOptional<z.ZodString>;
    SESSION_STORE: z.ZodOptional<z.ZodEnum<["memory", "redis"]>>;
    UPSTASH_REDIS_REST_URL: z.ZodOptional<z.ZodString>;
    UPSTASH_REDIS_REST_TOKEN: z.ZodOptional<z.ZodString>;
}, z.ZodTypeAny, "passthrough">, z.objectInputType<{
    NEXTAUTH_SECRET: z.ZodString;
    PREVIEW_TOKEN_SECRET: z.ZodOptional<z.ZodString>;
    UPGRADE_PREVIEW_TOKEN_SECRET: z.ZodOptional<z.ZodString>;
    NODE_ENV: z.ZodOptional<z.ZodEnum<["development", "test", "production"]>>;
    OUTPUT_EXPORT: z.ZodOptional<z.ZodBoolean>;
    NEXT_PUBLIC_PHASE: z.ZodOptional<z.ZodString>;
    NEXT_PUBLIC_DEFAULT_SHOP: z.ZodOptional<z.ZodString>;
    NEXT_PUBLIC_SHOP_ID: z.ZodOptional<z.ZodString>;
    SHOP_CODE: z.ZodOptional<z.ZodString>;
    CART_COOKIE_SECRET: z.ZodString;
    CART_TTL: z.ZodOptional<z.ZodNumber>;
    CMS_SPACE_URL: z.ZodOptional<z.ZodString>;
    CMS_ACCESS_TOKEN: z.ZodOptional<z.ZodString>;
    CHROMATIC_PROJECT_TOKEN: z.ZodOptional<z.ZodString>;
    GMAIL_USER: z.ZodOptional<z.ZodString>;
    GMAIL_PASS: z.ZodOptional<z.ZodString>;
    GA_API_SECRET: z.ZodOptional<z.ZodString>;
    SMTP_URL: z.ZodOptional<z.ZodString>;
    CAMPAIGN_FROM: z.ZodOptional<z.ZodString>;
    EMAIL_PROVIDER: z.ZodOptional<z.ZodEnum<["sendgrid", "resend", "smtp"]>>;
    SENDGRID_API_KEY: z.ZodOptional<z.ZodString>;
    SENDGRID_MARKETING_KEY: z.ZodOptional<z.ZodString>;
    RESEND_API_KEY: z.ZodOptional<z.ZodString>;
    EMAIL_BATCH_SIZE: z.ZodOptional<z.ZodNumber>;
    EMAIL_BATCH_DELAY_MS: z.ZodOptional<z.ZodNumber>;
    DATABASE_URL: z.ZodOptional<z.ZodString>;
    SANITY_API_VERSION: z.ZodOptional<z.ZodString>;
    CLOUDFLARE_ACCOUNT_ID: z.ZodOptional<z.ZodString>;
    CLOUDFLARE_API_TOKEN: z.ZodOptional<z.ZodString>;
    LUXURY_FEATURES_RA_TICKETING: z.ZodOptional<z.ZodBoolean>;
    LUXURY_FEATURES_FRAUD_REVIEW_THRESHOLD: z.ZodOptional<z.ZodNumber>;
    LUXURY_FEATURES_REQUIRE_STRONG_CUSTOMER_AUTH: z.ZodOptional<z.ZodBoolean>;
    LUXURY_FEATURES_TRACKING_DASHBOARD: z.ZodOptional<z.ZodBoolean>;
    LUXURY_FEATURES_RETURNS: z.ZodOptional<z.ZodBoolean>;
    DEPOSIT_RELEASE_ENABLED: z.ZodOptional<z.ZodEffects<z.ZodEffects<z.ZodString, "true" | "false", string>, boolean, string>>;
    DEPOSIT_RELEASE_INTERVAL_MS: z.ZodOptional<z.ZodEffects<z.ZodEffects<z.ZodString, string, string>, number, string>>;
    REVERSE_LOGISTICS_ENABLED: z.ZodOptional<z.ZodEffects<z.ZodEffects<z.ZodString, "true" | "false", string>, boolean, string>>;
    REVERSE_LOGISTICS_INTERVAL_MS: z.ZodOptional<z.ZodEffects<z.ZodEffects<z.ZodString, string, string>, number, string>>;
    LATE_FEE_ENABLED: z.ZodOptional<z.ZodEffects<z.ZodEffects<z.ZodString, "true" | "false", string>, boolean, string>>;
    LATE_FEE_INTERVAL_MS: z.ZodOptional<z.ZodEffects<z.ZodEffects<z.ZodString, string, string>, number, string>>;
    OPENAI_API_KEY: z.ZodOptional<z.ZodString>;
    SESSION_SECRET: z.ZodString;
    COOKIE_DOMAIN: z.ZodOptional<z.ZodString>;
    LOGIN_RATE_LIMIT_REDIS_URL: z.ZodOptional<z.ZodString>;
    LOGIN_RATE_LIMIT_REDIS_TOKEN: z.ZodOptional<z.ZodString>;
    NEXT_PUBLIC_BASE_URL: z.ZodOptional<z.ZodString>;
    STOCK_ALERT_RECIPIENTS: z.ZodOptional<z.ZodString>;
    STOCK_ALERT_WEBHOOK: z.ZodOptional<z.ZodString>;
    STOCK_ALERT_DEFAULT_THRESHOLD: z.ZodOptional<z.ZodNumber>;
    STOCK_ALERT_RECIPIENT: z.ZodOptional<z.ZodString>;
    SESSION_STORE: z.ZodOptional<z.ZodEnum<["memory", "redis"]>>;
    UPSTASH_REDIS_REST_URL: z.ZodOptional<z.ZodString>;
    UPSTASH_REDIS_REST_TOKEN: z.ZodOptional<z.ZodString>;
}, z.ZodTypeAny, "passthrough">>;
export declare function depositReleaseEnvRefinement(env: Record<string, unknown>, ctx: z.RefinementCtx): void;
export declare const coreEnvSchema: z.ZodEffects<z.ZodObject<{
    NEXTAUTH_SECRET: z.ZodString;
    PREVIEW_TOKEN_SECRET: z.ZodOptional<z.ZodString>;
    UPGRADE_PREVIEW_TOKEN_SECRET: z.ZodOptional<z.ZodString>;
    NODE_ENV: z.ZodOptional<z.ZodEnum<["development", "test", "production"]>>;
    OUTPUT_EXPORT: z.ZodOptional<z.ZodBoolean>;
    NEXT_PUBLIC_PHASE: z.ZodOptional<z.ZodString>;
    NEXT_PUBLIC_DEFAULT_SHOP: z.ZodOptional<z.ZodString>;
    NEXT_PUBLIC_SHOP_ID: z.ZodOptional<z.ZodString>;
    SHOP_CODE: z.ZodOptional<z.ZodString>;
    CART_COOKIE_SECRET: z.ZodString;
    CART_TTL: z.ZodOptional<z.ZodNumber>;
    CMS_SPACE_URL: z.ZodOptional<z.ZodString>;
    CMS_ACCESS_TOKEN: z.ZodOptional<z.ZodString>;
    CHROMATIC_PROJECT_TOKEN: z.ZodOptional<z.ZodString>;
    GMAIL_USER: z.ZodOptional<z.ZodString>;
    GMAIL_PASS: z.ZodOptional<z.ZodString>;
    GA_API_SECRET: z.ZodOptional<z.ZodString>;
    SMTP_URL: z.ZodOptional<z.ZodString>;
    CAMPAIGN_FROM: z.ZodOptional<z.ZodString>;
    EMAIL_PROVIDER: z.ZodOptional<z.ZodEnum<["sendgrid", "resend", "smtp"]>>;
    SENDGRID_API_KEY: z.ZodOptional<z.ZodString>;
    SENDGRID_MARKETING_KEY: z.ZodOptional<z.ZodString>;
    RESEND_API_KEY: z.ZodOptional<z.ZodString>;
    EMAIL_BATCH_SIZE: z.ZodOptional<z.ZodNumber>;
    EMAIL_BATCH_DELAY_MS: z.ZodOptional<z.ZodNumber>;
    DATABASE_URL: z.ZodOptional<z.ZodString>;
    SANITY_API_VERSION: z.ZodOptional<z.ZodString>;
    CLOUDFLARE_ACCOUNT_ID: z.ZodOptional<z.ZodString>;
    CLOUDFLARE_API_TOKEN: z.ZodOptional<z.ZodString>;
    LUXURY_FEATURES_RA_TICKETING: z.ZodOptional<z.ZodBoolean>;
    LUXURY_FEATURES_FRAUD_REVIEW_THRESHOLD: z.ZodOptional<z.ZodNumber>;
    LUXURY_FEATURES_REQUIRE_STRONG_CUSTOMER_AUTH: z.ZodOptional<z.ZodBoolean>;
    LUXURY_FEATURES_TRACKING_DASHBOARD: z.ZodOptional<z.ZodBoolean>;
    LUXURY_FEATURES_RETURNS: z.ZodOptional<z.ZodBoolean>;
    DEPOSIT_RELEASE_ENABLED: z.ZodOptional<z.ZodEffects<z.ZodEffects<z.ZodString, "true" | "false", string>, boolean, string>>;
    DEPOSIT_RELEASE_INTERVAL_MS: z.ZodOptional<z.ZodEffects<z.ZodEffects<z.ZodString, string, string>, number, string>>;
    REVERSE_LOGISTICS_ENABLED: z.ZodOptional<z.ZodEffects<z.ZodEffects<z.ZodString, "true" | "false", string>, boolean, string>>;
    REVERSE_LOGISTICS_INTERVAL_MS: z.ZodOptional<z.ZodEffects<z.ZodEffects<z.ZodString, string, string>, number, string>>;
    LATE_FEE_ENABLED: z.ZodOptional<z.ZodEffects<z.ZodEffects<z.ZodString, "true" | "false", string>, boolean, string>>;
    LATE_FEE_INTERVAL_MS: z.ZodOptional<z.ZodEffects<z.ZodEffects<z.ZodString, string, string>, number, string>>;
    OPENAI_API_KEY: z.ZodOptional<z.ZodString>;
    SESSION_SECRET: z.ZodString;
    COOKIE_DOMAIN: z.ZodOptional<z.ZodString>;
    LOGIN_RATE_LIMIT_REDIS_URL: z.ZodOptional<z.ZodString>;
    LOGIN_RATE_LIMIT_REDIS_TOKEN: z.ZodOptional<z.ZodString>;
    NEXT_PUBLIC_BASE_URL: z.ZodOptional<z.ZodString>;
    STOCK_ALERT_RECIPIENTS: z.ZodOptional<z.ZodString>;
    STOCK_ALERT_WEBHOOK: z.ZodOptional<z.ZodString>;
    STOCK_ALERT_DEFAULT_THRESHOLD: z.ZodOptional<z.ZodNumber>;
    STOCK_ALERT_RECIPIENT: z.ZodOptional<z.ZodString>;
    SESSION_STORE: z.ZodOptional<z.ZodEnum<["memory", "redis"]>>;
    UPSTASH_REDIS_REST_URL: z.ZodOptional<z.ZodString>;
    UPSTASH_REDIS_REST_TOKEN: z.ZodOptional<z.ZodString>;
}, "passthrough", z.ZodTypeAny, z.objectOutputType<{
    NEXTAUTH_SECRET: z.ZodString;
    PREVIEW_TOKEN_SECRET: z.ZodOptional<z.ZodString>;
    UPGRADE_PREVIEW_TOKEN_SECRET: z.ZodOptional<z.ZodString>;
    NODE_ENV: z.ZodOptional<z.ZodEnum<["development", "test", "production"]>>;
    OUTPUT_EXPORT: z.ZodOptional<z.ZodBoolean>;
    NEXT_PUBLIC_PHASE: z.ZodOptional<z.ZodString>;
    NEXT_PUBLIC_DEFAULT_SHOP: z.ZodOptional<z.ZodString>;
    NEXT_PUBLIC_SHOP_ID: z.ZodOptional<z.ZodString>;
    SHOP_CODE: z.ZodOptional<z.ZodString>;
    CART_COOKIE_SECRET: z.ZodString;
    CART_TTL: z.ZodOptional<z.ZodNumber>;
    CMS_SPACE_URL: z.ZodOptional<z.ZodString>;
    CMS_ACCESS_TOKEN: z.ZodOptional<z.ZodString>;
    CHROMATIC_PROJECT_TOKEN: z.ZodOptional<z.ZodString>;
    GMAIL_USER: z.ZodOptional<z.ZodString>;
    GMAIL_PASS: z.ZodOptional<z.ZodString>;
    GA_API_SECRET: z.ZodOptional<z.ZodString>;
    SMTP_URL: z.ZodOptional<z.ZodString>;
    CAMPAIGN_FROM: z.ZodOptional<z.ZodString>;
    EMAIL_PROVIDER: z.ZodOptional<z.ZodEnum<["sendgrid", "resend", "smtp"]>>;
    SENDGRID_API_KEY: z.ZodOptional<z.ZodString>;
    SENDGRID_MARKETING_KEY: z.ZodOptional<z.ZodString>;
    RESEND_API_KEY: z.ZodOptional<z.ZodString>;
    EMAIL_BATCH_SIZE: z.ZodOptional<z.ZodNumber>;
    EMAIL_BATCH_DELAY_MS: z.ZodOptional<z.ZodNumber>;
    DATABASE_URL: z.ZodOptional<z.ZodString>;
    SANITY_API_VERSION: z.ZodOptional<z.ZodString>;
    CLOUDFLARE_ACCOUNT_ID: z.ZodOptional<z.ZodString>;
    CLOUDFLARE_API_TOKEN: z.ZodOptional<z.ZodString>;
    LUXURY_FEATURES_RA_TICKETING: z.ZodOptional<z.ZodBoolean>;
    LUXURY_FEATURES_FRAUD_REVIEW_THRESHOLD: z.ZodOptional<z.ZodNumber>;
    LUXURY_FEATURES_REQUIRE_STRONG_CUSTOMER_AUTH: z.ZodOptional<z.ZodBoolean>;
    LUXURY_FEATURES_TRACKING_DASHBOARD: z.ZodOptional<z.ZodBoolean>;
    LUXURY_FEATURES_RETURNS: z.ZodOptional<z.ZodBoolean>;
    DEPOSIT_RELEASE_ENABLED: z.ZodOptional<z.ZodEffects<z.ZodEffects<z.ZodString, "true" | "false", string>, boolean, string>>;
    DEPOSIT_RELEASE_INTERVAL_MS: z.ZodOptional<z.ZodEffects<z.ZodEffects<z.ZodString, string, string>, number, string>>;
    REVERSE_LOGISTICS_ENABLED: z.ZodOptional<z.ZodEffects<z.ZodEffects<z.ZodString, "true" | "false", string>, boolean, string>>;
    REVERSE_LOGISTICS_INTERVAL_MS: z.ZodOptional<z.ZodEffects<z.ZodEffects<z.ZodString, string, string>, number, string>>;
    LATE_FEE_ENABLED: z.ZodOptional<z.ZodEffects<z.ZodEffects<z.ZodString, "true" | "false", string>, boolean, string>>;
    LATE_FEE_INTERVAL_MS: z.ZodOptional<z.ZodEffects<z.ZodEffects<z.ZodString, string, string>, number, string>>;
    OPENAI_API_KEY: z.ZodOptional<z.ZodString>;
    SESSION_SECRET: z.ZodString;
    COOKIE_DOMAIN: z.ZodOptional<z.ZodString>;
    LOGIN_RATE_LIMIT_REDIS_URL: z.ZodOptional<z.ZodString>;
    LOGIN_RATE_LIMIT_REDIS_TOKEN: z.ZodOptional<z.ZodString>;
    NEXT_PUBLIC_BASE_URL: z.ZodOptional<z.ZodString>;
    STOCK_ALERT_RECIPIENTS: z.ZodOptional<z.ZodString>;
    STOCK_ALERT_WEBHOOK: z.ZodOptional<z.ZodString>;
    STOCK_ALERT_DEFAULT_THRESHOLD: z.ZodOptional<z.ZodNumber>;
    STOCK_ALERT_RECIPIENT: z.ZodOptional<z.ZodString>;
    SESSION_STORE: z.ZodOptional<z.ZodEnum<["memory", "redis"]>>;
    UPSTASH_REDIS_REST_URL: z.ZodOptional<z.ZodString>;
    UPSTASH_REDIS_REST_TOKEN: z.ZodOptional<z.ZodString>;
}, z.ZodTypeAny, "passthrough">, z.objectInputType<{
    NEXTAUTH_SECRET: z.ZodString;
    PREVIEW_TOKEN_SECRET: z.ZodOptional<z.ZodString>;
    UPGRADE_PREVIEW_TOKEN_SECRET: z.ZodOptional<z.ZodString>;
    NODE_ENV: z.ZodOptional<z.ZodEnum<["development", "test", "production"]>>;
    OUTPUT_EXPORT: z.ZodOptional<z.ZodBoolean>;
    NEXT_PUBLIC_PHASE: z.ZodOptional<z.ZodString>;
    NEXT_PUBLIC_DEFAULT_SHOP: z.ZodOptional<z.ZodString>;
    NEXT_PUBLIC_SHOP_ID: z.ZodOptional<z.ZodString>;
    SHOP_CODE: z.ZodOptional<z.ZodString>;
    CART_COOKIE_SECRET: z.ZodString;
    CART_TTL: z.ZodOptional<z.ZodNumber>;
    CMS_SPACE_URL: z.ZodOptional<z.ZodString>;
    CMS_ACCESS_TOKEN: z.ZodOptional<z.ZodString>;
    CHROMATIC_PROJECT_TOKEN: z.ZodOptional<z.ZodString>;
    GMAIL_USER: z.ZodOptional<z.ZodString>;
    GMAIL_PASS: z.ZodOptional<z.ZodString>;
    GA_API_SECRET: z.ZodOptional<z.ZodString>;
    SMTP_URL: z.ZodOptional<z.ZodString>;
    CAMPAIGN_FROM: z.ZodOptional<z.ZodString>;
    EMAIL_PROVIDER: z.ZodOptional<z.ZodEnum<["sendgrid", "resend", "smtp"]>>;
    SENDGRID_API_KEY: z.ZodOptional<z.ZodString>;
    SENDGRID_MARKETING_KEY: z.ZodOptional<z.ZodString>;
    RESEND_API_KEY: z.ZodOptional<z.ZodString>;
    EMAIL_BATCH_SIZE: z.ZodOptional<z.ZodNumber>;
    EMAIL_BATCH_DELAY_MS: z.ZodOptional<z.ZodNumber>;
    DATABASE_URL: z.ZodOptional<z.ZodString>;
    SANITY_API_VERSION: z.ZodOptional<z.ZodString>;
    CLOUDFLARE_ACCOUNT_ID: z.ZodOptional<z.ZodString>;
    CLOUDFLARE_API_TOKEN: z.ZodOptional<z.ZodString>;
    LUXURY_FEATURES_RA_TICKETING: z.ZodOptional<z.ZodBoolean>;
    LUXURY_FEATURES_FRAUD_REVIEW_THRESHOLD: z.ZodOptional<z.ZodNumber>;
    LUXURY_FEATURES_REQUIRE_STRONG_CUSTOMER_AUTH: z.ZodOptional<z.ZodBoolean>;
    LUXURY_FEATURES_TRACKING_DASHBOARD: z.ZodOptional<z.ZodBoolean>;
    LUXURY_FEATURES_RETURNS: z.ZodOptional<z.ZodBoolean>;
    DEPOSIT_RELEASE_ENABLED: z.ZodOptional<z.ZodEffects<z.ZodEffects<z.ZodString, "true" | "false", string>, boolean, string>>;
    DEPOSIT_RELEASE_INTERVAL_MS: z.ZodOptional<z.ZodEffects<z.ZodEffects<z.ZodString, string, string>, number, string>>;
    REVERSE_LOGISTICS_ENABLED: z.ZodOptional<z.ZodEffects<z.ZodEffects<z.ZodString, "true" | "false", string>, boolean, string>>;
    REVERSE_LOGISTICS_INTERVAL_MS: z.ZodOptional<z.ZodEffects<z.ZodEffects<z.ZodString, string, string>, number, string>>;
    LATE_FEE_ENABLED: z.ZodOptional<z.ZodEffects<z.ZodEffects<z.ZodString, "true" | "false", string>, boolean, string>>;
    LATE_FEE_INTERVAL_MS: z.ZodOptional<z.ZodEffects<z.ZodEffects<z.ZodString, string, string>, number, string>>;
    OPENAI_API_KEY: z.ZodOptional<z.ZodString>;
    SESSION_SECRET: z.ZodString;
    COOKIE_DOMAIN: z.ZodOptional<z.ZodString>;
    LOGIN_RATE_LIMIT_REDIS_URL: z.ZodOptional<z.ZodString>;
    LOGIN_RATE_LIMIT_REDIS_TOKEN: z.ZodOptional<z.ZodString>;
    NEXT_PUBLIC_BASE_URL: z.ZodOptional<z.ZodString>;
    STOCK_ALERT_RECIPIENTS: z.ZodOptional<z.ZodString>;
    STOCK_ALERT_WEBHOOK: z.ZodOptional<z.ZodString>;
    STOCK_ALERT_DEFAULT_THRESHOLD: z.ZodOptional<z.ZodNumber>;
    STOCK_ALERT_RECIPIENT: z.ZodOptional<z.ZodString>;
    SESSION_STORE: z.ZodOptional<z.ZodEnum<["memory", "redis"]>>;
    UPSTASH_REDIS_REST_URL: z.ZodOptional<z.ZodString>;
    UPSTASH_REDIS_REST_TOKEN: z.ZodOptional<z.ZodString>;
}, z.ZodTypeAny, "passthrough">>, z.objectOutputType<{
    NEXTAUTH_SECRET: z.ZodString;
    PREVIEW_TOKEN_SECRET: z.ZodOptional<z.ZodString>;
    UPGRADE_PREVIEW_TOKEN_SECRET: z.ZodOptional<z.ZodString>;
    NODE_ENV: z.ZodOptional<z.ZodEnum<["development", "test", "production"]>>;
    OUTPUT_EXPORT: z.ZodOptional<z.ZodBoolean>;
    NEXT_PUBLIC_PHASE: z.ZodOptional<z.ZodString>;
    NEXT_PUBLIC_DEFAULT_SHOP: z.ZodOptional<z.ZodString>;
    NEXT_PUBLIC_SHOP_ID: z.ZodOptional<z.ZodString>;
    SHOP_CODE: z.ZodOptional<z.ZodString>;
    CART_COOKIE_SECRET: z.ZodString;
    CART_TTL: z.ZodOptional<z.ZodNumber>;
    CMS_SPACE_URL: z.ZodOptional<z.ZodString>;
    CMS_ACCESS_TOKEN: z.ZodOptional<z.ZodString>;
    CHROMATIC_PROJECT_TOKEN: z.ZodOptional<z.ZodString>;
    GMAIL_USER: z.ZodOptional<z.ZodString>;
    GMAIL_PASS: z.ZodOptional<z.ZodString>;
    GA_API_SECRET: z.ZodOptional<z.ZodString>;
    SMTP_URL: z.ZodOptional<z.ZodString>;
    CAMPAIGN_FROM: z.ZodOptional<z.ZodString>;
    EMAIL_PROVIDER: z.ZodOptional<z.ZodEnum<["sendgrid", "resend", "smtp"]>>;
    SENDGRID_API_KEY: z.ZodOptional<z.ZodString>;
    SENDGRID_MARKETING_KEY: z.ZodOptional<z.ZodString>;
    RESEND_API_KEY: z.ZodOptional<z.ZodString>;
    EMAIL_BATCH_SIZE: z.ZodOptional<z.ZodNumber>;
    EMAIL_BATCH_DELAY_MS: z.ZodOptional<z.ZodNumber>;
    DATABASE_URL: z.ZodOptional<z.ZodString>;
    SANITY_API_VERSION: z.ZodOptional<z.ZodString>;
    CLOUDFLARE_ACCOUNT_ID: z.ZodOptional<z.ZodString>;
    CLOUDFLARE_API_TOKEN: z.ZodOptional<z.ZodString>;
    LUXURY_FEATURES_RA_TICKETING: z.ZodOptional<z.ZodBoolean>;
    LUXURY_FEATURES_FRAUD_REVIEW_THRESHOLD: z.ZodOptional<z.ZodNumber>;
    LUXURY_FEATURES_REQUIRE_STRONG_CUSTOMER_AUTH: z.ZodOptional<z.ZodBoolean>;
    LUXURY_FEATURES_TRACKING_DASHBOARD: z.ZodOptional<z.ZodBoolean>;
    LUXURY_FEATURES_RETURNS: z.ZodOptional<z.ZodBoolean>;
    DEPOSIT_RELEASE_ENABLED: z.ZodOptional<z.ZodEffects<z.ZodEffects<z.ZodString, "true" | "false", string>, boolean, string>>;
    DEPOSIT_RELEASE_INTERVAL_MS: z.ZodOptional<z.ZodEffects<z.ZodEffects<z.ZodString, string, string>, number, string>>;
    REVERSE_LOGISTICS_ENABLED: z.ZodOptional<z.ZodEffects<z.ZodEffects<z.ZodString, "true" | "false", string>, boolean, string>>;
    REVERSE_LOGISTICS_INTERVAL_MS: z.ZodOptional<z.ZodEffects<z.ZodEffects<z.ZodString, string, string>, number, string>>;
    LATE_FEE_ENABLED: z.ZodOptional<z.ZodEffects<z.ZodEffects<z.ZodString, "true" | "false", string>, boolean, string>>;
    LATE_FEE_INTERVAL_MS: z.ZodOptional<z.ZodEffects<z.ZodEffects<z.ZodString, string, string>, number, string>>;
    OPENAI_API_KEY: z.ZodOptional<z.ZodString>;
    SESSION_SECRET: z.ZodString;
    COOKIE_DOMAIN: z.ZodOptional<z.ZodString>;
    LOGIN_RATE_LIMIT_REDIS_URL: z.ZodOptional<z.ZodString>;
    LOGIN_RATE_LIMIT_REDIS_TOKEN: z.ZodOptional<z.ZodString>;
    NEXT_PUBLIC_BASE_URL: z.ZodOptional<z.ZodString>;
    STOCK_ALERT_RECIPIENTS: z.ZodOptional<z.ZodString>;
    STOCK_ALERT_WEBHOOK: z.ZodOptional<z.ZodString>;
    STOCK_ALERT_DEFAULT_THRESHOLD: z.ZodOptional<z.ZodNumber>;
    STOCK_ALERT_RECIPIENT: z.ZodOptional<z.ZodString>;
    SESSION_STORE: z.ZodOptional<z.ZodEnum<["memory", "redis"]>>;
    UPSTASH_REDIS_REST_URL: z.ZodOptional<z.ZodString>;
    UPSTASH_REDIS_REST_TOKEN: z.ZodOptional<z.ZodString>;
}, z.ZodTypeAny, "passthrough">, z.objectInputType<{
    NEXTAUTH_SECRET: z.ZodString;
    PREVIEW_TOKEN_SECRET: z.ZodOptional<z.ZodString>;
    UPGRADE_PREVIEW_TOKEN_SECRET: z.ZodOptional<z.ZodString>;
    NODE_ENV: z.ZodOptional<z.ZodEnum<["development", "test", "production"]>>;
    OUTPUT_EXPORT: z.ZodOptional<z.ZodBoolean>;
    NEXT_PUBLIC_PHASE: z.ZodOptional<z.ZodString>;
    NEXT_PUBLIC_DEFAULT_SHOP: z.ZodOptional<z.ZodString>;
    NEXT_PUBLIC_SHOP_ID: z.ZodOptional<z.ZodString>;
    SHOP_CODE: z.ZodOptional<z.ZodString>;
    CART_COOKIE_SECRET: z.ZodString;
    CART_TTL: z.ZodOptional<z.ZodNumber>;
    CMS_SPACE_URL: z.ZodOptional<z.ZodString>;
    CMS_ACCESS_TOKEN: z.ZodOptional<z.ZodString>;
    CHROMATIC_PROJECT_TOKEN: z.ZodOptional<z.ZodString>;
    GMAIL_USER: z.ZodOptional<z.ZodString>;
    GMAIL_PASS: z.ZodOptional<z.ZodString>;
    GA_API_SECRET: z.ZodOptional<z.ZodString>;
    SMTP_URL: z.ZodOptional<z.ZodString>;
    CAMPAIGN_FROM: z.ZodOptional<z.ZodString>;
    EMAIL_PROVIDER: z.ZodOptional<z.ZodEnum<["sendgrid", "resend", "smtp"]>>;
    SENDGRID_API_KEY: z.ZodOptional<z.ZodString>;
    SENDGRID_MARKETING_KEY: z.ZodOptional<z.ZodString>;
    RESEND_API_KEY: z.ZodOptional<z.ZodString>;
    EMAIL_BATCH_SIZE: z.ZodOptional<z.ZodNumber>;
    EMAIL_BATCH_DELAY_MS: z.ZodOptional<z.ZodNumber>;
    DATABASE_URL: z.ZodOptional<z.ZodString>;
    SANITY_API_VERSION: z.ZodOptional<z.ZodString>;
    CLOUDFLARE_ACCOUNT_ID: z.ZodOptional<z.ZodString>;
    CLOUDFLARE_API_TOKEN: z.ZodOptional<z.ZodString>;
    LUXURY_FEATURES_RA_TICKETING: z.ZodOptional<z.ZodBoolean>;
    LUXURY_FEATURES_FRAUD_REVIEW_THRESHOLD: z.ZodOptional<z.ZodNumber>;
    LUXURY_FEATURES_REQUIRE_STRONG_CUSTOMER_AUTH: z.ZodOptional<z.ZodBoolean>;
    LUXURY_FEATURES_TRACKING_DASHBOARD: z.ZodOptional<z.ZodBoolean>;
    LUXURY_FEATURES_RETURNS: z.ZodOptional<z.ZodBoolean>;
    DEPOSIT_RELEASE_ENABLED: z.ZodOptional<z.ZodEffects<z.ZodEffects<z.ZodString, "true" | "false", string>, boolean, string>>;
    DEPOSIT_RELEASE_INTERVAL_MS: z.ZodOptional<z.ZodEffects<z.ZodEffects<z.ZodString, string, string>, number, string>>;
    REVERSE_LOGISTICS_ENABLED: z.ZodOptional<z.ZodEffects<z.ZodEffects<z.ZodString, "true" | "false", string>, boolean, string>>;
    REVERSE_LOGISTICS_INTERVAL_MS: z.ZodOptional<z.ZodEffects<z.ZodEffects<z.ZodString, string, string>, number, string>>;
    LATE_FEE_ENABLED: z.ZodOptional<z.ZodEffects<z.ZodEffects<z.ZodString, "true" | "false", string>, boolean, string>>;
    LATE_FEE_INTERVAL_MS: z.ZodOptional<z.ZodEffects<z.ZodEffects<z.ZodString, string, string>, number, string>>;
    OPENAI_API_KEY: z.ZodOptional<z.ZodString>;
    SESSION_SECRET: z.ZodString;
    COOKIE_DOMAIN: z.ZodOptional<z.ZodString>;
    LOGIN_RATE_LIMIT_REDIS_URL: z.ZodOptional<z.ZodString>;
    LOGIN_RATE_LIMIT_REDIS_TOKEN: z.ZodOptional<z.ZodString>;
    NEXT_PUBLIC_BASE_URL: z.ZodOptional<z.ZodString>;
    STOCK_ALERT_RECIPIENTS: z.ZodOptional<z.ZodString>;
    STOCK_ALERT_WEBHOOK: z.ZodOptional<z.ZodString>;
    STOCK_ALERT_DEFAULT_THRESHOLD: z.ZodOptional<z.ZodNumber>;
    STOCK_ALERT_RECIPIENT: z.ZodOptional<z.ZodString>;
    SESSION_STORE: z.ZodOptional<z.ZodEnum<["memory", "redis"]>>;
    UPSTASH_REDIS_REST_URL: z.ZodOptional<z.ZodString>;
    UPSTASH_REDIS_REST_TOKEN: z.ZodOptional<z.ZodString>;
}, z.ZodTypeAny, "passthrough">>;
export declare const coreEnv: z.objectOutputType<{
    NEXTAUTH_SECRET: z.ZodString;
    PREVIEW_TOKEN_SECRET: z.ZodOptional<z.ZodString>;
    UPGRADE_PREVIEW_TOKEN_SECRET: z.ZodOptional<z.ZodString>;
    NODE_ENV: z.ZodOptional<z.ZodEnum<["development", "test", "production"]>>;
    OUTPUT_EXPORT: z.ZodOptional<z.ZodBoolean>;
    NEXT_PUBLIC_PHASE: z.ZodOptional<z.ZodString>;
    NEXT_PUBLIC_DEFAULT_SHOP: z.ZodOptional<z.ZodString>;
    NEXT_PUBLIC_SHOP_ID: z.ZodOptional<z.ZodString>;
    SHOP_CODE: z.ZodOptional<z.ZodString>;
    CART_COOKIE_SECRET: z.ZodString;
    CART_TTL: z.ZodOptional<z.ZodNumber>;
    CMS_SPACE_URL: z.ZodOptional<z.ZodString>;
    CMS_ACCESS_TOKEN: z.ZodOptional<z.ZodString>;
    CHROMATIC_PROJECT_TOKEN: z.ZodOptional<z.ZodString>;
    GMAIL_USER: z.ZodOptional<z.ZodString>;
    GMAIL_PASS: z.ZodOptional<z.ZodString>;
    GA_API_SECRET: z.ZodOptional<z.ZodString>;
    SMTP_URL: z.ZodOptional<z.ZodString>;
    CAMPAIGN_FROM: z.ZodOptional<z.ZodString>;
    EMAIL_PROVIDER: z.ZodOptional<z.ZodEnum<["sendgrid", "resend", "smtp"]>>;
    SENDGRID_API_KEY: z.ZodOptional<z.ZodString>;
    SENDGRID_MARKETING_KEY: z.ZodOptional<z.ZodString>;
    RESEND_API_KEY: z.ZodOptional<z.ZodString>;
    EMAIL_BATCH_SIZE: z.ZodOptional<z.ZodNumber>;
    EMAIL_BATCH_DELAY_MS: z.ZodOptional<z.ZodNumber>;
    DATABASE_URL: z.ZodOptional<z.ZodString>;
    SANITY_API_VERSION: z.ZodOptional<z.ZodString>;
    CLOUDFLARE_ACCOUNT_ID: z.ZodOptional<z.ZodString>;
    CLOUDFLARE_API_TOKEN: z.ZodOptional<z.ZodString>;
    LUXURY_FEATURES_RA_TICKETING: z.ZodOptional<z.ZodBoolean>;
    LUXURY_FEATURES_FRAUD_REVIEW_THRESHOLD: z.ZodOptional<z.ZodNumber>;
    LUXURY_FEATURES_REQUIRE_STRONG_CUSTOMER_AUTH: z.ZodOptional<z.ZodBoolean>;
    LUXURY_FEATURES_TRACKING_DASHBOARD: z.ZodOptional<z.ZodBoolean>;
    LUXURY_FEATURES_RETURNS: z.ZodOptional<z.ZodBoolean>;
    DEPOSIT_RELEASE_ENABLED: z.ZodOptional<z.ZodEffects<z.ZodEffects<z.ZodString, "true" | "false", string>, boolean, string>>;
    DEPOSIT_RELEASE_INTERVAL_MS: z.ZodOptional<z.ZodEffects<z.ZodEffects<z.ZodString, string, string>, number, string>>;
    REVERSE_LOGISTICS_ENABLED: z.ZodOptional<z.ZodEffects<z.ZodEffects<z.ZodString, "true" | "false", string>, boolean, string>>;
    REVERSE_LOGISTICS_INTERVAL_MS: z.ZodOptional<z.ZodEffects<z.ZodEffects<z.ZodString, string, string>, number, string>>;
    LATE_FEE_ENABLED: z.ZodOptional<z.ZodEffects<z.ZodEffects<z.ZodString, "true" | "false", string>, boolean, string>>;
    LATE_FEE_INTERVAL_MS: z.ZodOptional<z.ZodEffects<z.ZodEffects<z.ZodString, string, string>, number, string>>;
    OPENAI_API_KEY: z.ZodOptional<z.ZodString>;
    SESSION_SECRET: z.ZodString;
    COOKIE_DOMAIN: z.ZodOptional<z.ZodString>;
    LOGIN_RATE_LIMIT_REDIS_URL: z.ZodOptional<z.ZodString>;
    LOGIN_RATE_LIMIT_REDIS_TOKEN: z.ZodOptional<z.ZodString>;
    NEXT_PUBLIC_BASE_URL: z.ZodOptional<z.ZodString>;
    STOCK_ALERT_RECIPIENTS: z.ZodOptional<z.ZodString>;
    STOCK_ALERT_WEBHOOK: z.ZodOptional<z.ZodString>;
    STOCK_ALERT_DEFAULT_THRESHOLD: z.ZodOptional<z.ZodNumber>;
    STOCK_ALERT_RECIPIENT: z.ZodOptional<z.ZodString>;
    SESSION_STORE: z.ZodOptional<z.ZodEnum<["memory", "redis"]>>;
    UPSTASH_REDIS_REST_URL: z.ZodOptional<z.ZodString>;
    UPSTASH_REDIS_REST_TOKEN: z.ZodOptional<z.ZodString>;
}, z.ZodTypeAny, "passthrough">;
export type CoreEnv = z.infer<typeof coreEnvSchema>;
//# sourceMappingURL=core.d.ts.map