import "@acme/zod-utils/initZod";
import { z } from "zod";
export declare const emailEnvSchema: z.ZodEffects<z.ZodObject<{
    EMAIL_FROM: z.ZodOptional<z.ZodEffects<z.ZodString, string, string>>;
    EMAIL_SENDER_NAME: z.ZodOptional<z.ZodString>;
    GMAIL_USER: z.ZodOptional<z.ZodString>;
    GMAIL_PASS: z.ZodOptional<z.ZodString>;
    SMTP_URL: z.ZodOptional<z.ZodString>;
    SMTP_PORT: z.ZodOptional<z.ZodEffects<z.ZodEffects<z.ZodString, string, string>, number, string>>;
    SMTP_SECURE: z.ZodOptional<z.ZodEffects<z.ZodEffects<z.ZodEffects<z.ZodString, string, string>, string, string>, boolean, string>>;
    CAMPAIGN_FROM: z.ZodOptional<z.ZodEffects<z.ZodString, string, string>>;
    EMAIL_PROVIDER: z.ZodDefault<z.ZodEnum<["sendgrid", "resend", "smtp", "noop"]>>;
    SENDGRID_API_KEY: z.ZodOptional<z.ZodString>;
    SENDGRID_MARKETING_KEY: z.ZodOptional<z.ZodString>;
    RESEND_API_KEY: z.ZodOptional<z.ZodString>;
    EMAIL_BATCH_SIZE: z.ZodOptional<z.ZodNumber>;
    EMAIL_BATCH_DELAY_MS: z.ZodOptional<z.ZodNumber>;
}, "strip", z.ZodTypeAny, {
    EMAIL_PROVIDER: "sendgrid" | "resend" | "smtp" | "noop";
    EMAIL_FROM?: string | undefined;
    EMAIL_SENDER_NAME?: string | undefined;
    GMAIL_USER?: string | undefined;
    GMAIL_PASS?: string | undefined;
    SMTP_URL?: string | undefined;
    SMTP_PORT?: number | undefined;
    SMTP_SECURE?: boolean | undefined;
    CAMPAIGN_FROM?: string | undefined;
    SENDGRID_API_KEY?: string | undefined;
    SENDGRID_MARKETING_KEY?: string | undefined;
    RESEND_API_KEY?: string | undefined;
    EMAIL_BATCH_SIZE?: number | undefined;
    EMAIL_BATCH_DELAY_MS?: number | undefined;
}, {
    EMAIL_FROM?: string | undefined;
    EMAIL_SENDER_NAME?: string | undefined;
    GMAIL_USER?: string | undefined;
    GMAIL_PASS?: string | undefined;
    SMTP_URL?: string | undefined;
    SMTP_PORT?: string | undefined;
    SMTP_SECURE?: string | undefined;
    CAMPAIGN_FROM?: string | undefined;
    EMAIL_PROVIDER?: "sendgrid" | "resend" | "smtp" | "noop" | undefined;
    SENDGRID_API_KEY?: string | undefined;
    SENDGRID_MARKETING_KEY?: string | undefined;
    RESEND_API_KEY?: string | undefined;
    EMAIL_BATCH_SIZE?: number | undefined;
    EMAIL_BATCH_DELAY_MS?: number | undefined;
}>, {
    EMAIL_PROVIDER: "sendgrid" | "resend" | "smtp" | "noop";
    EMAIL_FROM?: string | undefined;
    EMAIL_SENDER_NAME?: string | undefined;
    GMAIL_USER?: string | undefined;
    GMAIL_PASS?: string | undefined;
    SMTP_URL?: string | undefined;
    SMTP_PORT?: number | undefined;
    SMTP_SECURE?: boolean | undefined;
    CAMPAIGN_FROM?: string | undefined;
    SENDGRID_API_KEY?: string | undefined;
    SENDGRID_MARKETING_KEY?: string | undefined;
    RESEND_API_KEY?: string | undefined;
    EMAIL_BATCH_SIZE?: number | undefined;
    EMAIL_BATCH_DELAY_MS?: number | undefined;
}, {
    EMAIL_FROM?: string | undefined;
    EMAIL_SENDER_NAME?: string | undefined;
    GMAIL_USER?: string | undefined;
    GMAIL_PASS?: string | undefined;
    SMTP_URL?: string | undefined;
    SMTP_PORT?: string | undefined;
    SMTP_SECURE?: string | undefined;
    CAMPAIGN_FROM?: string | undefined;
    EMAIL_PROVIDER?: "sendgrid" | "resend" | "smtp" | "noop" | undefined;
    SENDGRID_API_KEY?: string | undefined;
    SENDGRID_MARKETING_KEY?: string | undefined;
    RESEND_API_KEY?: string | undefined;
    EMAIL_BATCH_SIZE?: number | undefined;
    EMAIL_BATCH_DELAY_MS?: number | undefined;
}>;
export type EmailEnv = z.infer<typeof emailEnvSchema>;
