import "@acme/zod-utils/initZod";
import { z } from "zod";
type UnionToIntersection<U> = (U extends any ? (k: U) => void : never) extends (k: infer I) => void ? I : never;
type AnyZodObject = z.ZodObject<z.ZodRawShape, any, any, any, any>;
type MergedShape<T extends readonly AnyZodObject[]> = UnionToIntersection<{
    [K in keyof T]: T[K] extends z.ZodObject<infer S extends z.ZodRawShape, any, any, any, any> ? S : never;
}[number]> & z.ZodRawShape;
export declare const mergeEnvSchemas: <T extends readonly AnyZodObject[]>(...schemas: T) => z.ZodObject<MergedShape<T>>;
export declare const envSchema: z.ZodEffects<z.ZodObject<MergedShape<[z.ZodObject<{
    NEXTAUTH_SECRET: z.ZodString;
    PREVIEW_TOKEN_SECRET: z.ZodOptional<z.ZodString>;
    UPGRADE_PREVIEW_TOKEN_SECRET: z.ZodOptional<z.ZodString>;
    NODE_ENV: z.ZodOptional<z.ZodEnum<["development", "test", "production"]>>;
    OUTPUT_EXPORT: z.ZodOptional<z.ZodBoolean>;
    NEXT_PUBLIC_PHASE: z.ZodOptional<z.ZodString>;
    NEXT_PUBLIC_DEFAULT_SHOP: z.ZodOptional<z.ZodString>;
    NEXT_PUBLIC_SHOP_ID: z.ZodOptional<z.ZodString>;
    SHOP_CODE: z.ZodOptional<z.ZodString>;
    CART_COOKIE_SECRET: z.ZodString;
    CART_TTL: z.ZodOptional<z.ZodNumber>;
    CMS_SPACE_URL: z.ZodOptional<z.ZodString>;
    CMS_ACCESS_TOKEN: z.ZodOptional<z.ZodString>;
    CHROMATIC_PROJECT_TOKEN: z.ZodOptional<z.ZodString>;
    GMAIL_USER: z.ZodOptional<z.ZodString>;
    GMAIL_PASS: z.ZodOptional<z.ZodString>;
    GA_API_SECRET: z.ZodOptional<z.ZodString>;
    SMTP_URL: z.ZodOptional<z.ZodString>;
    CAMPAIGN_FROM: z.ZodOptional<z.ZodString>;
    EMAIL_PROVIDER: z.ZodOptional<z.ZodEnum<["sendgrid", "resend", "smtp"]>>;
    SENDGRID_API_KEY: z.ZodOptional<z.ZodString>;
    SENDGRID_MARKETING_KEY: z.ZodOptional<z.ZodString>;
    RESEND_API_KEY: z.ZodOptional<z.ZodString>;
    EMAIL_BATCH_SIZE: z.ZodOptional<z.ZodNumber>;
    EMAIL_BATCH_DELAY_MS: z.ZodOptional<z.ZodNumber>;
    DATABASE_URL: z.ZodOptional<z.ZodString>;
    SANITY_API_VERSION: z.ZodOptional<z.ZodString>;
    CLOUDFLARE_ACCOUNT_ID: z.ZodOptional<z.ZodString>;
    CLOUDFLARE_API_TOKEN: z.ZodOptional<z.ZodString>;
    LUXURY_FEATURES_RA_TICKETING: z.ZodOptional<z.ZodBoolean>;
    LUXURY_FEATURES_FRAUD_REVIEW_THRESHOLD: z.ZodOptional<z.ZodNumber>;
    LUXURY_FEATURES_REQUIRE_STRONG_CUSTOMER_AUTH: z.ZodOptional<z.ZodBoolean>;
    LUXURY_FEATURES_TRACKING_DASHBOARD: z.ZodOptional<z.ZodBoolean>;
    LUXURY_FEATURES_RETURNS: z.ZodOptional<z.ZodBoolean>;
    DEPOSIT_RELEASE_ENABLED: z.ZodOptional<z.ZodEffects<z.ZodEffects<z.ZodString, "true" | "false", string>, boolean, string>>;
    DEPOSIT_RELEASE_INTERVAL_MS: z.ZodOptional<z.ZodEffects<z.ZodEffects<z.ZodString, string, string>, number, string>>;
    REVERSE_LOGISTICS_ENABLED: z.ZodOptional<z.ZodEffects<z.ZodEffects<z.ZodString, "true" | "false", string>, boolean, string>>;
    REVERSE_LOGISTICS_INTERVAL_MS: z.ZodOptional<z.ZodEffects<z.ZodEffects<z.ZodString, string, string>, number, string>>;
    LATE_FEE_ENABLED: z.ZodOptional<z.ZodEffects<z.ZodEffects<z.ZodString, "true" | "false", string>, boolean, string>>;
    LATE_FEE_INTERVAL_MS: z.ZodOptional<z.ZodEffects<z.ZodEffects<z.ZodString, string, string>, number, string>>;
    OPENAI_API_KEY: z.ZodOptional<z.ZodString>;
    SESSION_SECRET: z.ZodString;
    COOKIE_DOMAIN: z.ZodOptional<z.ZodString>;
    LOGIN_RATE_LIMIT_REDIS_URL: z.ZodOptional<z.ZodString>;
    LOGIN_RATE_LIMIT_REDIS_TOKEN: z.ZodOptional<z.ZodString>;
    NEXT_PUBLIC_BASE_URL: z.ZodOptional<z.ZodString>;
    STOCK_ALERT_RECIPIENTS: z.ZodOptional<z.ZodString>;
    STOCK_ALERT_WEBHOOK: z.ZodOptional<z.ZodString>;
    STOCK_ALERT_DEFAULT_THRESHOLD: z.ZodOptional<z.ZodNumber>;
    STOCK_ALERT_RECIPIENT: z.ZodOptional<z.ZodString>;
    SESSION_STORE: z.ZodOptional<z.ZodEnum<["memory", "redis"]>>;
    UPSTASH_REDIS_REST_URL: z.ZodOptional<z.ZodString>;
    UPSTASH_REDIS_REST_TOKEN: z.ZodOptional<z.ZodString>;
}, "passthrough", z.ZodTypeAny, z.objectOutputType<{
    NEXTAUTH_SECRET: z.ZodString;
    PREVIEW_TOKEN_SECRET: z.ZodOptional<z.ZodString>;
    UPGRADE_PREVIEW_TOKEN_SECRET: z.ZodOptional<z.ZodString>;
    NODE_ENV: z.ZodOptional<z.ZodEnum<["development", "test", "production"]>>;
    OUTPUT_EXPORT: z.ZodOptional<z.ZodBoolean>;
    NEXT_PUBLIC_PHASE: z.ZodOptional<z.ZodString>;
    NEXT_PUBLIC_DEFAULT_SHOP: z.ZodOptional<z.ZodString>;
    NEXT_PUBLIC_SHOP_ID: z.ZodOptional<z.ZodString>;
    SHOP_CODE: z.ZodOptional<z.ZodString>;
    CART_COOKIE_SECRET: z.ZodString;
    CART_TTL: z.ZodOptional<z.ZodNumber>;
    CMS_SPACE_URL: z.ZodOptional<z.ZodString>;
    CMS_ACCESS_TOKEN: z.ZodOptional<z.ZodString>;
    CHROMATIC_PROJECT_TOKEN: z.ZodOptional<z.ZodString>;
    GMAIL_USER: z.ZodOptional<z.ZodString>;
    GMAIL_PASS: z.ZodOptional<z.ZodString>;
    GA_API_SECRET: z.ZodOptional<z.ZodString>;
    SMTP_URL: z.ZodOptional<z.ZodString>;
    CAMPAIGN_FROM: z.ZodOptional<z.ZodString>;
    EMAIL_PROVIDER: z.ZodOptional<z.ZodEnum<["sendgrid", "resend", "smtp"]>>;
    SENDGRID_API_KEY: z.ZodOptional<z.ZodString>;
    SENDGRID_MARKETING_KEY: z.ZodOptional<z.ZodString>;
    RESEND_API_KEY: z.ZodOptional<z.ZodString>;
    EMAIL_BATCH_SIZE: z.ZodOptional<z.ZodNumber>;
    EMAIL_BATCH_DELAY_MS: z.ZodOptional<z.ZodNumber>;
    DATABASE_URL: z.ZodOptional<z.ZodString>;
    SANITY_API_VERSION: z.ZodOptional<z.ZodString>;
    CLOUDFLARE_ACCOUNT_ID: z.ZodOptional<z.ZodString>;
    CLOUDFLARE_API_TOKEN: z.ZodOptional<z.ZodString>;
    LUXURY_FEATURES_RA_TICKETING: z.ZodOptional<z.ZodBoolean>;
    LUXURY_FEATURES_FRAUD_REVIEW_THRESHOLD: z.ZodOptional<z.ZodNumber>;
    LUXURY_FEATURES_REQUIRE_STRONG_CUSTOMER_AUTH: z.ZodOptional<z.ZodBoolean>;
    LUXURY_FEATURES_TRACKING_DASHBOARD: z.ZodOptional<z.ZodBoolean>;
    LUXURY_FEATURES_RETURNS: z.ZodOptional<z.ZodBoolean>;
    DEPOSIT_RELEASE_ENABLED: z.ZodOptional<z.ZodEffects<z.ZodEffects<z.ZodString, "true" | "false", string>, boolean, string>>;
    DEPOSIT_RELEASE_INTERVAL_MS: z.ZodOptional<z.ZodEffects<z.ZodEffects<z.ZodString, string, string>, number, string>>;
    REVERSE_LOGISTICS_ENABLED: z.ZodOptional<z.ZodEffects<z.ZodEffects<z.ZodString, "true" | "false", string>, boolean, string>>;
    REVERSE_LOGISTICS_INTERVAL_MS: z.ZodOptional<z.ZodEffects<z.ZodEffects<z.ZodString, string, string>, number, string>>;
    LATE_FEE_ENABLED: z.ZodOptional<z.ZodEffects<z.ZodEffects<z.ZodString, "true" | "false", string>, boolean, string>>;
    LATE_FEE_INTERVAL_MS: z.ZodOptional<z.ZodEffects<z.ZodEffects<z.ZodString, string, string>, number, string>>;
    OPENAI_API_KEY: z.ZodOptional<z.ZodString>;
    SESSION_SECRET: z.ZodString;
    COOKIE_DOMAIN: z.ZodOptional<z.ZodString>;
    LOGIN_RATE_LIMIT_REDIS_URL: z.ZodOptional<z.ZodString>;
    LOGIN_RATE_LIMIT_REDIS_TOKEN: z.ZodOptional<z.ZodString>;
    NEXT_PUBLIC_BASE_URL: z.ZodOptional<z.ZodString>;
    STOCK_ALERT_RECIPIENTS: z.ZodOptional<z.ZodString>;
    STOCK_ALERT_WEBHOOK: z.ZodOptional<z.ZodString>;
    STOCK_ALERT_DEFAULT_THRESHOLD: z.ZodOptional<z.ZodNumber>;
    STOCK_ALERT_RECIPIENT: z.ZodOptional<z.ZodString>;
    SESSION_STORE: z.ZodOptional<z.ZodEnum<["memory", "redis"]>>;
    UPSTASH_REDIS_REST_URL: z.ZodOptional<z.ZodString>;
    UPSTASH_REDIS_REST_TOKEN: z.ZodOptional<z.ZodString>;
}, z.ZodTypeAny, "passthrough">, z.objectInputType<{
    NEXTAUTH_SECRET: z.ZodString;
    PREVIEW_TOKEN_SECRET: z.ZodOptional<z.ZodString>;
    UPGRADE_PREVIEW_TOKEN_SECRET: z.ZodOptional<z.ZodString>;
    NODE_ENV: z.ZodOptional<z.ZodEnum<["development", "test", "production"]>>;
    OUTPUT_EXPORT: z.ZodOptional<z.ZodBoolean>;
    NEXT_PUBLIC_PHASE: z.ZodOptional<z.ZodString>;
    NEXT_PUBLIC_DEFAULT_SHOP: z.ZodOptional<z.ZodString>;
    NEXT_PUBLIC_SHOP_ID: z.ZodOptional<z.ZodString>;
    SHOP_CODE: z.ZodOptional<z.ZodString>;
    CART_COOKIE_SECRET: z.ZodString;
    CART_TTL: z.ZodOptional<z.ZodNumber>;
    CMS_SPACE_URL: z.ZodOptional<z.ZodString>;
    CMS_ACCESS_TOKEN: z.ZodOptional<z.ZodString>;
    CHROMATIC_PROJECT_TOKEN: z.ZodOptional<z.ZodString>;
    GMAIL_USER: z.ZodOptional<z.ZodString>;
    GMAIL_PASS: z.ZodOptional<z.ZodString>;
    GA_API_SECRET: z.ZodOptional<z.ZodString>;
    SMTP_URL: z.ZodOptional<z.ZodString>;
    CAMPAIGN_FROM: z.ZodOptional<z.ZodString>;
    EMAIL_PROVIDER: z.ZodOptional<z.ZodEnum<["sendgrid", "resend", "smtp"]>>;
    SENDGRID_API_KEY: z.ZodOptional<z.ZodString>;
    SENDGRID_MARKETING_KEY: z.ZodOptional<z.ZodString>;
    RESEND_API_KEY: z.ZodOptional<z.ZodString>;
    EMAIL_BATCH_SIZE: z.ZodOptional<z.ZodNumber>;
    EMAIL_BATCH_DELAY_MS: z.ZodOptional<z.ZodNumber>;
    DATABASE_URL: z.ZodOptional<z.ZodString>;
    SANITY_API_VERSION: z.ZodOptional<z.ZodString>;
    CLOUDFLARE_ACCOUNT_ID: z.ZodOptional<z.ZodString>;
    CLOUDFLARE_API_TOKEN: z.ZodOptional<z.ZodString>;
    LUXURY_FEATURES_RA_TICKETING: z.ZodOptional<z.ZodBoolean>;
    LUXURY_FEATURES_FRAUD_REVIEW_THRESHOLD: z.ZodOptional<z.ZodNumber>;
    LUXURY_FEATURES_REQUIRE_STRONG_CUSTOMER_AUTH: z.ZodOptional<z.ZodBoolean>;
    LUXURY_FEATURES_TRACKING_DASHBOARD: z.ZodOptional<z.ZodBoolean>;
    LUXURY_FEATURES_RETURNS: z.ZodOptional<z.ZodBoolean>;
    DEPOSIT_RELEASE_ENABLED: z.ZodOptional<z.ZodEffects<z.ZodEffects<z.ZodString, "true" | "false", string>, boolean, string>>;
    DEPOSIT_RELEASE_INTERVAL_MS: z.ZodOptional<z.ZodEffects<z.ZodEffects<z.ZodString, string, string>, number, string>>;
    REVERSE_LOGISTICS_ENABLED: z.ZodOptional<z.ZodEffects<z.ZodEffects<z.ZodString, "true" | "false", string>, boolean, string>>;
    REVERSE_LOGISTICS_INTERVAL_MS: z.ZodOptional<z.ZodEffects<z.ZodEffects<z.ZodString, string, string>, number, string>>;
    LATE_FEE_ENABLED: z.ZodOptional<z.ZodEffects<z.ZodEffects<z.ZodString, "true" | "false", string>, boolean, string>>;
    LATE_FEE_INTERVAL_MS: z.ZodOptional<z.ZodEffects<z.ZodEffects<z.ZodString, string, string>, number, string>>;
    OPENAI_API_KEY: z.ZodOptional<z.ZodString>;
    SESSION_SECRET: z.ZodString;
    COOKIE_DOMAIN: z.ZodOptional<z.ZodString>;
    LOGIN_RATE_LIMIT_REDIS_URL: z.ZodOptional<z.ZodString>;
    LOGIN_RATE_LIMIT_REDIS_TOKEN: z.ZodOptional<z.ZodString>;
    NEXT_PUBLIC_BASE_URL: z.ZodOptional<z.ZodString>;
    STOCK_ALERT_RECIPIENTS: z.ZodOptional<z.ZodString>;
    STOCK_ALERT_WEBHOOK: z.ZodOptional<z.ZodString>;
    STOCK_ALERT_DEFAULT_THRESHOLD: z.ZodOptional<z.ZodNumber>;
    STOCK_ALERT_RECIPIENT: z.ZodOptional<z.ZodString>;
    SESSION_STORE: z.ZodOptional<z.ZodEnum<["memory", "redis"]>>;
    UPSTASH_REDIS_REST_URL: z.ZodOptional<z.ZodString>;
    UPSTASH_REDIS_REST_TOKEN: z.ZodOptional<z.ZodString>;
}, z.ZodTypeAny, "passthrough">>, z.ZodObject<{
    STRIPE_SECRET_KEY: z.ZodString;
    NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY: z.ZodString;
    STRIPE_WEBHOOK_SECRET: z.ZodString;
}, "strip", z.ZodTypeAny, {
    STRIPE_SECRET_KEY: string;
    NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY: string;
    STRIPE_WEBHOOK_SECRET: string;
}, {
    STRIPE_SECRET_KEY: string;
    NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY: string;
    STRIPE_WEBHOOK_SECRET: string;
}>, z.ZodObject<{
    TAXJAR_KEY: z.ZodOptional<z.ZodString>;
    UPS_KEY: z.ZodOptional<z.ZodString>;
    DHL_KEY: z.ZodOptional<z.ZodString>;
}, "strip", z.ZodTypeAny, {
    TAXJAR_KEY?: string | undefined;
    UPS_KEY?: string | undefined;
    DHL_KEY?: string | undefined;
}, {
    TAXJAR_KEY?: string | undefined;
    UPS_KEY?: string | undefined;
    DHL_KEY?: string | undefined;
}>]>, z.UnknownKeysParam, z.ZodTypeAny, {
    [x: string]: any;
    NEXTAUTH_SECRET?: unknown;
    PREVIEW_TOKEN_SECRET?: unknown;
    UPGRADE_PREVIEW_TOKEN_SECRET?: unknown;
    NODE_ENV?: unknown;
    OUTPUT_EXPORT?: unknown;
    NEXT_PUBLIC_PHASE?: unknown;
    NEXT_PUBLIC_DEFAULT_SHOP?: unknown;
    NEXT_PUBLIC_SHOP_ID?: unknown;
    SHOP_CODE?: unknown;
    CART_COOKIE_SECRET?: unknown;
    CART_TTL?: unknown;
    CMS_SPACE_URL?: unknown;
    CMS_ACCESS_TOKEN?: unknown;
    CHROMATIC_PROJECT_TOKEN?: unknown;
    GMAIL_USER?: unknown;
    GMAIL_PASS?: unknown;
    GA_API_SECRET?: unknown;
    SMTP_URL?: unknown;
    CAMPAIGN_FROM?: unknown;
    EMAIL_PROVIDER?: unknown;
    SENDGRID_API_KEY?: unknown;
    SENDGRID_MARKETING_KEY?: unknown;
    RESEND_API_KEY?: unknown;
    EMAIL_BATCH_SIZE?: unknown;
    EMAIL_BATCH_DELAY_MS?: unknown;
    DATABASE_URL?: unknown;
    SANITY_API_VERSION?: unknown;
    CLOUDFLARE_ACCOUNT_ID?: unknown;
    CLOUDFLARE_API_TOKEN?: unknown;
    LUXURY_FEATURES_RA_TICKETING?: unknown;
    LUXURY_FEATURES_FRAUD_REVIEW_THRESHOLD?: unknown;
    LUXURY_FEATURES_REQUIRE_STRONG_CUSTOMER_AUTH?: unknown;
    LUXURY_FEATURES_TRACKING_DASHBOARD?: unknown;
    LUXURY_FEATURES_RETURNS?: unknown;
    DEPOSIT_RELEASE_ENABLED?: unknown;
    DEPOSIT_RELEASE_INTERVAL_MS?: unknown;
    REVERSE_LOGISTICS_ENABLED?: unknown;
    REVERSE_LOGISTICS_INTERVAL_MS?: unknown;
    LATE_FEE_ENABLED?: unknown;
    LATE_FEE_INTERVAL_MS?: unknown;
    OPENAI_API_KEY?: unknown;
    SESSION_SECRET?: unknown;
    COOKIE_DOMAIN?: unknown;
    LOGIN_RATE_LIMIT_REDIS_URL?: unknown;
    LOGIN_RATE_LIMIT_REDIS_TOKEN?: unknown;
    NEXT_PUBLIC_BASE_URL?: unknown;
    STOCK_ALERT_RECIPIENTS?: unknown;
    STOCK_ALERT_WEBHOOK?: unknown;
    STOCK_ALERT_DEFAULT_THRESHOLD?: unknown;
    STOCK_ALERT_RECIPIENT?: unknown;
    SESSION_STORE?: unknown;
    UPSTASH_REDIS_REST_URL?: unknown;
    UPSTASH_REDIS_REST_TOKEN?: unknown;
    STRIPE_SECRET_KEY?: unknown;
    NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY?: unknown;
    STRIPE_WEBHOOK_SECRET?: unknown;
    TAXJAR_KEY?: unknown;
    UPS_KEY?: unknown;
    DHL_KEY?: unknown;
}, {
    [x: string]: any;
    NEXTAUTH_SECRET?: unknown;
    PREVIEW_TOKEN_SECRET?: unknown;
    UPGRADE_PREVIEW_TOKEN_SECRET?: unknown;
    NODE_ENV?: unknown;
    OUTPUT_EXPORT?: unknown;
    NEXT_PUBLIC_PHASE?: unknown;
    NEXT_PUBLIC_DEFAULT_SHOP?: unknown;
    NEXT_PUBLIC_SHOP_ID?: unknown;
    SHOP_CODE?: unknown;
    CART_COOKIE_SECRET?: unknown;
    CART_TTL?: unknown;
    CMS_SPACE_URL?: unknown;
    CMS_ACCESS_TOKEN?: unknown;
    CHROMATIC_PROJECT_TOKEN?: unknown;
    GMAIL_USER?: unknown;
    GMAIL_PASS?: unknown;
    GA_API_SECRET?: unknown;
    SMTP_URL?: unknown;
    CAMPAIGN_FROM?: unknown;
    EMAIL_PROVIDER?: unknown;
    SENDGRID_API_KEY?: unknown;
    SENDGRID_MARKETING_KEY?: unknown;
    RESEND_API_KEY?: unknown;
    EMAIL_BATCH_SIZE?: unknown;
    EMAIL_BATCH_DELAY_MS?: unknown;
    DATABASE_URL?: unknown;
    SANITY_API_VERSION?: unknown;
    CLOUDFLARE_ACCOUNT_ID?: unknown;
    CLOUDFLARE_API_TOKEN?: unknown;
    LUXURY_FEATURES_RA_TICKETING?: unknown;
    LUXURY_FEATURES_FRAUD_REVIEW_THRESHOLD?: unknown;
    LUXURY_FEATURES_REQUIRE_STRONG_CUSTOMER_AUTH?: unknown;
    LUXURY_FEATURES_TRACKING_DASHBOARD?: unknown;
    LUXURY_FEATURES_RETURNS?: unknown;
    DEPOSIT_RELEASE_ENABLED?: unknown;
    DEPOSIT_RELEASE_INTERVAL_MS?: unknown;
    REVERSE_LOGISTICS_ENABLED?: unknown;
    REVERSE_LOGISTICS_INTERVAL_MS?: unknown;
    LATE_FEE_ENABLED?: unknown;
    LATE_FEE_INTERVAL_MS?: unknown;
    OPENAI_API_KEY?: unknown;
    SESSION_SECRET?: unknown;
    COOKIE_DOMAIN?: unknown;
    LOGIN_RATE_LIMIT_REDIS_URL?: unknown;
    LOGIN_RATE_LIMIT_REDIS_TOKEN?: unknown;
    NEXT_PUBLIC_BASE_URL?: unknown;
    STOCK_ALERT_RECIPIENTS?: unknown;
    STOCK_ALERT_WEBHOOK?: unknown;
    STOCK_ALERT_DEFAULT_THRESHOLD?: unknown;
    STOCK_ALERT_RECIPIENT?: unknown;
    SESSION_STORE?: unknown;
    UPSTASH_REDIS_REST_URL?: unknown;
    UPSTASH_REDIS_REST_TOKEN?: unknown;
    STRIPE_SECRET_KEY?: unknown;
    NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY?: unknown;
    STRIPE_WEBHOOK_SECRET?: unknown;
    TAXJAR_KEY?: unknown;
    UPS_KEY?: unknown;
    DHL_KEY?: unknown;
}>, {
    [x: string]: any;
    NEXTAUTH_SECRET?: unknown;
    PREVIEW_TOKEN_SECRET?: unknown;
    UPGRADE_PREVIEW_TOKEN_SECRET?: unknown;
    NODE_ENV?: unknown;
    OUTPUT_EXPORT?: unknown;
    NEXT_PUBLIC_PHASE?: unknown;
    NEXT_PUBLIC_DEFAULT_SHOP?: unknown;
    NEXT_PUBLIC_SHOP_ID?: unknown;
    SHOP_CODE?: unknown;
    CART_COOKIE_SECRET?: unknown;
    CART_TTL?: unknown;
    CMS_SPACE_URL?: unknown;
    CMS_ACCESS_TOKEN?: unknown;
    CHROMATIC_PROJECT_TOKEN?: unknown;
    GMAIL_USER?: unknown;
    GMAIL_PASS?: unknown;
    GA_API_SECRET?: unknown;
    SMTP_URL?: unknown;
    CAMPAIGN_FROM?: unknown;
    EMAIL_PROVIDER?: unknown;
    SENDGRID_API_KEY?: unknown;
    SENDGRID_MARKETING_KEY?: unknown;
    RESEND_API_KEY?: unknown;
    EMAIL_BATCH_SIZE?: unknown;
    EMAIL_BATCH_DELAY_MS?: unknown;
    DATABASE_URL?: unknown;
    SANITY_API_VERSION?: unknown;
    CLOUDFLARE_ACCOUNT_ID?: unknown;
    CLOUDFLARE_API_TOKEN?: unknown;
    LUXURY_FEATURES_RA_TICKETING?: unknown;
    LUXURY_FEATURES_FRAUD_REVIEW_THRESHOLD?: unknown;
    LUXURY_FEATURES_REQUIRE_STRONG_CUSTOMER_AUTH?: unknown;
    LUXURY_FEATURES_TRACKING_DASHBOARD?: unknown;
    LUXURY_FEATURES_RETURNS?: unknown;
    DEPOSIT_RELEASE_ENABLED?: unknown;
    DEPOSIT_RELEASE_INTERVAL_MS?: unknown;
    REVERSE_LOGISTICS_ENABLED?: unknown;
    REVERSE_LOGISTICS_INTERVAL_MS?: unknown;
    LATE_FEE_ENABLED?: unknown;
    LATE_FEE_INTERVAL_MS?: unknown;
    OPENAI_API_KEY?: unknown;
    SESSION_SECRET?: unknown;
    COOKIE_DOMAIN?: unknown;
    LOGIN_RATE_LIMIT_REDIS_URL?: unknown;
    LOGIN_RATE_LIMIT_REDIS_TOKEN?: unknown;
    NEXT_PUBLIC_BASE_URL?: unknown;
    STOCK_ALERT_RECIPIENTS?: unknown;
    STOCK_ALERT_WEBHOOK?: unknown;
    STOCK_ALERT_DEFAULT_THRESHOLD?: unknown;
    STOCK_ALERT_RECIPIENT?: unknown;
    SESSION_STORE?: unknown;
    UPSTASH_REDIS_REST_URL?: unknown;
    UPSTASH_REDIS_REST_TOKEN?: unknown;
    STRIPE_SECRET_KEY?: unknown;
    NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY?: unknown;
    STRIPE_WEBHOOK_SECRET?: unknown;
    TAXJAR_KEY?: unknown;
    UPS_KEY?: unknown;
    DHL_KEY?: unknown;
}, {
    [x: string]: any;
    NEXTAUTH_SECRET?: unknown;
    PREVIEW_TOKEN_SECRET?: unknown;
    UPGRADE_PREVIEW_TOKEN_SECRET?: unknown;
    NODE_ENV?: unknown;
    OUTPUT_EXPORT?: unknown;
    NEXT_PUBLIC_PHASE?: unknown;
    NEXT_PUBLIC_DEFAULT_SHOP?: unknown;
    NEXT_PUBLIC_SHOP_ID?: unknown;
    SHOP_CODE?: unknown;
    CART_COOKIE_SECRET?: unknown;
    CART_TTL?: unknown;
    CMS_SPACE_URL?: unknown;
    CMS_ACCESS_TOKEN?: unknown;
    CHROMATIC_PROJECT_TOKEN?: unknown;
    GMAIL_USER?: unknown;
    GMAIL_PASS?: unknown;
    GA_API_SECRET?: unknown;
    SMTP_URL?: unknown;
    CAMPAIGN_FROM?: unknown;
    EMAIL_PROVIDER?: unknown;
    SENDGRID_API_KEY?: unknown;
    SENDGRID_MARKETING_KEY?: unknown;
    RESEND_API_KEY?: unknown;
    EMAIL_BATCH_SIZE?: unknown;
    EMAIL_BATCH_DELAY_MS?: unknown;
    DATABASE_URL?: unknown;
    SANITY_API_VERSION?: unknown;
    CLOUDFLARE_ACCOUNT_ID?: unknown;
    CLOUDFLARE_API_TOKEN?: unknown;
    LUXURY_FEATURES_RA_TICKETING?: unknown;
    LUXURY_FEATURES_FRAUD_REVIEW_THRESHOLD?: unknown;
    LUXURY_FEATURES_REQUIRE_STRONG_CUSTOMER_AUTH?: unknown;
    LUXURY_FEATURES_TRACKING_DASHBOARD?: unknown;
    LUXURY_FEATURES_RETURNS?: unknown;
    DEPOSIT_RELEASE_ENABLED?: unknown;
    DEPOSIT_RELEASE_INTERVAL_MS?: unknown;
    REVERSE_LOGISTICS_ENABLED?: unknown;
    REVERSE_LOGISTICS_INTERVAL_MS?: unknown;
    LATE_FEE_ENABLED?: unknown;
    LATE_FEE_INTERVAL_MS?: unknown;
    OPENAI_API_KEY?: unknown;
    SESSION_SECRET?: unknown;
    COOKIE_DOMAIN?: unknown;
    LOGIN_RATE_LIMIT_REDIS_URL?: unknown;
    LOGIN_RATE_LIMIT_REDIS_TOKEN?: unknown;
    NEXT_PUBLIC_BASE_URL?: unknown;
    STOCK_ALERT_RECIPIENTS?: unknown;
    STOCK_ALERT_WEBHOOK?: unknown;
    STOCK_ALERT_DEFAULT_THRESHOLD?: unknown;
    STOCK_ALERT_RECIPIENT?: unknown;
    SESSION_STORE?: unknown;
    UPSTASH_REDIS_REST_URL?: unknown;
    UPSTASH_REDIS_REST_TOKEN?: unknown;
    STRIPE_SECRET_KEY?: unknown;
    NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY?: unknown;
    STRIPE_WEBHOOK_SECRET?: unknown;
    TAXJAR_KEY?: unknown;
    UPS_KEY?: unknown;
    DHL_KEY?: unknown;
}>;
export declare const env: {
    [x: string]: any;
    NEXTAUTH_SECRET?: unknown;
    PREVIEW_TOKEN_SECRET?: unknown;
    UPGRADE_PREVIEW_TOKEN_SECRET?: unknown;
    NODE_ENV?: unknown;
    OUTPUT_EXPORT?: unknown;
    NEXT_PUBLIC_PHASE?: unknown;
    NEXT_PUBLIC_DEFAULT_SHOP?: unknown;
    NEXT_PUBLIC_SHOP_ID?: unknown;
    SHOP_CODE?: unknown;
    CART_COOKIE_SECRET?: unknown;
    CART_TTL?: unknown;
    CMS_SPACE_URL?: unknown;
    CMS_ACCESS_TOKEN?: unknown;
    CHROMATIC_PROJECT_TOKEN?: unknown;
    GMAIL_USER?: unknown;
    GMAIL_PASS?: unknown;
    GA_API_SECRET?: unknown;
    SMTP_URL?: unknown;
    CAMPAIGN_FROM?: unknown;
    EMAIL_PROVIDER?: unknown;
    SENDGRID_API_KEY?: unknown;
    SENDGRID_MARKETING_KEY?: unknown;
    RESEND_API_KEY?: unknown;
    EMAIL_BATCH_SIZE?: unknown;
    EMAIL_BATCH_DELAY_MS?: unknown;
    DATABASE_URL?: unknown;
    SANITY_API_VERSION?: unknown;
    CLOUDFLARE_ACCOUNT_ID?: unknown;
    CLOUDFLARE_API_TOKEN?: unknown;
    LUXURY_FEATURES_RA_TICKETING?: unknown;
    LUXURY_FEATURES_FRAUD_REVIEW_THRESHOLD?: unknown;
    LUXURY_FEATURES_REQUIRE_STRONG_CUSTOMER_AUTH?: unknown;
    LUXURY_FEATURES_TRACKING_DASHBOARD?: unknown;
    LUXURY_FEATURES_RETURNS?: unknown;
    DEPOSIT_RELEASE_ENABLED?: unknown;
    DEPOSIT_RELEASE_INTERVAL_MS?: unknown;
    REVERSE_LOGISTICS_ENABLED?: unknown;
    REVERSE_LOGISTICS_INTERVAL_MS?: unknown;
    LATE_FEE_ENABLED?: unknown;
    LATE_FEE_INTERVAL_MS?: unknown;
    OPENAI_API_KEY?: unknown;
    SESSION_SECRET?: unknown;
    COOKIE_DOMAIN?: unknown;
    LOGIN_RATE_LIMIT_REDIS_URL?: unknown;
    LOGIN_RATE_LIMIT_REDIS_TOKEN?: unknown;
    NEXT_PUBLIC_BASE_URL?: unknown;
    STOCK_ALERT_RECIPIENTS?: unknown;
    STOCK_ALERT_WEBHOOK?: unknown;
    STOCK_ALERT_DEFAULT_THRESHOLD?: unknown;
    STOCK_ALERT_RECIPIENT?: unknown;
    SESSION_STORE?: unknown;
    UPSTASH_REDIS_REST_URL?: unknown;
    UPSTASH_REDIS_REST_TOKEN?: unknown;
    STRIPE_SECRET_KEY?: unknown;
    NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY?: unknown;
    STRIPE_WEBHOOK_SECRET?: unknown;
    TAXJAR_KEY?: unknown;
    UPS_KEY?: unknown;
    DHL_KEY?: unknown;
};
export type Env = z.infer<typeof envSchema>;
export * from "./core";
export * from "./payments";
export * from "./shipping";
//# sourceMappingURL=index.d.ts.map