/**
 * Guide manifest loader for business-os.
 *
 * Loads the manifest data by executing brikette's guide manifest module
 * at runtime via ts-node/tsx or by reading a pre-generated JSON file.
 *
 * For local development: reads guide manifest entries from a generated
 * JSON file at apps/brikette/src/data/guides/guide-manifest-snapshot.json.
 * This file is generated by running `pnpm --filter brikette generate:manifest-snapshot`.
 *
 * The approach avoids cross-app TypeScript imports which require complex
 * webpack alias configuration.
 */
import fs from "fs";
import path from "path";

import {
  getGuideManifestEntry as _getEntry,
  getGuideManifestEntryWithOverrides as _getEntryWithOverrides,
  type GuideManifestEntry,
  listGuideManifestEntries as _listEntries,
  listGuideManifestEntriesWithOverrides as _listEntriesWithOverrides,
  type ManifestOverrides,
  registerManifestEntries,
  resolveDraftPathSegment,
} from "@acme/guide-system";

import { getBriketteRoot } from "./config";

let initialized = false;

/**
 * Load manifest entries from brikette's generated snapshot.
 * Falls back to reading all individual content files to build a minimal manifest.
 */
function loadManifestFromSnapshot(): GuideManifestEntry[] {
  const snapshotPath = path.join(
    getBriketteRoot(),
    "src/data/guides/guide-manifest-snapshot.json",
  );

  // eslint-disable-next-line security/detect-non-literal-fs-filename -- GS-001: path derived from config
  if (fs.existsSync(snapshotPath)) {
    // eslint-disable-next-line security/detect-non-literal-fs-filename -- GS-001: path derived from config
    const data = JSON.parse(fs.readFileSync(snapshotPath, "utf8"));
    if (Array.isArray(data)) return data as GuideManifestEntry[];
    if (data && typeof data === "object" && Array.isArray(data.entries)) {
      return data.entries as GuideManifestEntry[];
    }
  }

  console.warn(
    "[guide-authoring] No manifest snapshot found at",
    snapshotPath,
    "— run `pnpm --filter brikette generate:manifest-snapshot` to generate it.",
  );
  return [];
}

function ensureInitialized(): void {
  if (initialized) return;
  const entries = loadManifestFromSnapshot();
  registerManifestEntries(entries);
  initialized = true;
}

export function getGuideManifestEntry(key: string): GuideManifestEntry | undefined {
  ensureInitialized();
  return _getEntry(key);
}

export function listGuideManifestEntries(): GuideManifestEntry[] {
  ensureInitialized();
  return _listEntries();
}

export function getGuideManifestEntryWithOverrides(
  key: string,
  overrides: ManifestOverrides,
): GuideManifestEntry | undefined {
  ensureInitialized();
  return _getEntryWithOverrides(key, overrides);
}

export function listGuideManifestEntriesWithOverrides(
  overrides: ManifestOverrides,
): GuideManifestEntry[] {
  ensureInitialized();
  return _listEntriesWithOverrides(overrides);
}

export { resolveDraftPathSegment };
