export declare const env: import("zod").objectOutputType<{
    NEXTAUTH_SECRET: import("zod").ZodString | import("zod").ZodDefault<import("zod").ZodString>;
    PREVIEW_TOKEN_SECRET: import("zod").ZodOptional<import("zod").ZodString>;
    UPGRADE_PREVIEW_TOKEN_SECRET: import("zod").ZodOptional<import("zod").ZodString>;
    SESSION_SECRET: import("zod").ZodString | import("zod").ZodDefault<import("zod").ZodString>;
    COOKIE_DOMAIN: import("zod").ZodOptional<import("zod").ZodString>;
    LOGIN_RATE_LIMIT_REDIS_URL: import("zod").ZodOptional<import("zod").ZodString>;
    LOGIN_RATE_LIMIT_REDIS_TOKEN: import("zod").ZodOptional<import("zod").ZodString>;
    RATE_LIMIT_STORE_PROVIDER: import("zod").ZodOptional<import("zod").ZodEnum<["redis", "kv"]>>;
    CART_STORE_PROVIDER: import("zod").ZodOptional<import("zod").ZodEnum<["redis", "cloudflare", "memory"]>>;
    SESSION_STORE_PROVIDER: import("zod").ZodOptional<import("zod").ZodEnum<["redis", "cloudflare", "memory"]>>;
    SESSION_STORE: import("zod").ZodOptional<import("zod").ZodEnum<["memory", "redis"]>>;
    UPSTASH_REDIS_REST_URL: import("zod").ZodOptional<import("zod").ZodString>;
    UPSTASH_REDIS_REST_TOKEN: import("zod").ZodOptional<import("zod").ZodString>;
} & {
    CMS_SPACE_URL: import("zod").ZodOptional<import("zod").ZodString>;
    CMS_ACCESS_TOKEN: import("zod").ZodOptional<import("zod").ZodString>;
    SANITY_API_VERSION: import("zod").ZodOptional<import("zod").ZodString>;
} & {
    GMAIL_USER: import("zod").ZodOptional<import("zod").ZodString>;
    GMAIL_PASS: import("zod").ZodOptional<import("zod").ZodString>;
    SMTP_URL: import("zod").ZodOptional<import("zod").ZodString>;
    CAMPAIGN_FROM: import("zod").ZodOptional<import("zod").ZodString>;
    EMAIL_PROVIDER: import("zod").ZodDefault<import("zod").ZodEnum<["sendgrid", "resend", "smtp"]>>;
    SENDGRID_API_KEY: import("zod").ZodOptional<import("zod").ZodString>;
    SENDGRID_MARKETING_KEY: import("zod").ZodOptional<import("zod").ZodString>;
    RESEND_API_KEY: import("zod").ZodOptional<import("zod").ZodString>;
    EMAIL_BATCH_SIZE: import("zod").ZodOptional<import("zod").ZodNumber>;
    EMAIL_BATCH_DELAY_MS: import("zod").ZodOptional<import("zod").ZodNumber>;
} & {
    NODE_ENV: import("zod").ZodOptional<import("zod").ZodEnum<["development", "test", "production"]>>;
    OUTPUT_EXPORT: import("zod").ZodOptional<import("zod").ZodBoolean>;
    NEXT_PUBLIC_PHASE: import("zod").ZodOptional<import("zod").ZodString>;
    NEXT_PUBLIC_DEFAULT_SHOP: import("zod").ZodOptional<import("zod").ZodString>;
    NEXT_PUBLIC_SHOP_ID: import("zod").ZodOptional<import("zod").ZodString>;
    SHOP_CODE: import("zod").ZodOptional<import("zod").ZodString>;
    CART_COOKIE_SECRET: import("zod").ZodString | import("zod").ZodDefault<import("zod").ZodString>;
    CART_TTL: import("zod").ZodOptional<import("zod").ZodNumber>;
    CHROMATIC_PROJECT_TOKEN: import("zod").ZodOptional<import("zod").ZodString>;
    GA_API_SECRET: import("zod").ZodOptional<import("zod").ZodString>;
    DATABASE_URL: import("zod").ZodOptional<import("zod").ZodString>;
    CLOUDFLARE_ACCOUNT_ID: import("zod").ZodOptional<import("zod").ZodString>;
    CLOUDFLARE_API_TOKEN: import("zod").ZodOptional<import("zod").ZodString>;
    LUXURY_FEATURES_RA_TICKETING: import("zod").ZodOptional<import("zod").ZodBoolean>;
    LUXURY_FEATURES_FRAUD_REVIEW_THRESHOLD: import("zod").ZodOptional<import("zod").ZodNumber>;
    LUXURY_FEATURES_REQUIRE_STRONG_CUSTOMER_AUTH: import("zod").ZodOptional<import("zod").ZodBoolean>;
    LUXURY_FEATURES_TRACKING_DASHBOARD: import("zod").ZodOptional<import("zod").ZodBoolean>;
    LUXURY_FEATURES_RETURNS: import("zod").ZodOptional<import("zod").ZodBoolean>;
    DEPOSIT_RELEASE_ENABLED: import("zod").ZodOptional<import("zod").ZodEffects<import("zod").ZodEffects<import("zod").ZodString, "true" | "false", string>, boolean, string>>;
    DEPOSIT_RELEASE_INTERVAL_MS: import("zod").ZodOptional<import("zod").ZodEffects<import("zod").ZodEffects<import("zod").ZodString, string, string>, number, string>>;
    REVERSE_LOGISTICS_ENABLED: import("zod").ZodOptional<import("zod").ZodEffects<import("zod").ZodEffects<import("zod").ZodString, "true" | "false", string>, boolean, string>>;
    REVERSE_LOGISTICS_INTERVAL_MS: import("zod").ZodOptional<import("zod").ZodEffects<import("zod").ZodEffects<import("zod").ZodString, string, string>, number, string>>;
    LATE_FEE_ENABLED: import("zod").ZodOptional<import("zod").ZodEffects<import("zod").ZodEffects<import("zod").ZodString, "true" | "false", string>, boolean, string>>;
    LATE_FEE_INTERVAL_MS: import("zod").ZodOptional<import("zod").ZodEffects<import("zod").ZodEffects<import("zod").ZodString, string, string>, number, string>>;
    OPENAI_API_KEY: import("zod").ZodOptional<import("zod").ZodString>;
    NEXT_PUBLIC_BASE_URL: import("zod").ZodOptional<import("zod").ZodString>;
    STOCK_ALERT_RECIPIENTS: import("zod").ZodOptional<import("zod").ZodString>;
    STOCK_ALERT_WEBHOOK: import("zod").ZodOptional<import("zod").ZodString>;
    STOCK_ALERT_DEFAULT_THRESHOLD: import("zod").ZodOptional<import("zod").ZodNumber>;
    STOCK_ALERT_RECIPIENT: import("zod").ZodOptional<import("zod").ZodString>;
}, import("zod").ZodTypeAny, "passthrough">;
export type { CoreEnv as Env } from "./env/core";
