export const XA_B_DEPLOY_HOOK_URL_ENV = "XA_B_DEPLOY_HOOK_URL";
export const XA_B_DEPLOY_HOOK_TOKEN_ENV = "XA_B_DEPLOY_HOOK_TOKEN";
export const XA_B_DEPLOY_HOOK_REQUIRED_ENV = "XA_B_DEPLOY_HOOK_REQUIRED";
export const XA_UPLOADER_DEPLOY_DRAIN_TOKEN_ENV = "XA_UPLOADER_DEPLOY_DRAIN_TOKEN";

export const XA_UPLOADER_REQUIRED_CF_SECRET_NAMES = [
  "XA_UPLOADER_SESSION_SECRET",
  "XA_UPLOADER_ADMIN_TOKEN",
  "NEXTAUTH_SECRET",
  "SESSION_SECRET",
  "CART_COOKIE_SECRET",
  "XA_CATALOG_CONTRACT_BASE_URL",
  "XA_CATALOG_CONTRACT_WRITE_TOKEN",
  XA_B_DEPLOY_HOOK_URL_ENV,
  XA_B_DEPLOY_HOOK_TOKEN_ENV,
  XA_UPLOADER_DEPLOY_DRAIN_TOKEN_ENV,
] as const;
