name: "Setup Repo"
description: "Setup Node/PNPM and install dependencies with optional Turbo remote cache"

inputs:
  turbo-token:
    description: "Turbo remote cache token (from Vercel)"
    required: false
  turbo-team:
    description: "Turbo team slug for remote cache"
    required: false

runs:
  using: "composite"
  steps:
    - name: Setup PNPM
      uses: pnpm/action-setup@v4
      with:
        version: 10.12.1

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: "pnpm"

    - name: Install Dependencies
      run: pnpm install --frozen-lockfile
      shell: bash

    - name: Configure Turbo remote cache
      if: inputs.turbo-token != ''
      shell: bash
      run: |
        echo "TURBO_TOKEN=${{ inputs.turbo-token }}" >> $GITHUB_ENV
        echo "TURBO_TEAM=${{ inputs.turbo-team }}" >> $GITHUB_ENV
        echo "Turbo remote cache enabled for team: ${{ inputs.turbo-team }}"

    - name: Build eslint plugin
      run: pnpm --filter @acme/eslint-plugin-ds build
      shell: bash
