// src/routes/guides/blocks/types.ts
// Re-exports from @acme/guide-system for backward compatibility.
export {
  type AlsoHelpfulBlock,
  type AlsoHelpfulBlockOptions,
  type BreadcrumbsBlock,
  type BreadcrumbsBlockOptions,
  type CalloutBlock,
  type CalloutBlockOptions,
  type CustomBlock,
  type CustomBlockOptions,
  type FaqBlock,
  type FaqBlockOptions,
  type GenericContentBlock,
  type GenericContentBlockOptions,
  GUIDE_BLOCK_DECLARATION_SCHEMA,
  GUIDE_BLOCK_TYPES,
  type GuideBlockDeclaration,
  type GuideBlockType,
  type HeroBlock,
  type HeroBlockOptions,
  type JsonLdBlock,
  type JsonLdBlockOptions,
  type PlanChoiceBlock,
  type PlanChoiceBlockOptions,
  type RelatedGuidesBlock,
  type RelatedGuidesBlockOptions,
  type ServiceSchemaBlock,
  type ServiceSchemaBlockOptions,
  type TableBlock,
  type TableBlockOptions,
  type TransportDropInBlock,
  type TransportDropInBlockOptions,
  type TransportNoticeBlock,
  type TransportNoticeBlockOptions,
} from "@acme/guide-system";
