import { z } from "zod";
export declare const rentalOrderSchema: z.ZodObject<{
    id: z.ZodString;
    sessionId: z.ZodString;
    shop: z.ZodString;
    deposit: z.ZodNumber;
    expectedReturnDate: z.ZodOptional<z.ZodString>;
    returnDueDate: z.ZodOptional<z.ZodString>;
    startedAt: z.ZodString;
    returnedAt: z.ZodOptional<z.ZodString>;
    returnReceivedAt: z.ZodOptional<z.ZodString>;
    refundedAt: z.ZodOptional<z.ZodString>;
    refundTotal: z.ZodOptional<z.ZodNumber>;
    /** Optional damage fee deducted from the deposit */
    damageFee: z.ZodOptional<z.ZodNumber>;
    lateFeeCharged: z.ZodOptional<z.ZodNumber>;
    fulfilledAt: z.ZodOptional<z.ZodString>;
    shippedAt: z.ZodOptional<z.ZodString>;
    deliveredAt: z.ZodOptional<z.ZodString>;
    cancelledAt: z.ZodOptional<z.ZodString>;
    customerId: z.ZodOptional<z.ZodString>;
    riskLevel: z.ZodOptional<z.ZodString>;
    riskScore: z.ZodOptional<z.ZodNumber>;
    flaggedForReview: z.ZodOptional<z.ZodBoolean>;
    trackingNumber: z.ZodOptional<z.ZodString>;
    labelUrl: z.ZodOptional<z.ZodString>;
    returnStatus: z.ZodOptional<z.ZodString>;
    status: z.ZodOptional<z.ZodEnum<["received", "cleaning", "repair", "qa", "available"]>>;
    currency: z.ZodOptional<z.ZodString>;
    subtotalAmount: z.ZodOptional<z.ZodNumber>;
    taxAmount: z.ZodOptional<z.ZodNumber>;
    shippingAmount: z.ZodOptional<z.ZodNumber>;
    discountAmount: z.ZodOptional<z.ZodNumber>;
    totalAmount: z.ZodOptional<z.ZodNumber>;
    cartId: z.ZodOptional<z.ZodString>;
    stripePaymentIntentId: z.ZodOptional<z.ZodString>;
    stripeChargeId: z.ZodOptional<z.ZodString>;
    stripeBalanceTransactionId: z.ZodOptional<z.ZodString>;
    stripeCustomerId: z.ZodOptional<z.ZodString>;
    /** Variant allocation details for inventory linkage */
    lineItems: z.ZodOptional<z.ZodArray<z.ZodObject<{
        sku: z.ZodString;
        productId: z.ZodOptional<z.ZodString>;
        variantAttributes: z.ZodRecord<z.ZodString, z.ZodString>;
        quantity: z.ZodOptional<z.ZodNumber>;
    }, "strict", z.ZodTypeAny, {
        sku: string;
        productId?: string | undefined;
        variantAttributes: Record<string, string>;
        quantity?: number | undefined;
    }, {
        sku: string;
        productId?: string | undefined;
        variantAttributes: Record<string, string>;
        quantity?: number | undefined;
    }>>>;
}, "strict", z.ZodTypeAny, {
    shop: string;
    id: string;
    deposit: number;
    sessionId: string;
    startedAt: string;
    status?: "received" | "cleaning" | "repair" | "qa" | "available" | undefined;
    expectedReturnDate?: string | undefined;
    returnDueDate?: string | undefined;
    returnedAt?: string | undefined;
    returnReceivedAt?: string | undefined;
    refundedAt?: string | undefined;
    refundTotal?: number | undefined;
    damageFee?: number | undefined;
    lateFeeCharged?: number | undefined;
    fulfilledAt?: string | undefined;
    shippedAt?: string | undefined;
    deliveredAt?: string | undefined;
    cancelledAt?: string | undefined;
    customerId?: string | undefined;
    riskLevel?: string | undefined;
    riskScore?: number | undefined;
    flaggedForReview?: boolean | undefined;
    trackingNumber?: string | undefined;
    labelUrl?: string | undefined;
    returnStatus?: string | undefined;
    currency?: string | undefined;
    subtotalAmount?: number | undefined;
    taxAmount?: number | undefined;
    shippingAmount?: number | undefined;
    discountAmount?: number | undefined;
    totalAmount?: number | undefined;
    cartId?: string | undefined;
    stripePaymentIntentId?: string | undefined;
    stripeChargeId?: string | undefined;
    stripeBalanceTransactionId?: string | undefined;
    stripeCustomerId?: string | undefined;
    lineItems?: {
        sku: string;
        productId?: string | undefined;
        variantAttributes: Record<string, string>;
        quantity?: number | undefined;
    }[] | undefined;
}, {
    shop: string;
    id: string;
    deposit: number;
    sessionId: string;
    startedAt: string;
    status?: "received" | "cleaning" | "repair" | "qa" | "available" | undefined;
    expectedReturnDate?: string | undefined;
    returnDueDate?: string | undefined;
    returnedAt?: string | undefined;
    returnReceivedAt?: string | undefined;
    refundedAt?: string | undefined;
    refundTotal?: number | undefined;
    damageFee?: number | undefined;
    lateFeeCharged?: number | undefined;
    fulfilledAt?: string | undefined;
    shippedAt?: string | undefined;
    deliveredAt?: string | undefined;
    cancelledAt?: string | undefined;
    customerId?: string | undefined;
    riskLevel?: string | undefined;
    riskScore?: number | undefined;
    flaggedForReview?: boolean | undefined;
    trackingNumber?: string | undefined;
    labelUrl?: string | undefined;
    returnStatus?: string | undefined;
    currency?: string | undefined;
    subtotalAmount?: number | undefined;
    taxAmount?: number | undefined;
    shippingAmount?: number | undefined;
    discountAmount?: number | undefined;
    totalAmount?: number | undefined;
    cartId?: string | undefined;
    stripePaymentIntentId?: string | undefined;
    stripeChargeId?: string | undefined;
    stripeBalanceTransactionId?: string | undefined;
    stripeCustomerId?: string | undefined;
    lineItems?: {
        sku: string;
        productId?: string | undefined;
        variantAttributes: Record<string, string>;
        quantity?: number | undefined;
    }[] | undefined;
}>;
export type RentalOrder = z.infer<typeof rentalOrderSchema>;
