import { type RouteOption } from "./types";

export const romeRoutes: RouteOption[] = [
  {
    id: "naples-bus-train-to-hostel",
    direction: "from-rome",
    hub: "naples",
    mode: "bus-train",
    changes: 2,
    titleKey: "romePlanner.route.naples.busTrain.title",
    shortSummaryKey: "romePlanner.route.naples.busTrain.summary.to",
    notesKeys: [],
    prosKeys: [
      "romePlanner.pro.easySwapNaples",
      "romePlanner.pro.trainDropsSorrentoBusStation",
      "romePlanner.pro.cheapBusTrain",
      "romePlanner.pro.posBusNearHostel",
    ],
    consKeys: [
      "romePlanner.con.changeTrainToBusSorrento",
      "romePlanner.con.crowdedBusTrain",
      "romePlanner.con.fewHours",
    ],
    steps: [
      { labelKey: "romePlanner.route.naples.busTrain.steps.to.1" },
      { labelKey: "romePlanner.route.naples.busTrain.steps.to.2" },
      { labelKey: "romePlanner.route.naples.busTrain.steps.to.3" },
    ],
    tagsKeys: [
      "romePlanner.tag.train",
      "romePlanner.tag.bus",
      "romePlanner.tag.transfer",
    ],
  },
  {
    id: "salerno-bus-to-hostel",
    direction: "from-rome",
    hub: "salerno",
    mode: "bus",
    changes: 1,
    titleKey: "romePlanner.route.salerno.bus.title",
    shortSummaryKey: "romePlanner.route.salerno.bus.summary.to",
    notesKeys: [],
    prosKeys: [
      "romePlanner.pro.salerno.busStopNearHostel",
      "romePlanner.pro.busCollectsSalernoStation",
      "romePlanner.pro.busCheap",
    ],
    consKeys: [
      "romePlanner.con.changeBusesAmalfi",
      "romePlanner.con.busUsuallyCrowded",
    ],
    steps: [
      { labelKey: "romePlanner.route.salerno.bus.steps.to.1" },
      { labelKey: "romePlanner.route.salerno.bus.steps.to.2" },
      { labelKey: "romePlanner.route.salerno.bus.steps.to.3" },
    ],
    tagsKeys: [
      "romePlanner.tag.bus",
      "romePlanner.tag.transfer",
      "romePlanner.tag.cheap",
    ],
  },
  {
    id: "salerno-ferry-to-hostel",
    direction: "from-rome",
    hub: "salerno",
    mode: "ferry",
    changes: 0,
    titleKey: "romePlanner.route.salerno.ferry.title",
    shortSummaryKey: "romePlanner.route.salerno.ferry.summary.to",
    notesKeys: ["romePlanner.note.salerno.walkPortStation"],
    prosKeys: [
      "romePlanner.pro.portersHelp",
      "romePlanner.pro.ferryEnjoyableEasy",
      "romePlanner.pro.shortWalkSalernoStationPort",
    ],
    consKeys: [
      "romePlanner.con.ferryCostHigherBus",
      "romePlanner.con.hostelEasierBySita",
    ],
    steps: [
      { labelKey: "romePlanner.route.salerno.ferry.steps.to.1" },
      { labelKey: "romePlanner.route.salerno.ferry.steps.to.2" },
      { labelKey: "romePlanner.route.salerno.ferry.steps.to.3" },
      { labelKey: "romePlanner.route.salerno.ferry.steps.to.4" },
    ],
    tagsKeys: ["romePlanner.tag.ferry", "romePlanner.tag.scenic"],
  },
  {
    id: "naples-ferry-to-hostel",
    direction: "from-rome",
    hub: "naples",
    mode: "ferry",
    changes: 0,
    titleKey: "romePlanner.route.naples.ferry.title",
    shortSummaryKey: "romePlanner.route.naples.ferry.summary.to",
    notesKeys: ["romePlanner.note.naples.tramPortStation"],
    prosKeys: [
      "romePlanner.pro.portersHelp",
      "romePlanner.pro.ferryEnjoyableEasy",
    ],
    consKeys: [
      "romePlanner.con.naplesPortComfort",
      "romePlanner.con.ferriesLessFrequent",
      "romePlanner.con.ferryCostHigherTrainBus",
      "romePlanner.con.hostelEasierBySita",
    ],
    steps: [
      { labelKey: "romePlanner.route.naples.ferry.steps.to.1" },
      { labelKey: "romePlanner.route.naples.ferry.steps.to.2" },
      { labelKey: "romePlanner.route.naples.ferry.steps.to.3" },
      { labelKey: "romePlanner.route.naples.ferry.steps.to.4" },
    ],
    tagsKeys: ["romePlanner.tag.ferry", "romePlanner.tag.scenic"],
  },
  {
    id: "naples-bus-train-to-rome",
    direction: "to-rome",
    hub: "naples",
    mode: "bus-train",
    changes: 2,
    titleKey: "romePlanner.route.naples.busTrain.title",
    shortSummaryKey: "romePlanner.route.naples.busTrain.summary.from",
    notesKeys: [],
    prosKeys: [
      "romePlanner.pro.posBusNearHostel",
      "romePlanner.pro.busDropsSorrentoStation",
      "romePlanner.pro.cheapBusTrain",
      "romePlanner.pro.arriveNaplesStation",
    ],
    consKeys: [
      "romePlanner.con.changeBusToTrain",
      "romePlanner.con.crowdedBusTrain",
      "romePlanner.con.fewHours",
    ],
    steps: [
      { labelKey: "romePlanner.route.naples.busTrain.steps.from.1" },
      { labelKey: "romePlanner.route.naples.busTrain.steps.from.2" },
      { labelKey: "romePlanner.route.naples.busTrain.steps.from.3" },
    ],
    tagsKeys: [
      "romePlanner.tag.bus",
      "romePlanner.tag.train",
      "romePlanner.tag.transfer",
    ],
  },
  {
    id: "salerno-bus-to-rome",
    direction: "to-rome",
    hub: "salerno",
    mode: "bus",
    changes: 1,
    titleKey: "romePlanner.route.salerno.bus.title",
    shortSummaryKey: "romePlanner.route.salerno.bus.summary.from",
    notesKeys: [],
    prosKeys: [
      "romePlanner.pro.salerno.busStopNearHostel",
      "romePlanner.pro.busDropsSalernoStation",
      "romePlanner.pro.busCheap",
    ],
    consKeys: [
      "romePlanner.con.changeBusesAmalfi",
      "romePlanner.con.busUsuallyCrowded",
    ],
    steps: [
      { labelKey: "romePlanner.route.salerno.bus.steps.from.1" },
      { labelKey: "romePlanner.route.salerno.bus.steps.from.2" },
      { labelKey: "romePlanner.route.salerno.bus.steps.from.3" },
    ],
    tagsKeys: [
      "romePlanner.tag.bus",
      "romePlanner.tag.transfer",
      "romePlanner.tag.cheap",
    ],
  },
  {
    id: "salerno-ferry-to-rome",
    direction: "to-rome",
    hub: "salerno",
    mode: "ferry",
    changes: 0,
    titleKey: "romePlanner.route.salerno.ferry.title",
    shortSummaryKey: "romePlanner.route.salerno.ferry.summary.from",
    notesKeys: ["romePlanner.note.salerno.walkPortStation"],
    prosKeys: [
      "romePlanner.pro.portersHelp",
      "romePlanner.pro.ferryEnjoyableEasy",
      "romePlanner.pro.shortWalkSalernoStationPort",
    ],
    consKeys: ["romePlanner.con.ferryCostHigherBus"],
    steps: [
      { labelKey: "romePlanner.route.salerno.ferry.steps.from.1" },
      { labelKey: "romePlanner.route.salerno.ferry.steps.from.2" },
      { labelKey: "romePlanner.route.salerno.ferry.steps.from.3" },
      { labelKey: "romePlanner.route.salerno.ferry.steps.from.4" },
    ],
    tagsKeys: ["romePlanner.tag.ferry", "romePlanner.tag.scenic"],
  },
  {
    id: "naples-ferry-to-rome",
    direction: "to-rome",
    hub: "naples",
    mode: "ferry",
    changes: 0,
    titleKey: "romePlanner.route.naples.ferry.title",
    shortSummaryKey: "romePlanner.route.naples.ferry.summary.from",
    notesKeys: ["romePlanner.note.naples.tramPortStation"],
    prosKeys: [
      "romePlanner.pro.portersHelp",
      "romePlanner.pro.ferryEnjoyableEasy",
    ],
    consKeys: [
      "romePlanner.con.naplesPortComfort",
      "romePlanner.con.ferriesLessFrequent",
      "romePlanner.con.ferryCostHigherTrainBus",
    ],
    steps: [
      { labelKey: "romePlanner.route.naples.ferry.steps.from.1" },
      { labelKey: "romePlanner.route.naples.ferry.steps.from.2" },
      { labelKey: "romePlanner.route.naples.ferry.steps.from.3" },
      { labelKey: "romePlanner.route.naples.ferry.steps.from.4" },
    ],
    tagsKeys: ["romePlanner.tag.ferry", "romePlanner.tag.scenic"],
  },
];
