export declare const version = "0.0.0-dev";
export { coreBlockDescriptors } from "./blocks/core-blocks";
export * from "./blocks/registry";
export { commit, redo,undo } from "./history";
export type { PageDiffEntry } from "./pageHistory";
export { diffPage, mergeDefined, parsePageDiffHistory, } from "./pageHistory";
export type { ExportedComponent } from "./runtime/exportComponents";
export { exportComponents, exportComponentsFromHistory, } from "./runtime/exportComponents";
export type { ScaffoldContext,TemplateDescriptor, TemplateKind, TemplateOrigin,  } from "./templates";
export { cloneTemplateComponents, scaffoldPageFromTemplate, } from "./templates";
export type { EditorFlags,HistoryState, Page, PageComponent,  } from "@acme/types";
export { historyStateSchema, pageComponentSchema,pageSchema,  } from "@acme/types";
