// scripts/build-tokens.ts
/* eslint-disable @typescript-eslint/no-require-imports -- ENG-2005: dist-scripts are CommonJS-style Node entrypoints used by CLI and tests [ttl=2026-12-31] */
import { readdirSync, readFileSync, writeFileSync, existsSync } from "node:fs";
import { join } from "node:path";
import { runInNewContext } from "node:vm";
import ts from "typescript";
const { tokens } = require("../packages/themes/base/tokens.js");
/**
 * Create a plain-value stylesheet (no CSS variables).
 */
function generateStaticCss(map) {
    let css = "/* Generated by build-tokens.ts */\n\n:root {\n";
    const darkEntries = [];
    for (const [name, defs] of Object.entries(map)) {
        css += `  ${name}: ${defs.light};\n`;
        if (defs.dark !== undefined) {
            css += `  ${name}-dark: ${defs.dark};\n`;
            darkEntries.push([name, defs]);
        }
    }
    css += "}\n";
    if (darkEntries.length) {
        css += "\n@media (prefers-color-scheme: dark) {\n  :root {\n";
        for (const [name] of darkEntries) {
            css += `    ${name}: var(${name}-dark);\n`;
        }
        css += "  }\n}\n";
        css += "\nhtml.theme-dark {\n";
        for (const [name] of darkEntries) {
            css += `  ${name}: var(${name}-dark);\n`;
        }
        css += "}\n";
    }
    return css;
}
/**
 * Create a CSS-variable stylesheet so end-users can override tokens.
 */
function generateDynamicCss(map) {
    let css = "/* Generated by build-tokens.ts */\n\n:root {\n";
    const darkEntries = [];
    for (const [name, defs] of Object.entries(map)) {
        const varName = `--token-${name.slice(2)}`;
        css += `  ${name}: var(${varName}, ${defs.light});\n`;
        if (defs.dark !== undefined) {
            const darkVar = `--token-${name.slice(2)}-dark`;
            css += `  ${name}-dark: var(${darkVar}, ${defs.dark});\n`;
            darkEntries.push([name, defs]);
        }
    }
    css += "}\n";
    if (darkEntries.length) {
        css += "\n@media (prefers-color-scheme: dark) {\n  :root {\n";
        for (const [name] of darkEntries) {
            css += `    ${name}: var(${name}-dark);\n`;
        }
        css += "  }\n}\n";
        css += "\nhtml.theme-dark {\n";
        for (const [name] of darkEntries) {
            css += `  ${name}: var(${name}-dark);\n`;
        }
        css += "}\n";
    }
    return css;
}
const outDir = join(__dirname, "..", "packages", "themes", "base");
writeFileSync(join(outDir, "tokens.static.css"), generateStaticCss(tokens));
writeFileSync(join(outDir, "tokens.dynamic.css"), generateDynamicCss(tokens));
console.log("→ tokens.static.css and tokens.dynamic.css generated");
/* -------------------------------------------------------------------------- */
/*  Additional theme tokens                                                   */
/* -------------------------------------------------------------------------- */
function generateThemeCss(map) {
    let css = "/* Generated by build-tokens.ts */\n\n:root {\n";
    const darkEntries = [];
    for (const [name, val] of Object.entries(map)) {
        if (name.endsWith("-dark")) {
            const base = name.replace(/-dark$/, "");
            if (map[base] !== undefined) {
                css += `  ${name}: ${val};\n`;
                darkEntries.push([base, name]);
            }
        }
        else {
            css += `  ${name}: ${val};\n`;
        }
    }
    css += "}\n";
    if (darkEntries.length) {
        css += "\n@media (prefers-color-scheme: dark) {\n  :root {\n";
        for (const [base, dark] of darkEntries) {
            css += `    ${base}: var(${dark});\n`;
        }
        css += "  }\n}\n";
        css += "\nhtml.theme-dark {\n";
        for (const [base, dark] of darkEntries) {
            css += `  ${base}: var(${dark});\n`;
        }
        css += "}\n";
    }
    return css;
}
async function buildThemeCss() {
    const themesDir = join(__dirname, "..", "packages", "themes");
    const themes = readdirSync(themesDir, { withFileTypes: true })
        .filter((d) => d.isDirectory() && d.name !== "base")
        .map((d) => d.name);
    for (const theme of themes) {
        const modPath = join(themesDir, theme, "src", "tailwind-tokens.ts");
        // eslint-disable-next-line security/detect-non-literal-fs-filename -- SEC-2004: modPath is workspace-relative theme token path; script is CLI-only and not exposed to HTTP input [ttl=2026-12-31]
        if (!existsSync(modPath))
            continue;
        // eslint-disable-next-line security/detect-non-literal-fs-filename -- SEC-2004: modPath is workspace-relative theme token path; script is CLI-only and not exposed to HTTP input [ttl=2026-12-31]
        const source = readFileSync(modPath, "utf8");
        const transpiled = ts.transpileModule(source, {
            compilerOptions: { module: ts.ModuleKind.CommonJS },
        }).outputText;
        const sandbox = {
            module: { exports: {} },
            exports: {},
            require,
        };
        sandbox.exports = sandbox.module.exports;
        runInNewContext(transpiled, sandbox);
        const themeTokens = sandbox.module.exports.tokens;
        const css = generateThemeCss(themeTokens);
        // eslint-disable-next-line security/detect-non-literal-fs-filename -- SEC-2004: output path is workspace-relative under packages/themes; script is CLI-only [ttl=2026-12-31]
        writeFileSync(join(themesDir, theme, "src", "tokens.css"), css);
    }
}
void buildThemeCss()
    .then(() => {
    console.log("→ theme tokens generated");
})
    .catch((err) => {
    console.error(err);
	    process.exit(1);
	});

export { generateStaticCss, generateDynamicCss, generateThemeCss };
