import type { AppLanguage } from "../../i18n.config";

type SlugOverrides = Partial<Record<AppLanguage, string>>;

// Stability and explicitness: per-guide slug overrides by locale.
// Keys are guide IDs; values map language → slug.
// Note: Use string keys to avoid circular deps with GuideKey typing.
export const GUIDE_SLUG_OVERRIDES: Partial<Record<string, SlugOverrides>> = Object.freeze({
  ferryDockToBrikette: {
    en: "ferry-dock-to-hostel-brikette-with-luggage",
    de: "ferry-dock-to-hostel-brikette-with-luggage",
    es: "ferry-dock-to-hostel-brikette-with-luggage",
    fr: "ferry-dock-to-hostel-brikette-with-luggage",
    it: "ferry-dock-to-hostel-brikette-with-luggage",
    ja: "ferry-dock-to-hostel-brikette-with-luggage",
    ko: "ferry-dock-to-hostel-brikette-with-luggage",
    pt: "ferry-dock-to-hostel-brikette-with-luggage",
    ru: "ferry-dock-to-hostel-brikette-with-luggage",
    zh: "ferry-dock-to-hostel-brikette-with-luggage",
    ar: "ferry-dock-to-hostel-brikette-with-luggage",
    hi: "ferry-dock-to-hostel-brikette-with-luggage",
    vi: "ferry-dock-to-hostel-brikette-with-luggage",
    pl: "ferry-dock-to-hostel-brikette-with-luggage",
    sv: "ferry-dock-to-hostel-brikette-with-luggage",
    no: "ferry-dock-to-hostel-brikette-with-luggage",
    da: "ferry-dock-to-hostel-brikette-with-luggage",
    hu: "ferry-dock-to-hostel-brikette-with-luggage",
  },
  briketteToFerryDock: {
    en: "hostel-brikette-to-ferry-dock-with-luggage",
    de: "hostel-brikette-to-ferry-dock-with-luggage",
    es: "hostel-brikette-to-ferry-dock-with-luggage",
    fr: "hostel-brikette-to-ferry-dock-with-luggage",
    it: "hostel-brikette-to-ferry-dock-with-luggage",
    ja: "hostel-brikette-to-ferry-dock-with-luggage",
    ko: "hostel-brikette-to-ferry-dock-with-luggage",
    pt: "hostel-brikette-to-ferry-dock-with-luggage",
    ru: "hostel-brikette-to-ferry-dock-with-luggage",
    zh: "hostel-brikette-to-ferry-dock-with-luggage",
    ar: "hostel-brikette-to-ferry-dock-with-luggage",
    hi: "hostel-brikette-to-ferry-dock-with-luggage",
    vi: "hostel-brikette-to-ferry-dock-with-luggage",
    pl: "hostel-brikette-to-ferry-dock-with-luggage",
    sv: "hostel-brikette-to-ferry-dock-with-luggage",
    no: "hostel-brikette-to-ferry-dock-with-luggage",
    da: "hostel-brikette-to-ferry-dock-with-luggage",
    hu: "hostel-brikette-to-ferry-dock-with-luggage",
  },
  chiesaNuovaArrivals: {
    en: "chiesa-nuova-bar-internazionale-to-hostel-brikette",
    de: "chiesa-nuova-bar-internazionale-to-hostel-brikette",
    es: "chiesa-nuova-bar-internazionale-to-hostel-brikette",
    fr: "chiesa-nuova-bar-internazionale-to-hostel-brikette",
    it: "chiesa-nuova-bar-internazionale-to-hostel-brikette",
    ja: "chiesa-nuova-bar-internazionale-to-hostel-brikette",
    ko: "chiesa-nuova-bar-internazionale-to-hostel-brikette",
    pt: "chiesa-nuova-bar-internazionale-to-hostel-brikette",
    ru: "chiesa-nuova-bar-internazionale-to-hostel-brikette",
    zh: "chiesa-nuova-bar-internazionale-to-hostel-brikette",
    ar: "chiesa-nuova-bar-internazionale-to-hostel-brikette",
    hi: "chiesa-nuova-bar-internazionale-to-hostel-brikette",
    vi: "chiesa-nuova-bar-internazionale-to-hostel-brikette",
    pl: "chiesa-nuova-bar-internazionale-to-hostel-brikette",
    sv: "chiesa-nuova-bar-internazionale-to-hostel-brikette",
    no: "chiesa-nuova-bar-internazionale-to-hostel-brikette",
    da: "chiesa-nuova-bar-internazionale-to-hostel-brikette",
    hu: "chiesa-nuova-bar-internazionale-to-hostel-brikette",
  },
  chiesaNuovaDepartures: {
    en: "hostel-brikette-to-chiesa-nuova-bar-internazionale",
    de: "hostel-brikette-to-chiesa-nuova-bar-internazionale",
    es: "hostel-brikette-to-chiesa-nuova-bar-internazionale",
    fr: "hostel-brikette-to-chiesa-nuova-bar-internazionale",
    it: "hostel-brikette-to-chiesa-nuova-bar-internazionale",
    ja: "hostel-brikette-to-chiesa-nuova-bar-internazionale",
    ko: "hostel-brikette-to-chiesa-nuova-bar-internazionale",
    pt: "hostel-brikette-to-chiesa-nuova-bar-internazionale",
    ru: "hostel-brikette-to-chiesa-nuova-bar-internazionale",
    zh: "hostel-brikette-to-chiesa-nuova-bar-internazionale",
    ar: "hostel-brikette-to-chiesa-nuova-bar-internazionale",
    hi: "hostel-brikette-to-chiesa-nuova-bar-internazionale",
    vi: "hostel-brikette-to-chiesa-nuova-bar-internazionale",
    pl: "hostel-brikette-to-chiesa-nuova-bar-internazionale",
    sv: "hostel-brikette-to-chiesa-nuova-bar-internazionale",
    no: "hostel-brikette-to-chiesa-nuova-bar-internazionale",
    da: "hostel-brikette-to-chiesa-nuova-bar-internazionale",
    hu: "hostel-brikette-to-chiesa-nuova-bar-internazionale",
  },
  fornilloBeachToBrikette: {
    en: "fornillo-beach-to-hostel-brikette",
    de: "fornillo-beach-to-hostel-brikette",
    es: "fornillo-beach-to-hostel-brikette",
    fr: "fornillo-beach-to-hostel-brikette",
    it: "fornillo-beach-to-hostel-brikette",
    ja: "fornillo-beach-to-hostel-brikette",
    ko: "fornillo-beach-to-hostel-brikette",
    pt: "fornillo-beach-to-hostel-brikette",
    ru: "fornillo-beach-to-hostel-brikette",
    zh: "fornillo-beach-to-hostel-brikette",
    ar: "fornillo-beach-to-hostel-brikette",
    hi: "fornillo-beach-to-hostel-brikette",
    vi: "fornillo-beach-to-hostel-brikette",
    pl: "fornillo-beach-to-hostel-brikette",
    sv: "fornillo-beach-to-hostel-brikette",
    no: "fornillo-beach-to-hostel-brikette",
    da: "fornillo-beach-to-hostel-brikette",
    hu: "fornillo-beach-to-hostel-brikette",
  },
  publicTransportAmalfi: {
    en: "amalfi-coast-public-transport-guide",
    fr: "amalfi-coast-public-transport-guide",
  },
  travelTipsFirstTime: {
    en: "positano-travel-tips-first-time-visitors",
  },
  workAndTravelPositano: {
    en: "work-and-travel-remote-work-positano",
    fr: "work-and-travel-remote-work-positano",
  },
  workExchangeItaly: {
    en: "work-exchange-in-italian-hostels",
  },
  whatToPack: {
    en: "what-to-pack-amalfi-coast",
  },
  dayTripsAmalfi: {
    en: "day-trips-from-positano",
  },
  // Ensure breadcrumbs and URLs for this guide match the route filename
  // expectation (e.g., "/it/guides/groceries-and-pharmacies-positano").
  groceriesPharmacies: {
    en: "groceries-and-pharmacies-positano",
    it: "groceries-and-pharmacies-positano",
  },
});
