// src/config/rooms.ts
// ─────────────────────────────────────────────────────────────
import type { RoomCategory } from "../types/machine-layer/ml.ts";
import { roomCategorySchema } from "../types/schemas";

const rooms: RoomCategory[] = [
  /* ───────────── 4-Bed Mixed Dorm ───────────── */
  {
    sku: "DR4",
    name: {
      en: "4-Bed Mixed Dorm",
      de: "4-Bett-Mischschlafsaal",
      es: "Dormitorio mixto de 4 camas",
      fr: "Dortoir mixte 4 lits",
      hi: "4-बेड मिश्रित डॉर्म",
      it: "Dormitorio misto 4 letti",
      ja: "4人部屋ドミトリー",
      ko: "4인 혼성 도미토리",
      pt: "Dormitório misto 4 camas",
      ru: "4-местный смешанный",
      vi: "Ký túc xá hỗn hợp 4 giường",
      zh: "4人混合宿舍",
      sv: "4-bäddars blandad sovsal",
      ar: "مهجع مختلط بأربعة أسرّة",
      pl: "4-osobowy pokój wieloosobowy (mieszany)",
      no: "4-sengs blandet sovesal",
      da: "4-sengs blandet dorm",
      hu: "4 ágyas vegyes hálóterem",
    },
    description: {
      en: "Bright room with sturdy wooden bunks, personal light & power, shared bathroom.",
      de: "Helles Zimmer mit stabilen Holzbetten, eigener Lampe & Steckdose, Gemeinschaftsbad.",
      es: "Habitación luminosa con literas de madera, luz y enchufe individual, baño compartido.",
      fr: "Chambre lumineuse avec lits superposés en bois, lampe et prise personnelles, salle de bain partagée.",
      hi: "मजबूत लकड़ी के बंक के साथ उजला कमरा, व्यक्तिगत लाइट और पावर सॉकेट, साझा बाथरूम।",
      it: "Camera luminosa con letti a castello in legno, luce e presa personali, bagno condiviso.",
      ja: "木製2段ベッド、読書灯・コンセント付き。共同バスルーム。",
      ko: "튼튼한 목재 2층 침대, 개인 조명·콘센트, 공용 욕실.",
      pt: "Quarto claro com beliches de madeira, luz e tomada individuais, banheiro compartilhado.",
      ru: "Светлая комната с деревянными двухъярусными кроватями, индивидуальной лампой и розеткой, общий санузел.",
      vi: "Phòng sáng sủa với giường tầng gỗ chắc chắn, đèn và ổ cắm riêng, phòng tắm chung.",
      zh: "明亮房间配木质双层床、个人灯及插座，共用浴室。",
      sv: "Ljust rum med robusta trävåningssängar, egen lampa och eluttag, delat badrum.",
      ar: "غرفة مشرقة تحتوي على أسرّة بطابقين خشبية متينة، وإضاءة ومقبس شخصيين، وحمام مشترك.",
      pl: "Jasny pokój z solidnymi drewnianymi łóżkami piętrowymi, własną lampką i gniazdkiem; wspólna łazienka.",
      no: "Lyst rom med solide køyesenger i tre, egen lampe og strømuttak, delt bad.",
      da: "Lyst værelse med robuste køjesenge i træ, egen lampe og strømudtag, fælles badeværelse.",
      hu: "Világos szoba masszív fa emeletes ágyakkal, saját lámpával és konnektorral, közös fürdőszobával.",
    },
    occupancy: 4,
    pricingModel: "perBed",
    basePrice: { amount: 25, currency: "EUR" },
    seasonalPrices: [
      {
        season: "high",
        start: "2025-06-01",
        end: "2025-08-31",
        price: { amount: 32, currency: "EUR" },
      },
      {
        season: "event",
        start: "2025-12-24",
        end: "2026-01-06",
        price: { amount: 38, currency: "EUR" },
      },
    ],
    amenities: [
      { name: "Reading light", icon: "lightbulb" },
      { name: "Power socket", icon: "plug" },
      { name: "Air-con", icon: "snowflake" },
      { name: "Shared bathroom" },
      { name: "Free Wi-Fi", icon: "wifi" },
      { name: "Security locker", icon: "lock" },
    ],
    availability: { totalBeds: 32, defaultRelease: 28 },
    images: [
      {
        url: "/images/rooms/dorm4-1.jpg",
        alt: {
          en: "4-bed mixed dorm",
          de: "Vierbettzimmer, gemischt",
          es: "Dormitorio mixto de cuatro camas",
          fr: "Dortoir mixte quatre lits",
          hi: "4-बेड मिश्रित डॉर्म",
          it: "Dormitorio misto quattro letti",
          ja: "4人ドミトリー",
          ko: "4인 혼성 도미토리",
          pt: "Dormitório misto quatro camas",
          ru: "Четырёхместный смешанный",
          vi: "Ký túc xá hỗn hợp 4 giường",
          zh: "4人混合宿舍",
          sv: "4-bäddars blandad sovsal",
          ar: "مهجع مختلط بأربعة أسرّة",
          pl: "4-osobowy mieszany pokój wieloosobowy",
          no: "4-sengs blandet sovesal",
          da: "4-sengs blandet dorm",
          hu: "4 ágyas vegyes hálóterem",
        },
      },
    ],
  },

  /* ───────────── 6-Bed Mixed Dorm ───────────── */
  {
    sku: "DR6",
    name: {
      en: "6-Bed Mixed Dorm",
      de: "6-Bett-Mischschlafsaal",
      es: "Dormitorio mixto de 6 camas",
      fr: "Dortoir mixte 6 lits",
      hi: "6-बेड मिश्रित डॉर्म",
      it: "Dormitorio misto 6 letti",
      ja: "6人部屋ドミトリー",
      ko: "6인 혼성 도미토리",
      pt: "Dormitório misto 6 camas",
      ru: "6-местный смешанный",
      vi: "Ký túc xá hỗn hợp 6 giường",
      zh: "6人混合宿舍",
      sv: "6-bäddars blandad sovsal",
      ar: "مهجع مختلط بستة أسرّة",
      pl: "6-osobowy pokój wieloosobowy (mieszany)",
      no: "6-sengs blandet sovesal",
      da: "6-sengs blandet dorm",
      hu: "6 ágyas vegyes hálóterem",
    },
    description: {
      en: "Spacious dorm with individual lockers and balcony access. Shared bathroom.",
      de: "Geräumiger Schlafsaal mit individuellen Spinden und Balkonzugang. Gemeinschaftsbad.",
      es: "Dormitorio amplio con taquillas individuales y acceso a balcón. Baño compartido.",
      fr: "Dortoir spacieux avec casiers individuels et accès balcon. Salle de bain partagée.",
      hi: "व्यक्तिगत लॉकर और बालकनी पहुँच के साथ विशाल डॉर्म। साझा बाथरूम।",
      it: "Dormitorio spazioso con armadietti personali e balcone. Bagno condiviso.",
      ja: "個別ロッカーとバルコニー付き。共同バスルーム。",
      ko: "개별 사물함과 발코니가 있는 넓은 도미토리. 공용 욕실.",
      pt: "Dormitório espaçoso com cacifos individuais e varanda. Banheiro compartilhado.",
      ru: "Просторный номер с индивидуальными шкафчиками и балконом. Общий санузел.",
      sv: "Rymlig sovsal med individuella skåp och balkongaccess. Delat badrum.",
      vi: "Ký túc xá rộng rãi với tủ khóa riêng và lối ra ban công. Phòng tắm chung.",
      zh: "宽敞宿舍，配个人储物柜及阳台，共用浴室。",
      ar: "مهجع واسع مع خزائن فردية وإمكانية الوصول إلى الشرفة. حمام مشترك.",
      pl: "Przestronny pokój wieloosobowy z indywidualnymi szafkami i wyjściem na balkon. Wspólna łazienka.",
      no: "Romslig sovesal med individuelle skap og tilgang til balkong. Delt bad.",
      da: "Rummeligt dorm med individuelle skabe og adgang til balkon. Fælles badeværelse.",
      hu: "Tágas hálóterem egyéni szekrényekkel és erkélykapcsolattal. Közös fürdőszoba.",
    },
    occupancy: 6,
    pricingModel: "perBed",
    basePrice: { amount: 22, currency: "EUR" },
    seasonalPrices: [
      {
        season: "high",
        start: "2025-06-01",
        end: "2025-08-31",
        price: { amount: 28, currency: "EUR" },
      },
      {
        season: "event",
        start: "2025-12-24",
        end: "2026-01-06",
        price: { amount: 34, currency: "EUR" },
      },
    ],
    amenities: [
      { name: "Balcony access", icon: "mountain" },
      { name: "Individual locker", icon: "lock" },
      { name: "Reading light", icon: "lightbulb" },
      { name: "Shared bathroom" },
      { name: "Free Wi-Fi", icon: "wifi" },
    ],
    availability: { totalBeds: 42, defaultRelease: 38 },
    images: [
      {
        url: "/images/rooms/dorm6-1.jpg",
        alt: {
          en: "6-bed mixed dorm",
          de: "Sechsbettzimmer, gemischt",
          es: "Dormitorio mixto de seis camas",
          fr: "Dortoir mixte six lits",
          hi: "6-बेड मिश्रित डॉर्म",
          it: "Dormitorio misto sei letti",
          ja: "6人ドミトリー",
          ko: "6인 혼성 도미토리",
          pt: "Dormitório misto seis camas",
          ru: "Шестиместный смешанный",
          vi: "Ký túc xá hỗn hợp 6 giường",
          zh: "6人混合宿舍",
          sv: "6-bäddars blandad sovsal",
          ar: "مهجع مختلط بستة أسرّة",
          pl: "6-osobowy mieszany pokój wieloosobowy",
          no: "6-sengs blandet sovesal",
          da: "6-sengs blandet dorm",
          hu: "6 ágyas vegyes hálóterem",
        },
      },
    ],
  },

  /* ───────────── Private Double Ensuite ───────────── */
  {
    sku: "PRD",
    name: {
      en: "Private Double Ensuite",
      de: "Privates Doppelzimmer (Bad)",
      es: "Doble privado con baño",
      fr: "Double privé avec salle de bain",
      hi: "निजी डबल एन-सुइट",
      it: "Matrimoniale privata con bagno",
      ja: "個室ダブル（専用バスルーム）",
      ko: "더블 전용 욕실",
      pt: "Duplo privado com banheiro",
      ru: "Двухместный номер с ванной",
      vi: "Phòng đôi riêng có phòng tắm riêng",
      zh: "私人双人套房",
      sv: "Privat dubbel med eget badrum",
      ar: "غرفة مزدوجة خاصة بحمام داخلي",
      pl: "Prywatny pokój dwuosobowy z łazienką",
      no: "Privat dobbeltrom med bad",
      da: "Privat dobbeltværelse med eget bad",
      hu: "Privát kétágyas szoba saját fürdővel",
    },
    description: {
      en: "Ideal for couples—queen bed, desk, mini-fridge, and ensuite bathroom.",
      de: "Ideal für Paare – Queensize-Bett, Schreibtisch, Minikühlschrank, eigenes Bad.",
      es: "Ideal para parejas: cama queen, escritorio, mini-nevera y baño privado.",
      fr: "Parfait pour les couples : lit queen-size, bureau, mini-frigo et salle de bain privative.",
      hi: "जोड़ों के लिए आदर्श—क्वीन बेड, डेस्क, मिनी-फ्रिज और निजी बाथरूम।",
      it: "Perfetta per coppie: letto queen-size, scrivania, mini-frigo e bagno privato.",
      ja: "カップルに最適。クイーンベッド、デスク、ミニ冷蔵庫、専用バスルーム。",
      ko: "커플에게 이상적 – 퀸침대, 책상, 미니 냉장고, 전용 욕실.",
      pt: "Ideal para casais — cama queen, escrivaninha, mini-frigorífico e banheiro privado.",
      ru: "Идеально для пар: кровать queen-size, рабочий стол, мини-холодильник, собственная ванная.",
      vi: "Lý tưởng cho các cặp đôi — giường queen, bàn làm việc, tủ lạnh mini và phòng tắm riêng.",
      zh: "适合情侣：大床、书桌、迷你冰箱及套内浴室。",
      sv: "Perfekt för par – queen size-säng, skrivbord, minibar och eget badrum.",
      ar: "مثالي للأزواج — سرير بحجم كوين، مكتب، ثلاجة صغيرة وحمام داخلي.",
      pl: "Idealny dla par — łóżko queen, biurko, minilodówka i prywatna łazienka.",
      no: "Ideelt for par – queen-size seng, skrivebord, minibar og eget bad.",
      da: "Ideel til par – queensize-seng, skrivebord, minibar og eget badeværelse.",
      hu: "Tökéletes pároknak — queen méretű ágy, íróasztal, mini hűtő és saját fürdőszoba.",
    },
    occupancy: 2,
    pricingModel: "perRoom",
    basePrice: { amount: 85, currency: "EUR" },
    seasonalPrices: [
      {
        season: "high",
        start: "2025-06-01",
        end: "2025-08-31",
        price: { amount: 110, currency: "EUR" },
      },
      {
        season: "event",
        start: "2025-12-24",
        end: "2026-01-06",
        price: { amount: 135, currency: "EUR" },
      },
    ],
    amenities: [
      { name: "Ensuite bathroom", icon: "bath" },
      { name: "Air-con", icon: "snowflake" },
      { name: "Mini-fridge", icon: "fridge" },
      { name: "Desk", icon: "monitor" },
      { name: "Smart TV", icon: "tv" },
      { name: "Towels included" },
      { name: "Free Wi-Fi", icon: "wifi" },
    ],
    availability: { totalBeds: 6, defaultRelease: 6 },
    images: [
      {
        url: "/images/rooms/double-1.jpg",
        alt: {
          en: "Private double ensuite",
          de: "Privates Doppelzimmer Bad",
          es: "Doble con baño privado",
          fr: "Double avec salle de bain",
          hi: "निजी डबल एन-सुइट",
          it: "Camera doppia con bagno",
          ja: "ダブル個室専用バス",
          ko: "더블 전용 욕실",
          pt: "Duplo banheiro privado",
          ru: "Двухместный номер ванная",
          vi: "Phòng đôi riêng có phòng tắm riêng",
          zh: "私人双人套房",
          sv: "Privat dubbel med eget badrum",
          ar: "غرفة مزدوجة خاصة بحمام داخلي",
          pl: "Prywatny pokój dwuosobowy z łazienką",
          no: "Privat dobbeltrom med bad",
          da: "Privat dobbeltværelse med eget bad",
          hu: "Privát kétágyas szoba saját fürdővel",
        },
      },
    ],
  },
];

export default roomCategorySchema.array().parse(rooms);
