// scripts/build-tokens.ts
/* eslint-disable no-console */
import { writeFileSync } from "node:fs";
import { join } from "node:path";
import { tokens, type TokenMap } from "../packages/themes/base/tokens";

/**
 * Create a plain-value stylesheet (no CSS variables).
 */
function generateStaticCss(map: TokenMap): string {
  let css = "/* Generated by build-tokens.ts */\n\n:root {\n";
  for (const [name, defs] of Object.entries(map)) {
    css += `  ${name}: ${defs.light};\n`;
  }
  css += "}\n";

  const darkEntries = Object.entries(map).filter(
    // narrow: keep only tokens that *do* define `dark`
    (entry): entry is [string, { light: string; dark: string }] =>
      entry[1].dark !== undefined
  );

  if (darkEntries.length) {
    css += "\n@media (prefers-color-scheme: dark) {\n  :root {\n";
    for (const [name, defs] of darkEntries) {
      css += `    ${name}: ${defs.dark};\n`;
    }
    css += "  }\n}\n";
  }
  return css;
}

/**
 * Create a CSS-variable stylesheet so end-users can override tokens.
 */
function generateDynamicCss(map: TokenMap): string {
  let css = "/* Generated by build-tokens.ts */\n\n:root {\n";
  for (const [name, defs] of Object.entries(map)) {
    const varName = `--token-${name.slice(2)}`;
    css += `  ${name}: var(${varName}, ${defs.light});\n`;
  }
  css += "}\n";

  const darkEntries = Object.entries(map).filter(
    (entry): entry is [string, { light: string; dark: string }] =>
      entry[1].dark !== undefined
  );

  if (darkEntries.length) {
    css += "\n@media (prefers-color-scheme: dark) {\n  :root {\n";
    for (const [name, defs] of darkEntries) {
      const varName = `--token-${name.slice(2)}-dark`;
      css += `    ${name}: var(${varName}, ${defs.dark});\n`;
    }
    css += "  }\n}\n";
  }
  return css;
}

const outDir = join(__dirname, "..", "packages", "themes", "base");
writeFileSync(join(outDir, "tokens.static.css"), generateStaticCss(tokens));
writeFileSync(join(outDir, "tokens.dynamic.css"), generateDynamicCss(tokens));

console.log("→ tokens.static.css and tokens.dynamic.css generated");
