import { defineConfig } from 'tsup';
import { resolve } from 'path';

export default defineConfig({
  // Main entry points
  entry: {
    // Root exports
    'index': 'src/index.ts',
    'account': 'src/account.ts',
    'operations': 'src/operations.ts',

    // CMS block exports (specific named exports from package.json)
    'components/cms/blocks/CollectionSection.server': 'src/components/cms/blocks/CollectionSection.server.tsx',
    'components/cms/blocks/CollectionSection.client': 'src/components/cms/blocks/CollectionSection.client.tsx',
    'components/cms/blocks/HeaderSection': 'src/components/cms/blocks/HeaderSection.tsx',
    'components/cms/blocks/FooterSection': 'src/components/cms/blocks/FooterSection.tsx',
    'components/cms/blocks/CurrencySelector': 'src/components/cms/blocks/CurrencySelector.tsx',
    'components/cms/blocks/RentalAvailabilitySection': 'src/components/cms/blocks/RentalAvailabilitySection.tsx',
    'components/cms/blocks/RentalTermsSection': 'src/components/cms/blocks/RentalTermsSection.tsx',
    'components/cms/blocks/StructuredDataSection': 'src/components/cms/blocks/StructuredDataSection.tsx',
    'components/cms/blocks/ConsentSection': 'src/components/cms/blocks/ConsentSection.tsx',
    'components/cms/blocks/AnalyticsPixelsSection': 'src/components/cms/blocks/AnalyticsPixelsSection.tsx',
    'components/cms/blocks/RentalDemoProvider.client': 'src/components/cms/blocks/RentalDemoProvider.client.tsx',

    // Component index exports
    'components/atoms/index': 'src/components/atoms/index.ts',
    'components/atoms/primitives/index': 'src/components/atoms/primitives/index.ts',
    'molecules/index': 'src/molecules/index.ts',
    'components/organisms/operations/index': 'src/components/organisms/operations/index.ts',

    // Wildcard pattern entry points - these need to be explicitly added for main files
    // The wildcard exports in package.json will still work because we're using outDir structure
  },

  // Output format
  format: ['esm'],

  // Generate TypeScript declaration files
  // NOTE: DTS generation is temporarily disabled due to TypeScript project config strictness
  // Declarations will be generated by tsc in a separate build step if needed
  dts: false,

  // Disable code splitting to avoid React context issues in Next.js SSG
  // When chunks have separate React imports, SSG can fail with "ReactCurrentOwner" errors
  splitting: false,

  // Enable tree-shaking
  treeshake: true,

  // Don't clean - tsc emits declarations to dist first, tsup adds JS files
  // The build script runs: tsc -b (declarations) then tsup (JS)
  clean: false,

  // Preserve source directory structure
  outDir: 'dist',

  // External dependencies that should not be bundled
  external: [
    // React ecosystem
    'react',
    'react-dom',
    'react/jsx-runtime',

    // Next.js
    'next',
    'next/link',
    'next/image',
    'next/navigation',
    'next/headers',
    'next-auth',

    // Peer dependencies from package.json
    '@headlessui/react',
    'dayjs',
    'focus-trap-react',
    'fuse.js',
    'i18next',
    'lucide-react',
    'tailwindcss',
    'react-datepicker',
    'react-i18next',
    'swiper',

    // Workspace dependencies
    '@acme/platform-core',
    '@acme/config',
    '@acme/date-utils',
    '@acme/i18n',
    '@acme/shared-utils',
    '@acme/telemetry',
    '@acme/types',
    '@acme/page-builder-core',
    '@acme/auth',

    // Path aliases used in UI package (types-compat)
    '@auth',
    '@i18n',
    '@platform-core',
  ],

  // esbuild options for path alias resolution
  esbuildOptions(options) {
    // Resolve @ui/* aliases to the src directory
    // esbuild requires explicit paths for each subdirectory alias
    options.alias = {
      '@ui/hooks': resolve(__dirname, 'src/hooks'),
      '@ui/lib': resolve(__dirname, 'src/lib'),
      '@ui/config': resolve(__dirname, 'src/config'),
      '@ui/context': resolve(__dirname, 'src/context'),
      '@ui/utils': resolve(__dirname, 'src/utils'),
      '@ui/locales': resolve(__dirname, 'src/locales'),
      '@ui/components': resolve(__dirname, 'src/components'),
      '@ui/atoms': resolve(__dirname, 'src/atoms'),
      '@ui/molecules': resolve(__dirname, 'src/molecules'),
      '@ui/organisms': resolve(__dirname, 'src/organisms'),
      '@ui/types': resolve(__dirname, 'src/types'),
      '@ui': resolve(__dirname, 'src'),
    };
  },

  // Silence warnings about using 'use client' directives
  banner: {
    js: '',
  },
});
