"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.createStripeWebhookEventDelegate = exports.createSectionTemplateDelegate = exports.createInventoryItemDelegate = exports.createProductDelegate = exports.createReverseLogisticsEventDelegate = exports.createUserDelegate = exports.createSubscriptionUsageDelegate = exports.createCustomerStripeMappingDelegate = exports.createCustomerIdentityDelegate = exports.createCustomerMfaDelegate = exports.createCustomerProfileDelegate = exports.createPageDelegate = exports.createShopDelegate = exports.createRentalOrderDelegate = void 0;
var rentalOrder_1 = require("./rentalOrder");
Object.defineProperty(exports, "createRentalOrderDelegate", { enumerable: true, get: function () { return rentalOrder_1.createRentalOrderDelegate; } });
var shop_1 = require("./shop");
Object.defineProperty(exports, "createShopDelegate", { enumerable: true, get: function () { return shop_1.createShopDelegate; } });
var page_1 = require("./page");
Object.defineProperty(exports, "createPageDelegate", { enumerable: true, get: function () { return page_1.createPageDelegate; } });
var customerProfile_1 = require("./customerProfile");
Object.defineProperty(exports, "createCustomerProfileDelegate", { enumerable: true, get: function () { return customerProfile_1.createCustomerProfileDelegate; } });
var customerMfa_1 = require("./customerMfa");
Object.defineProperty(exports, "createCustomerMfaDelegate", { enumerable: true, get: function () { return customerMfa_1.createCustomerMfaDelegate; } });
var customerIdentity_1 = require("./customerIdentity");
Object.defineProperty(exports, "createCustomerIdentityDelegate", { enumerable: true, get: function () { return customerIdentity_1.createCustomerIdentityDelegate; } });
var customerStripeMapping_1 = require("./customerStripeMapping");
Object.defineProperty(exports, "createCustomerStripeMappingDelegate", { enumerable: true, get: function () { return customerStripeMapping_1.createCustomerStripeMappingDelegate; } });
var subscriptionUsage_1 = require("./subscriptionUsage");
Object.defineProperty(exports, "createSubscriptionUsageDelegate", { enumerable: true, get: function () { return subscriptionUsage_1.createSubscriptionUsageDelegate; } });
var user_1 = require("./user");
Object.defineProperty(exports, "createUserDelegate", { enumerable: true, get: function () { return user_1.createUserDelegate; } });
var reverseLogisticsEvent_1 = require("./reverseLogisticsEvent");
Object.defineProperty(exports, "createReverseLogisticsEventDelegate", { enumerable: true, get: function () { return reverseLogisticsEvent_1.createReverseLogisticsEventDelegate; } });
var product_1 = require("./product");
Object.defineProperty(exports, "createProductDelegate", { enumerable: true, get: function () { return product_1.createProductDelegate; } });
var inventoryItem_1 = require("./inventoryItem");
Object.defineProperty(exports, "createInventoryItemDelegate", { enumerable: true, get: function () { return inventoryItem_1.createInventoryItemDelegate; } });
var sectionTemplate_1 = require("./sectionTemplate");
Object.defineProperty(exports, "createSectionTemplateDelegate", { enumerable: true, get: function () { return sectionTemplate_1.createSectionTemplateDelegate; } });
var stripeWebhookEvent_1 = require("./stripeWebhookEvent");
Object.defineProperty(exports, "createStripeWebhookEventDelegate", { enumerable: true, get: function () { return stripeWebhookEvent_1.createStripeWebhookEventDelegate; } });
