import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

type GuideContentEntry = {
  linkLabel?: unknown;
  seo?: { title?: unknown } | undefined;
};

type LegacyGuidesBundle = {
  links?: Record<string, unknown>;
  content?: Record<string, GuideContentEntry>;
};

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const APP_ROOT = path.resolve(__dirname, "..");
const LOCALES_ROOT = path.join(APP_ROOT, "src", "locales");
const OUTPUT_PATH = path.join(APP_ROOT, "src", "data", "generated-guide-link-labels.ts");

function isDirectory(targetPath: string): boolean {
  try {
    return fs.statSync(targetPath).isDirectory();
  } catch {
    return false;
  }
}

function readJsonFile<T>(targetPath: string): T | undefined {
  try {
    const raw = fs.readFileSync(targetPath, "utf8");
    return JSON.parse(raw) as T;
  } catch {
    return undefined;
  }
}

function normaliseLabel(value: unknown): string | undefined {
  if (typeof value !== "string") return undefined;
  const trimmed = value.trim();
  return trimmed.length > 0 ? trimmed : undefined;
}

function setLabel(labels: Record<string, string>, key: string, value: unknown): void {
  const normalised = normaliseLabel(value);
  if (!normalised) return;
  labels[key] = normalised;
}

function readLabelFromContentEntry(entry: GuideContentEntry | undefined): string | undefined {
  const linkLabel = normaliseLabel(entry?.linkLabel);
  if (linkLabel) return linkLabel;
  return normaliseLabel(entry?.seo?.title);
}

function collectFromLegacyBundle(localeDir: string, labels: Record<string, string>): void {
  const legacyPath = path.join(localeDir, "guides.json");
  const legacy = readJsonFile<LegacyGuidesBundle>(legacyPath);
  if (!legacy) return;

  for (const [key, value] of Object.entries(legacy.links ?? {})) {
    setLabel(labels, key, value);
  }

  for (const [key, value] of Object.entries(legacy.content ?? {})) {
    const label = readLabelFromContentEntry(value);
    if (label) {
      labels[key] = label;
    }
  }
}

function collectFromSplitFiles(localeDir: string, labels: Record<string, string>): void {
  const contentDir = path.join(localeDir, "guides", "content");
  if (!isDirectory(contentDir)) return;

  const files = fs.readdirSync(contentDir).filter((file) => file.endsWith(".json"));
  files.sort((a, b) => a.localeCompare(b));

  for (const file of files) {
    const key = file.replace(/\.json$/u, "");
    const entry = readJsonFile<GuideContentEntry>(path.join(contentDir, file));
    if (!entry) continue;
    const label = readLabelFromContentEntry(entry);
    if (label) {
      labels[key] = label;
    }
  }
}

function sortObjectByKey<T>(value: Record<string, T>): Record<string, T> {
  return Object.fromEntries(
    Object.entries(value).sort(([left], [right]) => left.localeCompare(right)),
  );
}

function collectLocaleLabelMap(locale: string): Record<string, string> {
  const localeDir = path.join(LOCALES_ROOT, locale);
  const labels: Record<string, string> = {};

  collectFromLegacyBundle(localeDir, labels);
  collectFromSplitFiles(localeDir, labels);

  return sortObjectByKey(labels);
}

function listLocales(): string[] {
  const entries = fs.readdirSync(LOCALES_ROOT, { withFileTypes: true });
  return entries
    .filter((entry) => entry.isDirectory())
    .map((entry) => entry.name)
    .filter((name) => !name.startsWith("_"))
    .sort((a, b) => a.localeCompare(b));
}

function renderOutput(data: Record<string, Record<string, string>>): string {
  const serialized = JSON.stringify(data, null, 2);
  return [
    "// src/data/generated-guide-link-labels.ts",
    "// Auto-generated by scripts/generate-guide-link-labels.ts",
    "/* eslint-disable ds/no-hardcoded-copy, ds/no-raw-font -- INTL-451 generated non-UI locale labels */",
    "",
    "export const GENERATED_GUIDE_LINK_LABELS: Readonly<",
    "  Record<string, Readonly<Record<string, string>>>",
    `> = Object.freeze(${serialized});`,
    "",
    "export type GeneratedGuideLinkLabels = typeof GENERATED_GUIDE_LINK_LABELS;",
    "",
  ].join("\n");
}

function main(): void {
  const locales = listLocales();
  const byLocale: Record<string, Record<string, string>> = {};

  for (const locale of locales) {
    const labels = collectLocaleLabelMap(locale);
    if (Object.keys(labels).length > 0) {
      byLocale[locale] = labels;
    }
  }

  const sorted = sortObjectByKey(byLocale);
  const output = renderOutput(sorted);
  fs.writeFileSync(OUTPUT_PATH, output, "utf8");
  const labelCount = Object.values(sorted).reduce((sum, labels) => sum + Object.keys(labels).length, 0);
  process.stdout.write(
    `Wrote ${OUTPUT_PATH} with ${Object.keys(sorted).length} locales and ${labelCount} guide labels.\n`,
  );
}

main();
