import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

import { formatRedirectRules } from "../src/routing/staticExportRedirects";

import { buildStaticRuntimeArtifacts } from "./lib/static-runtime-redirects";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const APP_ROOT = path.resolve(__dirname, "..");
const REDIRECTS_PATH = path.join(APP_ROOT, "public", "_redirects");
const ROUTES_PATH = path.join(APP_ROOT, "public", "_routes.json");
const LEGACY_REDIRECTS_MODULE_PATH = path.join(
  APP_ROOT,
  "functions",
  "generated",
  "legacy-redirects.js",
);

function buildLegacyRedirectModule(entries: readonly { from: string; to: string }[]): string {
  const lines = [
    "// Generated by scripts/generate-static-export-redirects.ts",
    "// Exact historical redirects for the Cloudflare Pages legacy-path function.",
    "",
    "export const LEGACY_REDIRECT_ENTRIES = [",
    ...entries.map(
      ({ from, to }) => `  [${JSON.stringify(from)}, ${JSON.stringify(to)}],`,
    ),
    "];",
    "",
    "export const LEGACY_REDIRECTS = new Map(LEGACY_REDIRECT_ENTRIES);",
    "",
  ];

  return `${lines.join("\n")}\n`;
}

async function main(): Promise<void> {
  const { structuralRules, exactLegacyRedirects, routeConfig } = buildStaticRuntimeArtifacts(APP_ROOT);
  const fileLines = [
    "# Cloudflare Pages redirects",
    "# https://developers.cloudflare.com/pages/configuration/redirects/",
    "# This file is deployed alongside static HTML for structural edge-level redirects.",
    "# High-cardinality historical exact redirects are handled by the Pages legacy-path function.",
    "",
    ...formatRedirectRules(structuralRules),
    "",
  ];

  await mkdir(path.dirname(LEGACY_REDIRECTS_MODULE_PATH), { recursive: true });
  await writeFile(REDIRECTS_PATH, `${fileLines.join("\n")}`, "utf8");
  await writeFile(ROUTES_PATH, `${JSON.stringify(routeConfig, null, 2)}\n`, "utf8");
  await writeFile(
    LEGACY_REDIRECTS_MODULE_PATH,
    buildLegacyRedirectModule(exactLegacyRedirects),
    "utf8",
  );

  process.stdout.write(`Updated ${REDIRECTS_PATH}, ${ROUTES_PATH}, and ${LEGACY_REDIRECTS_MODULE_PATH}.\n`);
}

main().catch((error: unknown) => {
  console.error(error);
  process.exitCode = 1;
});
