import "server-only";
import type { RentalOrder } from "@acme/types";

export type Order = RentalOrder;
export declare function normalize<T extends Order>(order: T): T;
export declare function listOrders(shop: string): Promise<Order[]>;
export declare const readOrders: typeof listOrders;
export declare function addOrder(shop: string, sessionId: string, deposit: number, expectedReturnDate?: string, returnDueDate?: string, customerId?: string, riskLevel?: string, riskScore?: number, flaggedForReview?: boolean): Promise<Order>;
export declare function markFulfilled(shop: string, sessionId: string): Promise<Order>;
export declare function markShipped(shop: string, sessionId: string): Promise<Order>;
export declare function markDelivered(shop: string, sessionId: string): Promise<Order>;
export declare function markCancelled(shop: string, sessionId: string): Promise<Order>;
export declare function markReturned(shop: string, sessionId: string, damageFee?: number): Promise<Order | null>;
export declare function markRefunded(shop: string, sessionId: string, riskLevel?: string, riskScore?: number, flaggedForReview?: boolean): Promise<Order | null>;
export declare function refundOrder(shop: string, id: string, amount?: number): Promise<Order | null>;
export declare function updateRisk(shop: string, sessionId: string, riskLevel?: string, riskScore?: number, flaggedForReview?: boolean): Promise<Order | null>;
export declare function getOrdersForCustomer(shop: string, customerId: string): Promise<Order[]>;
export declare function setReturnTracking(shop: string, sessionId: string, trackingNumber: string, labelUrl: string): Promise<Order | null>;
export declare function setReturnStatus(shop: string, trackingNumber: string, returnStatus: string): Promise<Order | null>;
export {};
