# Startup Loop Specification
# Runtime-authoritative source of truth for the stage graph.
# All other documents (SKILL.md, workflow guide, prompt index) MUST align to this spec.
# Version bumps require downstream alignment check (VC-02).

spec_version: "1.7.0"
created: "2026-02-13"
decision_reference: "docs/plans/lp-skill-system-sequencing-plan.md#DL-01"
# v1.1.0: Added BD-3 sub-deliverable annotation on S2B (see docs/plans/startup-loop-branding-design-module/plan.md)
# v1.2.0: Added GATE-MEAS-01 (Hard) — S6B blocked until decision-grade measurement signal verified.
#         Rationale: channel spend before working measurement is structurally invalid. Always.
#         Decision captured: 2026-02-17 during BRIK S0 startup loop initiation.
#         Superseded by v1.5.0 sub-gate split (GATE-S6B-STRAT-01 + GATE-S6B-ACT-01).
# v1.3.0: Added GATE-BD-00 (Hard) — S0→S1 blocked when business_name_status=unconfirmed until naming
#         shortlist returned. Gate is a prompt-handoff pattern (mirrors S2 market intelligence).
#         Absent or confirmed status skips gate (backwards-compatible). Decision: 2026-02-17.
#         See: docs/plans/startup-loop-business-naming/plan.md
# v1.4.0: Added derived display fields to run_packet contract (current_stage_label,
#         current_stage_display, next_stage_label, next_stage_display). Labels sourced
#         from stage-operator-map.json (generated from stage-operator-dictionary.yaml).
#         Additive — existing consumers may ignore new fields without breakage. 2026-02-17.
# v1.5.0: Split GATE-MEAS-01 into GATE-S6B-STRAT-01 (strategy design gate — passes with valid DEP)
#         and GATE-S6B-ACT-01 (spend activation gate — inherits GATE-MEAS-01 pass conditions).
#         Rationale: strategy design before measurement is valid; spend commitment before measurement is not.
#         Resolves S6B planning stall on pre-website businesses. Decision: TASK-02 (2026-02-17).
#         See: docs/plans/startup-loop-marketing-sales-capability-gap-audit/plan.md (TASK-02, TASK-07)
# v1.6.0: Added S3B (Adjacent product research) as third conditional member of fan-out-1.
#         Condition: growth_intent in intake packet references product range expansion, or operator invokes.
#         Non-blocking at S4 — results artifact is optional (required: false).
#         GATE-S3B-01 (Soft/advisory) dispatches /adjacent-product-research at S2B Done.
#         Results artifact (human-produced after Perplexity run) consumed optionally by lp-prioritize (S5A).
#         Skill: .claude/skills/adjacent-product-research/SKILL.md. Decision: 2026-02-20.
# v1.7.0: Added S0A–S0D conditional pre-intake stage family for problem-first operator entry.
#         Entry routing: explicit --start-point problem|product flag (default: product).
#         Condition: "start-point = problem" — consistent with --launch-surface gate pattern.
#         Stages: S0A (Problem framing) → S0B (Solution-space scan) → S0C (Option selection) → S0D (Naming handoff).
#         S0D uses brand-naming-research (prompt-handoff); operator saves Perplexity results as
#         *-naming-shortlist.user.md to satisfy GATE-BD-00 (fires at S0→S1, not S0D→S0).
#         Operators with --start-point product (or flag absent) bypass S0A–S0D: pass-through, no gate block.
#         Decision: docs/plans/startup-loop-pre-s0-problem-framing/plan.md 2026-02-20.

# Capability contract: docs/business-os/startup-loop/marketing-sales-capability-contract.md
# Defines the 7 canonical marketing/sales capabilities (CAP-01 through CAP-07), their artifact paths,
# validation rules, and downstream consumers. Use this as the completeness reference for stage outputs.

# ─────────────────────────────────────────────────────────
# Stage Graph
# ─────────────────────────────────────────────────────────

stages:
  # ── Conditional pre-intake stage family (S0A–S0D) ─────────────────────────
  # Triggered when operator invokes /startup-loop start --start-point problem.
  # Operators using --start-point product (or flag absent) bypass S0A–S0D entirely: pass-through, no gate block.
  # S0D (brand-naming-research) produces a naming research prompt; the operator's Perplexity results
  # saved as *-naming-shortlist.user.md satisfy GATE-BD-00 at S0→S1. Gate fires at S0→S1, not S0D→S0.

  - id: S0A
    name: Problem framing
    skill: /lp-problem-frame
    prompt_required: false
    conditional: true
    condition: "start-point = problem"
    bos_sync: "Persist problem statement under docs/business-os/strategy/<BIZ>/"

  - id: S0B
    name: Solution-space scan
    skill: /lp-solution-space
    prompt_required: false
    conditional: true
    condition: "start-point = problem"
    bos_sync: "Persist solution-space prompt and results artifact slot under docs/business-os/strategy/<BIZ>/"

  - id: S0C
    name: Option selection
    skill: /lp-option-select
    prompt_required: false
    conditional: true
    condition: "start-point = problem"
    bos_sync: "Persist option-select artifact under docs/business-os/strategy/<BIZ>/"

  - id: S0D
    name: Naming handoff
    skill: /brand-naming-research
    prompt_required: false
    conditional: true
    condition: "start-point = problem"
    bos_sync: "Persist naming research prompt under docs/business-os/strategy/<BIZ>/"
    # GATE-BD-00 note: gate fires at S0→S1 (not S0D→S0). brand-naming-research produces a
    # naming research PROMPT (naming-research-prompt.md). The operator runs this in Perplexity
    # and saves results as <YYYY-MM-DD>-naming-shortlist.user.md — that artifact satisfies the
    # *-naming-shortlist.user.md pass condition. No new naming contract introduced by S0D.

  - id: S0
    name: Intake
    skill: /startup-loop start
    prompt_required: true
    prompt_template: intake-normalizer-prompt.md
    conditional: false
    bos_sync: "Update docs/business-os/strategy/<BIZ>/plan.user.md"
    # GATE-BD-00 (Hard) — evaluated at S0→S1 advance.
    # Triggers when business_name_status=unconfirmed in intake packet.
    # Absent or confirmed status skips gate (backwards-compatible, fail-open).
    # Prompt template: docs/business-os/market-research/_templates/deep-research-naming-prompt.md
    # Pass condition: any *-naming-shortlist.user.md glob match under docs/business-os/strategy/<BIZ>/
    # On pass: writes docs/business-os/strategy/<BIZ>/latest-naming-shortlist.user.md (stable pointer)
    # See: docs/plans/startup-loop-business-naming/plan.md

  - id: S1
    name: Readiness
    skill: /lp-readiness
    prompt_required: true
    prompt_template: readiness-blocker-interview-prompt.md
    conditional: false
    bos_sync: "Record blockers/warnings in readiness docs + strategy plan risk section"

  - id: S1B
    name: Measurement bootstrap
    skill: prompt-handoff
    prompt_required: true
    prompt_template: pre-website-measurement-bootstrap-prompt.md
    # expanded 2026-02-17: thin template replaced in-place with comprehensive Phase 0-2 bootstrap
    # covering access bundle (P0-01..P0-12 + deferred P0-11a/b), Phase 1 agent steps (G,SC,D,GH,C),
    # Phase 2 staging verification (V-01..V-06), 7 Derived Policies, IDs glossary, Consent Mode v2.
    # Decision: Option A (in-place, same filename) — no spec_version bump for this change alone.
    # Reference: docs/plans/startup-loop-infra-measurement-bootstrap/plan.md
    # For website-live businesses: use measurement-quality-audit-prompt.md (separate template, S2A path).
    conditional: true
    condition: "launch-surface = pre-website"
    bos_sync: "Record measurement setup status under docs/business-os/strategy/<BIZ>/"

  - id: S2A
    name: Historical baseline
    skill: prompt-handoff
    prompt_required: true
    prompt_template: existing-business-historical-baseline-prompt.md
    conditional: true
    condition: "launch-surface = website-live"
    bos_sync: "Persist baseline under docs/business-os/strategy/<BIZ>/"

  - id: S2
    name: Market intelligence
    skill: prompt-handoff
    prompt_required: true
    prompt_template: docs/business-os/market-research/_templates/deep-research-market-intelligence-prompt.md
    conditional: false
    bos_sync: "Update latest.user.md pointer + strategy assumptions"

  - id: S2B
    name: Offer design
    skill: /lp-offer
    prompt_required: false
    conditional: false
    # BD-3 sub-deliverable: messaging-hierarchy.user.md (Draft minimum) must exist before S2B is Done.
    # This does NOT block the S3/S6B parallel fan-out — both start after S2B completes.
    # Gate policy: GATE-BD-03 (Hard, S2B Done gate). See: docs/business-os/strategy/_templates/index-template.user.md
    bos_sync: "Persist offer + messaging_hierarchy artifacts under docs/business-os/startup-baselines/<BIZ>/"

  # ── Parallel fan-out ──────────────────────────────────
  # S3, S3B, and S6B may execute concurrently after S2B completes.
  # S3 and S6B must complete before S4 (join barrier) can proceed.
  # S3B is conditional and non-blocking at S4 (optional artifact).

  - id: S3
    name: Forecast
    skill: /lp-forecast
    prompt_required: false
    conditional: false
    parallel_group: fan-out-1
    bos_sync: "Update latest pointer + strategy assumptions/targets"

  - id: S3B
    name: Adjacent product research
    skill: /lp-other-products
    prompt_required: false
    conditional: true
    condition: "growth_intent includes product_range OR operator_invoked"
    parallel_group: fan-out-1
    bos_sync: none
    # GATE-S3B-01 (Soft/advisory) — evaluated at S2B Done.
    # Trigger: growth_intent field in intake packet references product range expansion.
    # Pass condition: adjacent-product-research-prompt.md exists under docs/business-os/strategy/<BIZ>/
    # Results (human-produced after Perplexity run): docs/business-os/strategy/<BIZ>/adjacent-product-research-results.user.md
    # Results consumed optionally by S5A (lp-prioritize) as additional go-item candidates.

  - id: S6B
    name: Channel strategy + GTM
    skill: /lp-channels
    secondary_skills:
      - /lp-seo
      - /draft-outreach
    prompt_required: false
    conditional: false
    parallel_group: fan-out-1
    bos_sync: "Persist channel artifact under docs/business-os/startup-baselines/<BIZ>/"
    # GATE-S6B-STRAT-01 (Hard) — strategy design gate, evaluated at S2B→S6B fan-out.
    # Pass condition: valid DEP artifact exists (demand-evidence-pack-schema.md pass floor met).
    # On pass: S6B strategy design (channel selection, GTM plan) may begin without measurement readiness.
    # GATE-S6B-ACT-01 (Hard) — spend activation gate, evaluated before first paid channel commitment.
    # Pass condition: decision-grade measurement signal verified (inherits GATE-MEAS-01 checks, v1.2.0).
    # Strategy design output may be completed and persisted before GATE-S6B-ACT-01 is evaluated.

  # ── Parallel fan-in (join barrier) ────────────────────

  - id: S4
    name: Baseline merge
    skill: /lp-baseline-merge
    prompt_required: false
    conditional: false
    join_barrier: true
    required_inputs:
      - stage: S2B
        artifact_key: offer
        required: true
      - stage: S3
        artifact_key: forecast
        required: true
      - stage: S6B
        artifact_key: channels
        required: true
      - stage: S6B
        artifact_key: seo
        required: false
      - stage: S6B
        artifact_key: outreach
        required: false
      - stage: S3B
        artifact_key: adjacent_product_research
        required: false
    bos_sync: "Write candidate baseline snapshot + draft manifest (uncommitted)"

  - id: S5A
    name: Prioritize
    skill: /lp-prioritize
    prompt_required: true
    prompt_template: prioritization-scorer-prompt.md
    conditional: false
    side_effects: none
    bos_sync: none

  - id: S5B
    name: BOS sync
    skill: /lp-bos-sync
    prompt_required: false
    conditional: false
    side_effects: guarded
    bos_sync: "Persist cards/stage-docs to D1 via /api/agent/*; commit manifest pointer"

  - id: S6
    name: Site-upgrade synthesis
    skill: /lp-site-upgrade
    prompt_required: true
    prompt_template: docs/business-os/site-upgrades/_templates/deep-research-business-upgrade-prompt.md
    conditional: false
    bos_sync: "Update latest.user.md pointer"

  - id: S7
    name: Fact-find
    skill: /lp-do-fact-find
    prompt_required: false
    conditional: false
    bos_sync: "Upsert fact-find stage doc via /api/agent/stage-docs/:cardId/fact-find"

  - id: S8
    name: Plan
    skill: /lp-do-plan
    prompt_required: false
    conditional: false
    bos_sync: "Upsert plan stage doc + lane transition Fact-finding -> Planned"

  - id: S9
    name: Build
    skill: /lp-do-build
    prompt_required: false
    conditional: false
    bos_sync: "Upsert build stage doc + lane transitions to In progress / Done"

  - id: S9B
    name: QA gates
    skill: /lp-launch-qa
    secondary_skills:
      - /lp-design-qa
    prompt_required: false
    conditional: false
    bos_sync: "Record QA results in build stage doc"

  - id: S10
    name: Weekly readout + experiments
    skill: /lp-experiment
    prompt_required: true
    prompt_template: weekly-kpcs-decision-prompt.md
    conditional: false
    bos_sync: "Record K/P/C/S decision + update card/plan state"

# ─────────────────────────────────────────────────────────
# Stage Ordering Constraints
# ─────────────────────────────────────────────────────────

ordering:
  sequential:
    - [S0A, S0B]         # problem-first pre-intake: S0A→S0B (conditional)
    - [S0B, S0C]         # problem-first pre-intake: S0B→S0C (conditional)
    - [S0C, S0D]         # problem-first pre-intake: S0C→S0D (conditional)
    - [S0D, S0]          # problem-first: S0D exits into standard S0 intake
    - [S0, S1]
    - [S1, S1B]          # conditional
    - [S1, S2A]          # conditional
    - [S2A, S2]          # S2A gates S2 for website-live
    - [S1B, S2]          # S1B gates S2 for pre-website (warning quality)
    - [S2, S2B]
    - [S2B, S3]
    - [S2B, S3B]         # fan-out: S3B starts after S2B (conditional)
    - [S2B, S6B]         # fan-out: S3 and S6B both start after S2B
    - [S3, S4]           # fan-in: S4 waits for S3
    - [S3B, S4]          # fan-in: S4 waits for S3B if running (non-blocking — optional artifact)
    - [S6B, S4]          # fan-in: S4 waits for S6B
    - [S4, S5A]
    - [S5A, S5B]
    - [S5B, S6]
    - [S5B, S7]          # S7 can start after S5B (or after S6 if site-upgrade in scope)
    - [S6, S7]
    - [S7, S8]
    - [S8, S9]
    - [S9, S9B]
    - [S9B, S10]

  parallel_groups:
    fan-out-1:
      members: [S3, S3B, S6B]
      join_at: S4
      conditional_members: [S3B]    # S3B only runs when condition is met; non-blocking at join

# ─────────────────────────────────────────────────────────
# Run Packet Contract
# ─────────────────────────────────────────────────────────

run_packet:
  required_fields:
    - run_id          # SFS-<BIZ>-<YYYYMMDD>-<hhmm>
    - business
    - current_stage
    - current_stage_label    # label_operator_short for current_stage (from stage-operator-map.json)
    - current_stage_display  # label_operator_long for current_stage (e.g. "S3 — Forecast")
    - next_stage_label       # label_operator_short for next eligible stage; null if none
    - next_stage_display     # label_operator_long for next eligible stage; null if none
    - status          # ready | blocked | awaiting-input | complete
    - blocking_reason
    - next_action
    - prompt_file
    - required_output_path
    - naming_gate     # skipped | blocked | complete (computed from filesystem; see GATE-BD-00)
    - bos_sync_actions
    - loop_spec_version   # must match this spec's spec_version
