import { useTranslations as getTranslations } from "@acme/i18n/useTranslations.server";
import { Stack } from "@acme/design-system/primitives";

import PageHeader from "@/components/PageHeader";

import CandidateDetailClient from "./CandidateDetailClient";

export const runtime = "edge";

export default async function CandidateDetailPage({
  params,
}: {
  params: Promise<{ id: string }>;
}) {
  const resolvedParams = await params;
  const t = await getTranslations("en");

  const strings = {
    overview: {
      label: t("pipeline.candidate.section.overview.label"),
      title: t("pipeline.candidate.section.overview.title"),
    },
    lead: {
      label: t("pipeline.candidate.section.lead.label"),
      title: t("pipeline.candidate.section.lead.title"),
    },
    hud: {
      label: t("pipeline.candidate.hud.label"),
      title: t("pipeline.candidate.hud.title"),
      returnLabel: t("pipeline.candidate.hud.return"),
      riskLabel: t("pipeline.candidate.hud.risk"),
      effortLabel: t("pipeline.candidate.hud.effort"),
      confidenceLabel: t("pipeline.candidate.hud.confidence"),
      nextLabel: t("pipeline.candidate.hud.next"),
      returnBands: {
        low: t("pipeline.candidate.hud.returnBands.low"),
        medium: t("pipeline.candidate.hud.returnBands.medium"),
        high: t("pipeline.candidate.hud.returnBands.high"),
        unknown: t("pipeline.candidate.hud.returnBands.unknown"),
      },
      riskBands: {
        low: t("pipeline.candidate.hud.riskBands.low"),
        medium: t("pipeline.candidate.hud.riskBands.medium"),
        high: t("pipeline.candidate.hud.riskBands.high"),
        unknown: t("pipeline.candidate.hud.riskBands.unknown"),
      },
      effortBands: {
        low: t("pipeline.candidate.hud.effortBands.low"),
        medium: t("pipeline.candidate.hud.effortBands.medium"),
        high: t("pipeline.candidate.hud.effortBands.high"),
        unknown: t("pipeline.candidate.hud.effortBands.unknown"),
      },
      nextActions: {
        needStageM: t("pipeline.candidate.hud.nextActions.needStageM"),
        needStageB: t("pipeline.candidate.hud.nextActions.needStageB"),
        needStageC: t("pipeline.candidate.hud.nextActions.needStageC"),
        needStageT: t("pipeline.candidate.hud.nextActions.needStageT"),
        needStageS: t("pipeline.candidate.hud.nextActions.needStageS"),
        needStageK: t("pipeline.candidate.hud.nextActions.needStageK"),
        needStageR: t("pipeline.candidate.hud.nextActions.needStageR"),
        reviewCompliance: t("pipeline.candidate.hud.nextActions.reviewCompliance"),
        ready: t("pipeline.candidate.hud.nextActions.ready"),
      },
    },
    common: {
      editInputs: t("pipeline.candidate.common.editInputs"),
      hideInputs: t("pipeline.candidate.common.hideInputs"),
      showDetails: t("pipeline.candidate.common.showDetails"),
      hideDetails: t("pipeline.candidate.common.hideDetails"),
      laterStepsLabel: t("pipeline.candidate.common.laterStepsLabel"),
      laterStepsShow: t("pipeline.candidate.common.laterStepsShow"),
      laterStepsHide: t("pipeline.candidate.common.laterStepsHide"),
    },
    nextStep: {
      label: t("pipeline.candidate.nextStep.label"),
      title: t("pipeline.candidate.nextStep.title"),
      resolveEligibility: t("pipeline.candidate.nextStep.resolveEligibility"),
      resolveCompliance: t("pipeline.candidate.nextStep.resolveCompliance"),
      resolveCooldown: t("pipeline.candidate.nextStep.resolveCooldown"),
      fillMissing: t("pipeline.candidate.nextStep.fillMissing"),
      viewEvidence: t("pipeline.candidate.nextStep.viewEvidence"),
      whyBlocked: t("pipeline.candidate.nextStep.whyBlocked"),
      go: t("pipeline.candidate.nextStep.go"),
    },
    fullEval: {
      label: t("pipeline.candidate.fullEval.label"),
      title: t("pipeline.candidate.fullEval.title"),
      body: t("pipeline.candidate.fullEval.body"),
      run: t("pipeline.candidate.fullEval.run"),
      running: t("pipeline.candidate.fullEval.running"),
      ready: t("pipeline.candidate.fullEval.ready"),
      success: t("pipeline.candidate.fullEval.success"),
      error: t("pipeline.candidate.fullEval.error"),
      statusQueued: t("pipeline.candidate.fullEval.statusQueued"),
      statusRan: t("pipeline.candidate.fullEval.statusRan"),
      statusSkipped: t("pipeline.candidate.fullEval.statusSkipped"),
      statusMissing: t("pipeline.candidate.fullEval.statusMissing"),
    },
    decisions: {
      label: t("pipeline.candidate.decisions.label"),
      title: t("pipeline.candidate.decisions.title"),
      ctaReview: t("pipeline.candidate.decisions.ctaReview"),
      ctaResolve: t("pipeline.candidate.decisions.ctaResolve"),
      ctaFill: t("pipeline.candidate.decisions.ctaFill"),
      items: {
        market: t("pipeline.candidate.decisions.items.market"),
        eligibility: t("pipeline.candidate.decisions.items.eligibility"),
        profit: t("pipeline.candidate.decisions.items.profit"),
        cash: t("pipeline.candidate.decisions.items.cash"),
        priority: t("pipeline.candidate.decisions.items.priority"),
      },
      status: {
        ready: t("pipeline.candidate.decisions.status.ready"),
        needsInput: t("pipeline.candidate.decisions.status.needsInput"),
        blocked: t("pipeline.candidate.decisions.status.blocked"),
        review: t("pipeline.candidate.decisions.status.review"),
        clear: t("pipeline.candidate.decisions.status.clear"),
        profitable: t("pipeline.candidate.decisions.status.profitable"),
        notProfitable: t("pipeline.candidate.decisions.status.notProfitable"),
      },
      market: {
        detail: t("pipeline.candidate.decisions.market.detail"),
        missing: t("pipeline.candidate.decisions.market.missing"),
      },
      eligibility: {
        blocked: t("pipeline.candidate.decisions.eligibility.blocked"),
        review: t("pipeline.candidate.decisions.eligibility.review"),
        clear: t("pipeline.candidate.decisions.eligibility.clear"),
        missing: t("pipeline.candidate.decisions.eligibility.missing"),
      },
      profit: {
        detail: t("pipeline.candidate.decisions.profit.detail"),
        loss: t("pipeline.candidate.decisions.profit.loss"),
        missing: t("pipeline.candidate.decisions.profit.missing"),
      },
      cash: {
        detail: t("pipeline.candidate.decisions.cash.detail"),
        missing: t("pipeline.candidate.decisions.cash.missing"),
      },
      priority: {
        detail: t("pipeline.candidate.decisions.priority.detail"),
        missing: t("pipeline.candidate.decisions.priority.missing"),
      },
    },
    scorecard: {
      label: t("pipeline.candidate.scorecard.label"),
      title: t("pipeline.candidate.scorecard.title"),
      recommendationLabel: t("pipeline.candidate.scorecard.recommendationLabel"),
      recommendationAdvance: t("pipeline.candidate.scorecard.recommendationAdvance"),
      recommendationReview: t("pipeline.candidate.scorecard.recommendationReview"),
      recommendationReject: t("pipeline.candidate.scorecard.recommendationReject"),
      recommendationPause: t("pipeline.candidate.scorecard.recommendationPause"),
      decisionLabel: t("pipeline.candidate.scorecard.decisionLabel"),
      decisionNone: t("pipeline.candidate.scorecard.decisionNone"),
      decisionAdvance: t("pipeline.candidate.scorecard.decisionAdvance"),
      decisionReview: t("pipeline.candidate.scorecard.decisionReview"),
      decisionReject: t("pipeline.candidate.scorecard.decisionReject"),
      decisionPause: t("pipeline.candidate.scorecard.decisionPause"),
      decisionReasonLabel: t("pipeline.candidate.scorecard.decisionReasonLabel"),
      decisionReasonPlaceholder: t("pipeline.candidate.scorecard.decisionReasonPlaceholder"),
      decisionSave: t("pipeline.candidate.scorecard.decisionSave"),
      decisionSaving: t("pipeline.candidate.scorecard.decisionSaving"),
      decisionSaved: t("pipeline.candidate.scorecard.decisionSaved"),
      decisionError: t("pipeline.candidate.scorecard.decisionError"),
      decisionRequired: t("pipeline.candidate.scorecard.decisionRequired"),
      reasonDefault: t("pipeline.candidate.scorecard.reasonDefault"),
      reasonCooldown: t("pipeline.candidate.scorecard.reasonCooldown"),
      reasonEligibilityBlocked: t("pipeline.candidate.scorecard.reasonEligibilityBlocked"),
      reasonEligibilityReview: t("pipeline.candidate.scorecard.reasonEligibilityReview"),
      reasonComplianceBlocked: t("pipeline.candidate.scorecard.reasonComplianceBlocked"),
      reasonMissingProfit: t("pipeline.candidate.scorecard.reasonMissingProfit"),
      reasonMissingCash: t("pipeline.candidate.scorecard.reasonMissingCash"),
      reasonMissingPayback: t("pipeline.candidate.scorecard.reasonMissingPayback"),
      metricProfit: t("pipeline.candidate.scorecard.metricProfit"),
      metricMarginLabel: t("pipeline.candidate.scorecard.metricMarginLabel"),
      metricCashNeeded: t("pipeline.candidate.scorecard.metricCashNeeded"),
      metricPayback: t("pipeline.candidate.scorecard.metricPayback"),
      metricPaybackDaysLabel: t("pipeline.candidate.scorecard.metricPaybackDaysLabel"),
      riskLabel: t("pipeline.candidate.scorecard.riskLabel"),
      effortLabel: t("pipeline.candidate.scorecard.effortLabel"),
      confidenceLabel: t("pipeline.candidate.scorecard.confidenceLabel"),
      confidenceHigh: t("pipeline.candidate.scorecard.confidenceHigh"),
      confidenceMedium: t("pipeline.candidate.scorecard.confidenceMedium"),
      confidenceLow: t("pipeline.candidate.scorecard.confidenceLow"),
      confidenceComplete: t("pipeline.candidate.scorecard.confidenceComplete"),
      missingLabel: t("pipeline.candidate.scorecard.missingLabel"),
    },
    stageLabels: {
      P: t("pipeline.home.stageRail.stage.preSelection"),
      M: t("pipeline.candidate.section.stageM.label"),
      A: t("pipeline.candidate.section.stageA.label"),
      T: t("pipeline.candidate.section.stageT.label"),
      S: t("pipeline.candidate.section.stageS.label"),
      N: t("pipeline.candidate.section.stageN.label"),
      D: t("pipeline.candidate.section.stageD.label"),
      B: t("pipeline.candidate.section.stageB.label"),
      C: t("pipeline.candidate.section.stageC.label"),
      K: t("pipeline.candidate.section.stageK.label"),
      R: t("pipeline.candidate.section.stageR.label"),
      L: t("pipeline.nav.launches.label"),
    },
    stageM: {
      label: t("pipeline.candidate.section.stageM.label"),
      title: t("pipeline.candidate.section.stageM.title"),
      runLabel: t("pipeline.candidate.stageM.run"),
      kindLabel: t("pipeline.candidate.stageM.kind.label"),
      kindAmazonSearch: t("pipeline.candidate.stageM.kind.amazonSearch"),
      kindAmazonListing: t("pipeline.candidate.stageM.kind.amazonListing"),
      kindTaobaoListing: t("pipeline.candidate.stageM.kind.taobaoListing"),
      captureModeLabel: t("pipeline.candidate.stageM.captureMode.label"),
      captureModeQueue: t("pipeline.candidate.stageM.captureMode.queue"),
      captureModeRunner: t("pipeline.candidate.stageM.captureMode.runner"),
      captureProfileLabel: t("pipeline.candidate.stageM.captureProfile.label"),
      captureProfileHelp: t("pipeline.candidate.stageM.captureProfile.help"),
      captureProfilePlaceholder: t("pipeline.candidate.stageM.captureProfile.placeholder"),
      captureProfileErrorRequired: t(
        "pipeline.candidate.stageM.captureProfile.errorRequired",
      ),
      captureProfileErrorInvalid: t(
        "pipeline.candidate.stageM.captureProfile.errorInvalid",
      ),
      captureProfileErrorNotAllowed: t(
        "pipeline.candidate.stageM.captureProfile.errorNotAllowed",
      ),
      runnerStatusLabel: t("pipeline.candidate.stageM.runnerStatus.label"),
      runnerStatusChecking: t("pipeline.candidate.stageM.runnerStatus.checking"),
      runnerStatusUnknown: t("pipeline.candidate.stageM.runnerStatus.unknown"),
      runnerStatusReady: t("pipeline.candidate.stageM.runnerStatus.ready"),
      runnerStatusStale: t("pipeline.candidate.stageM.runnerStatus.stale"),
      runnerStatusLastSeen: t("pipeline.candidate.stageM.runnerStatus.lastSeen"),
      runnerStatusMode: t("pipeline.candidate.stageM.runnerStatus.mode"),
      runnerStatusBrowser: t("pipeline.candidate.stageM.runnerStatus.browser"),
      runnerStatusSession: t("pipeline.candidate.stageM.runnerStatus.session"),
      marketplaceLabel: t("pipeline.candidate.stageM.marketplace"),
      queryLabel: t("pipeline.candidate.stageM.query"),
      urlLabel: t("pipeline.candidate.stageM.url"),
      maxResultsLabel: t("pipeline.candidate.stageM.maxResults"),
      readyLabel: t("pipeline.candidate.stageM.ready"),
      queueingLabel: t("pipeline.candidate.stageM.queueing"),
      successMessage: t("pipeline.candidate.stageM.success"),
      errorMessage: t("pipeline.candidate.stageM.error"),
      budgetMessage: t("pipeline.candidate.stageM.budgetExceeded"),
      summaryContext: t("pipeline.candidate.stageM.summary.context"),
      summaryGeneratedAt: t("pipeline.candidate.stageM.summary.generatedAt"),
      summaryPriceRange: t("pipeline.candidate.stageM.summary.priceRange"),
      summaryMedianPrice: t("pipeline.candidate.stageM.summary.medianPrice"),
      summaryReviewMedian: t("pipeline.candidate.stageM.summary.reviewMedian"),
      summarySponsoredShare: t("pipeline.candidate.stageM.summary.sponsoredShare"),
      summarySampleCount: t("pipeline.candidate.stageM.summary.sampleCount"),
      summaryCapture: t("pipeline.candidate.stageM.summary.capture"),
      summaryCaptureMode: t("pipeline.candidate.stageM.summary.captureMode"),
      summaryHeadless: t("pipeline.candidate.stageM.summary.headless"),
      summaryHeadlessOn: t("pipeline.candidate.stageM.summary.headlessOn"),
      summaryHeadlessOff: t("pipeline.candidate.stageM.summary.headlessOff"),
      summaryHumanGate: t("pipeline.candidate.stageM.summary.humanGate"),
      summaryHumanGateOn: t("pipeline.candidate.stageM.summary.humanGateOn"),
      summaryHumanGateOff: t("pipeline.candidate.stageM.summary.humanGateOff"),
      summaryHumanGateAccepted: t("pipeline.candidate.stageM.summary.humanGateAccepted"),
      summaryHumanGateDeclined: t("pipeline.candidate.stageM.summary.humanGateDeclined"),
      summaryPlaybook: t("pipeline.candidate.stageM.summary.playbook"),
      summarySession: t("pipeline.candidate.stageM.summary.session"),
      summaryDuration: t("pipeline.candidate.stageM.summary.duration"),
    },
    stageA: {
      label: t("pipeline.candidate.section.stageA.label"),
      title: t("pipeline.candidate.section.stageA.title"),
      runLabel: t("pipeline.candidate.stageA.run"),
      inputSalePrice: t("pipeline.candidate.stageA.inputs.salePrice"),
      inputUnitCost: t("pipeline.candidate.stageA.inputs.unitCost"),
      inputShipping: t("pipeline.candidate.stageA.inputs.shipping"),
      inputFeesPct: t("pipeline.candidate.stageA.inputs.feesPct"),
      inputTargetMarginPct: t("pipeline.candidate.stageA.inputs.targetMarginPct"),
      inputNotes: t("pipeline.candidate.stageA.inputs.notes"),
      inputHelp: t("pipeline.candidate.stageA.inputHelp"),
      success: t("pipeline.candidate.stageA.success"),
      errorInvalid: t("pipeline.candidate.stageA.errorInvalid"),
      errorRun: t("pipeline.candidate.stageA.errorRun"),
      summaryMargin: t("pipeline.candidate.stageA.summary.margin"),
      summaryNetPerUnit: t("pipeline.candidate.stageA.summary.netPerUnit"),
      summaryAction: t("pipeline.candidate.stageA.summary.action"),
      summaryThreshold: t("pipeline.candidate.stageA.summary.threshold"),
      actions: {
        advance: t("pipeline.candidate.stageA.actions.advance"),
        review: t("pipeline.candidate.stageA.actions.review"),
        reject: t("pipeline.candidate.stageA.actions.reject"),
      },
    },
    stageK: {
      label: t("pipeline.candidate.section.stageK.label"),
      title: t("pipeline.candidate.section.stageK.title"),
      runLabel: t("pipeline.candidate.stageK.run"),
      inputLabel: t("pipeline.candidate.stageK.input"),
      inputHelp: t("pipeline.candidate.stageK.inputHelp"),
      composeLabel: t("pipeline.candidate.stageK.compose"),
      composeHelp: t("pipeline.candidate.stageK.composeHelp"),
      composeSuccess: t("pipeline.candidate.stageK.composeSuccess"),
      composeError: t("pipeline.candidate.stageK.composeError"),
      composeMissingStageB: t("pipeline.candidate.stageK.composeMissingStageB"),
      composeMissingStageC: t("pipeline.candidate.stageK.composeMissingStageC"),
      success: t("pipeline.candidate.stageK.success"),
      errorInvalidJson: t("pipeline.candidate.stageK.errorInvalidJson"),
      errorRun: t("pipeline.candidate.stageK.errorRun"),
      summaryPeakCash: t("pipeline.candidate.stageK.summary.peakCash"),
      summaryPayback: t("pipeline.candidate.stageK.summary.payback"),
      summaryReturn: t("pipeline.candidate.stageK.summary.return"),
      laneCompare: {
        label: t("pipeline.candidate.stageK.laneCompare.label"),
        title: t("pipeline.candidate.stageK.laneCompare.title"),
        selectLabel: t("pipeline.candidate.stageK.laneCompare.selectLabel"),
        help: t("pipeline.candidate.stageK.laneCompare.help"),
        compareLabel: t("pipeline.candidate.stageK.laneCompare.compareLabel"),
        successCompare: t("pipeline.candidate.stageK.laneCompare.successCompare"),
        errorLoad: t("pipeline.candidate.stageK.laneCompare.errorLoad"),
        errorCompare: t("pipeline.candidate.stageK.laneCompare.errorCompare"),
        empty: t("pipeline.candidate.stageK.laneCompare.empty"),
        noLanes: t("pipeline.candidate.stageK.laneCompare.noLanes"),
        loading: t("pipeline.candidate.stageK.laneCompare.loading"),
        baseLabel: t("pipeline.candidate.stageK.laneCompare.baseLabel"),
        baseLaneLabel: t("pipeline.candidate.stageK.laneCompare.baseLaneLabel"),
        resultsLabel: t("pipeline.candidate.stageK.laneCompare.resultsLabel"),
        summaryPeakCash: t("pipeline.candidate.stageK.laneCompare.summaryPeakCash"),
        summaryPayback: t("pipeline.candidate.stageK.laneCompare.summaryPayback"),
        summaryReturn: t("pipeline.candidate.stageK.laneCompare.summaryReturn"),
        warningExpired: t("pipeline.candidate.stageK.laneCompare.warningExpired"),
        warningExpiring: t("pipeline.candidate.stageK.laneCompare.warningExpiring"),
        warningLowConfidence: t(
          "pipeline.candidate.stageK.laneCompare.warningLowConfidence",
        ),
        warningBasis: t("pipeline.candidate.stageK.laneCompare.warningBasis"),
        warningMissingCost: t(
          "pipeline.candidate.stageK.laneCompare.warningMissingCost",
        ),
        warningMissingLeadTime: t(
          "pipeline.candidate.stageK.laneCompare.warningMissingLeadTime",
        ),
      },
    },
    stageT: {
      label: t("pipeline.candidate.section.stageT.label"),
      title: t("pipeline.candidate.section.stageT.title"),
      runLabel: t("pipeline.candidate.stageT.run"),
      inputDecision: t("pipeline.candidate.stageT.inputs.decision"),
      inputReasons: t("pipeline.candidate.stageT.inputs.reasons"),
      inputReasonsPlaceholder: t(
        "pipeline.candidate.stageT.inputs.reasonsPlaceholder",
      ),
      inputEvidence: t("pipeline.candidate.stageT.inputs.evidence"),
      inputEvidencePlaceholder: t(
        "pipeline.candidate.stageT.inputs.evidencePlaceholder",
      ),
      inputNotes: t("pipeline.candidate.stageT.inputs.notes"),
      inputNotesPlaceholder: t("pipeline.candidate.stageT.inputs.notesPlaceholder"),
      inputHelp: t("pipeline.candidate.stageT.inputHelp"),
      success: t("pipeline.candidate.stageT.success"),
      errorRun: t("pipeline.candidate.stageT.errorRun"),
      decisions: {
        allowed: t("pipeline.candidate.stageT.decisions.allowed"),
        needsReview: t("pipeline.candidate.stageT.decisions.needsReview"),
        blocked: t("pipeline.candidate.stageT.decisions.blocked"),
      },
      actions: {
        advance: t("pipeline.candidate.stageT.actions.advance"),
        review: t("pipeline.candidate.stageT.actions.review"),
        block: t("pipeline.candidate.stageT.actions.block"),
      },
      summaryDecision: t("pipeline.candidate.stageT.summary.decision"),
      summaryAction: t("pipeline.candidate.stageT.summary.action"),
      summaryEvidence: t("pipeline.candidate.stageT.summary.evidence"),
      summaryReasons: t("pipeline.candidate.stageT.summary.reasons"),
      summaryEvidenceList: t("pipeline.candidate.stageT.summary.evidenceList"),
    },
    stageS: {
      label: t("pipeline.candidate.section.stageS.label"),
      title: t("pipeline.candidate.section.stageS.title"),
      runLabel: t("pipeline.candidate.stageS.run"),
      inputComplianceRisk: t("pipeline.candidate.stageS.inputs.complianceRisk"),
      inputIpRisk: t("pipeline.candidate.stageS.inputs.ipRisk"),
      inputHazmatRisk: t("pipeline.candidate.stageS.inputs.hazmatRisk"),
      inputShippingRisk: t("pipeline.candidate.stageS.inputs.shippingRisk"),
      inputListingRisk: t("pipeline.candidate.stageS.inputs.listingRisk"),
      inputPackagingRisk: t("pipeline.candidate.stageS.inputs.packagingRisk"),
      inputMatchingConfidence: t("pipeline.candidate.stageS.inputs.matching"),
      inputArtifactsRequired: t("pipeline.candidate.stageS.inputs.artifacts"),
      inputNotes: t("pipeline.candidate.stageS.inputs.notes"),
      inputHelp: t("pipeline.candidate.stageS.inputHelp"),
      success: t("pipeline.candidate.stageS.success"),
      errorInvalid: t("pipeline.candidate.stageS.errorInvalid"),
      errorRun: t("pipeline.candidate.stageS.errorRun"),
      summaryOverallRisk: t("pipeline.candidate.stageS.summary.overallRisk"),
      summaryAction: t("pipeline.candidate.stageS.summary.action"),
      summaryScore: t("pipeline.candidate.stageS.summary.score"),
      summaryMatchingConfidence: t("pipeline.candidate.stageS.summary.matching"),
      summaryFlags: t("pipeline.candidate.stageS.summary.flags"),
      riskBands: {
        low: t("pipeline.candidate.stageS.riskBands.low"),
        medium: t("pipeline.candidate.stageS.riskBands.medium"),
        high: t("pipeline.candidate.stageS.riskBands.high"),
      },
      actions: {
        advance: t("pipeline.candidate.stageS.actions.advance"),
        review: t("pipeline.candidate.stageS.actions.review"),
        block: t("pipeline.candidate.stageS.actions.block"),
      },
    },
    stageN: {
      label: t("pipeline.candidate.section.stageN.label"),
      title: t("pipeline.candidate.section.stageN.title"),
      runLabel: t("pipeline.candidate.stageN.run"),
      inputStatus: t("pipeline.candidate.stageN.inputs.status"),
      inputSupplier: t("pipeline.candidate.stageN.inputs.supplier"),
      inputTargetUnitCost: t("pipeline.candidate.stageN.inputs.targetUnitCost"),
      inputTargetMoq: t("pipeline.candidate.stageN.inputs.targetMoq"),
      inputTargetLeadTime: t("pipeline.candidate.stageN.inputs.targetLeadTime"),
      inputTargetDepositPct: t("pipeline.candidate.stageN.inputs.targetDepositPct"),
      inputTargetPaymentTerms: t("pipeline.candidate.stageN.inputs.targetPaymentTerms"),
      inputTargetIncoterms: t("pipeline.candidate.stageN.inputs.targetIncoterms"),
      inputTasks: t("pipeline.candidate.stageN.inputs.tasks"),
      inputNotes: t("pipeline.candidate.stageN.inputs.notes"),
      inputHelp: t("pipeline.candidate.stageN.inputHelp"),
      success: t("pipeline.candidate.stageN.success"),
      errorInvalid: t("pipeline.candidate.stageN.errorInvalid"),
      errorRun: t("pipeline.candidate.stageN.errorRun"),
      summaryStatus: t("pipeline.candidate.stageN.summary.status"),
      summarySupplier: t("pipeline.candidate.stageN.summary.supplier"),
      summaryTargetUnitCost: t("pipeline.candidate.stageN.summary.targetUnitCost"),
      summaryTargetMoq: t("pipeline.candidate.stageN.summary.targetMoq"),
      summaryLeadTime: t("pipeline.candidate.stageN.summary.leadTime"),
      summaryDeposit: t("pipeline.candidate.stageN.summary.deposit"),
      summaryPaymentTerms: t("pipeline.candidate.stageN.summary.paymentTerms"),
      summaryIncoterms: t("pipeline.candidate.stageN.summary.incoterms"),
      summaryTasks: t("pipeline.candidate.stageN.summary.tasks"),
      summaryTasksEmpty: t("pipeline.candidate.stageN.summary.tasksEmpty"),
      statuses: {
        notStarted: t("pipeline.candidate.stageN.statuses.notStarted"),
        inProgress: t("pipeline.candidate.stageN.statuses.inProgress"),
        waitingOnSupplier: t("pipeline.candidate.stageN.statuses.waitingOnSupplier"),
        termsImproved: t("pipeline.candidate.stageN.statuses.termsImproved"),
        noProgress: t("pipeline.candidate.stageN.statuses.noProgress"),
      },
    },
    stageD: {
      label: t("pipeline.candidate.section.stageD.label"),
      title: t("pipeline.candidate.section.stageD.title"),
      runLabel: t("pipeline.candidate.stageD.run"),
      inputAssetReadiness: t("pipeline.candidate.stageD.inputs.assetReadiness"),
      inputOneTimeCost: t("pipeline.candidate.stageD.inputs.oneTimeCost"),
      inputSamplingRounds: t("pipeline.candidate.stageD.inputs.samplingRounds"),
      inputLeadTime: t("pipeline.candidate.stageD.inputs.leadTime"),
      inputPackagingStatus: t("pipeline.candidate.stageD.inputs.packagingStatus"),
      inputNotes: t("pipeline.candidate.stageD.inputs.notes"),
      inputHelp: t("pipeline.candidate.stageD.inputHelp"),
      success: t("pipeline.candidate.stageD.success"),
      errorInvalid: t("pipeline.candidate.stageD.errorInvalid"),
      errorRun: t("pipeline.candidate.stageD.errorRun"),
      summaryAssetReadiness: t("pipeline.candidate.stageD.summary.assetReadiness"),
      summaryOneTimeCost: t("pipeline.candidate.stageD.summary.oneTimeCost"),
      summaryLeadTime: t("pipeline.candidate.stageD.summary.leadTime"),
      summarySamplingRounds: t("pipeline.candidate.stageD.summary.samplingRounds"),
      summaryPackagingStatus: t("pipeline.candidate.stageD.summary.packagingStatus"),
      assetReadiness: {
        notStarted: t("pipeline.candidate.stageD.assetReadiness.notStarted"),
        inProgress: t("pipeline.candidate.stageD.assetReadiness.inProgress"),
        ready: t("pipeline.candidate.stageD.assetReadiness.ready"),
      },
    },
    stageB: {
      label: t("pipeline.candidate.section.stageB.label"),
      title: t("pipeline.candidate.section.stageB.title"),
      runLabel: t("pipeline.candidate.stageB.run"),
      inputUnitsPlanned: t("pipeline.candidate.stageB.inputs.unitsPlanned"),
      inputUnitCost: t("pipeline.candidate.stageB.inputs.unitCost"),
      inputFreight: t("pipeline.candidate.stageB.inputs.freight"),
      inputDuty: t("pipeline.candidate.stageB.inputs.duty"),
      inputVat: t("pipeline.candidate.stageB.inputs.vat"),
      inputPackaging: t("pipeline.candidate.stageB.inputs.packaging"),
      inputInspection: t("pipeline.candidate.stageB.inputs.inspection"),
      inputOther: t("pipeline.candidate.stageB.inputs.other"),
      inputLeadTime: t("pipeline.candidate.stageB.inputs.leadTimeDays"),
      inputDepositPct: t("pipeline.candidate.stageB.inputs.depositPct"),
      inputBalanceDueDays: t("pipeline.candidate.stageB.inputs.balanceDueDays"),
      inputIncoterms: t("pipeline.candidate.stageB.inputs.incoterms"),
      inputNotes: t("pipeline.candidate.stageB.inputs.notes"),
      inputHelp: t("pipeline.candidate.stageB.inputHelp"),
      success: t("pipeline.candidate.stageB.success"),
      errorInvalid: t("pipeline.candidate.stageB.errorInvalid"),
      errorRun: t("pipeline.candidate.stageB.errorRun"),
      summaryUnitCost: t("pipeline.candidate.stageB.summary.unitCost"),
    summaryTotalCost: t("pipeline.candidate.stageB.summary.totalCost"),
    summaryDeposit: t("pipeline.candidate.stageB.summary.deposit"),
    summaryBalance: t("pipeline.candidate.stageB.summary.balance"),
    summaryLeadTime: t("pipeline.candidate.stageB.summary.leadTime"),
    quoteBasket: {
      label: t("pipeline.candidate.stageB.quoteBasket.label"),
      title: t("pipeline.candidate.stageB.quoteBasket.title"),
      selectLabel: t("pipeline.candidate.stageB.quoteBasket.selectLabel"),
      selectPlaceholder: t("pipeline.candidate.stageB.quoteBasket.selectPlaceholder"),
      applyLabel: t("pipeline.candidate.stageB.quoteBasket.applyLabel"),
      appliedLabel: t("pipeline.candidate.stageB.quoteBasket.appliedLabel"),
      appliedEmpty: t("pipeline.candidate.stageB.quoteBasket.appliedEmpty"),
      help: t("pipeline.candidate.stageB.quoteBasket.help"),
      loading: t("pipeline.candidate.stageB.quoteBasket.loading"),
      empty: t("pipeline.candidate.stageB.quoteBasket.empty"),
      errorLoad: t("pipeline.candidate.stageB.quoteBasket.errorLoad"),
      errorApply: t("pipeline.candidate.stageB.quoteBasket.errorApply"),
      successApply: t("pipeline.candidate.stageB.quoteBasket.successApply"),
      summaryUnits: t("pipeline.candidate.stageB.quoteBasket.summaryUnits"),
      summaryWeight: t("pipeline.candidate.stageB.quoteBasket.summaryWeight"),
      summaryVolume: t("pipeline.candidate.stageB.quoteBasket.summaryVolume"),
      summaryIncoterms: t("pipeline.candidate.stageB.quoteBasket.summaryIncoterms"),
    },
    lane: {
      label: t("pipeline.candidate.stageB.lane.label"),
      title: t("pipeline.candidate.stageB.lane.title"),
      selectLabel: t("pipeline.candidate.stageB.lane.selectLabel"),
        selectPlaceholder: t("pipeline.candidate.stageB.lane.selectPlaceholder"),
        applyLabel: t("pipeline.candidate.stageB.lane.applyLabel"),
        appliedLabel: t("pipeline.candidate.stageB.lane.appliedLabel"),
        appliedEmpty: t("pipeline.candidate.stageB.lane.appliedEmpty"),
        help: t("pipeline.candidate.stageB.lane.help"),
        loading: t("pipeline.candidate.stageB.lane.loading"),
        empty: t("pipeline.candidate.stageB.lane.empty"),
        warningExpired: t("pipeline.candidate.stageB.lane.warningExpired"),
        warningExpiring: t("pipeline.candidate.stageB.lane.warningExpiring"),
        warningBasis: t("pipeline.candidate.stageB.lane.warningBasis"),
        warningLowConfidence: t(
          "pipeline.candidate.stageB.lane.warningLowConfidence",
        ),
        errorLoad: t("pipeline.candidate.stageB.lane.errorLoad"),
        errorApply: t("pipeline.candidate.stageB.lane.errorApply"),
        successApply: t("pipeline.candidate.stageB.lane.successApply"),
      },
      guidance: {
        label: t("pipeline.candidate.stageB.guidance.label"),
        title: t("pipeline.candidate.stageB.guidance.title"),
        glossaryLabel: t("pipeline.candidate.stageB.guidance.glossaryLabel"),
        glossaryFba: t("pipeline.candidate.stageB.guidance.glossaryFba"),
        glossaryIncoterms: t(
          "pipeline.candidate.stageB.guidance.glossaryIncoterms",
        ),
        costTimingLabel: t("pipeline.candidate.stageB.guidance.costTimingLabel"),
        costTimingText: t("pipeline.candidate.stageB.guidance.costTimingText"),
        confidenceLabel: t("pipeline.candidate.stageB.guidance.confidenceLabel"),
        confidenceText: t("pipeline.candidate.stageB.guidance.confidenceText"),
      },
    },
    stageC: {
      label: t("pipeline.candidate.section.stageC.label"),
      title: t("pipeline.candidate.section.stageC.title"),
      runLabel: t("pipeline.candidate.stageC.run"),
      inputSalePrice: t("pipeline.candidate.stageC.inputs.salePrice"),
      inputPlatformFeePct: t("pipeline.candidate.stageC.inputs.platformFeePct"),
      inputFulfillment: t("pipeline.candidate.stageC.inputs.fulfillment"),
      inputStorage: t("pipeline.candidate.stageC.inputs.storage"),
      inputAdvertising: t("pipeline.candidate.stageC.inputs.advertising"),
      inputOtherFees: t("pipeline.candidate.stageC.inputs.otherFees"),
      inputReturnRatePct: t("pipeline.candidate.stageC.inputs.returnRatePct"),
      inputPayoutDelay: t("pipeline.candidate.stageC.inputs.payoutDelayDays"),
      inputUnitsPlanned: t("pipeline.candidate.stageC.inputs.unitsPlanned"),
      inputNotes: t("pipeline.candidate.stageC.inputs.notes"),
      inputHelp: t("pipeline.candidate.stageC.inputHelp"),
      success: t("pipeline.candidate.stageC.success"),
      errorInvalid: t("pipeline.candidate.stageC.errorInvalid"),
      errorRun: t("pipeline.candidate.stageC.errorRun"),
      summaryNetRevenue: t("pipeline.candidate.stageC.summary.netRevenue"),
      summaryContribution: t("pipeline.candidate.stageC.summary.contribution"),
      summaryMargin: t("pipeline.candidate.stageC.summary.margin"),
      summaryPayoutDelay: t("pipeline.candidate.stageC.summary.payoutDelay"),
      summaryTotalContribution: t("pipeline.candidate.stageC.summary.totalContribution"),
    },
    stageR: {
      label: t("pipeline.candidate.section.stageR.label"),
      title: t("pipeline.candidate.section.stageR.title"),
      runLabel: t("pipeline.candidate.stageR.run"),
      inputRiskScore: t("pipeline.candidate.stageR.inputs.riskScore"),
      inputEffortScore: t("pipeline.candidate.stageR.inputs.effortScore"),
      inputRiskDrivers: t("pipeline.candidate.stageR.inputs.riskDrivers"),
      inputEffortDrivers: t("pipeline.candidate.stageR.inputs.effortDrivers"),
      inputNotes: t("pipeline.candidate.stageR.inputs.notes"),
      inputHelp: t("pipeline.candidate.stageR.inputHelp"),
      success: t("pipeline.candidate.stageR.success"),
      errorInvalid: t("pipeline.candidate.stageR.errorInvalid"),
      errorRun: t("pipeline.candidate.stageR.errorRun"),
      summaryRisk: t("pipeline.candidate.stageR.summary.risk"),
      summaryEffort: t("pipeline.candidate.stageR.summary.effort"),
      summaryRank: t("pipeline.candidate.stageR.summary.rank"),
      summaryNext: t("pipeline.candidate.stageR.summary.next"),
      nextActions: {
        advance: t("pipeline.candidate.stageR.nextActions.advance"),
        reviewRisk: t("pipeline.candidate.stageR.nextActions.reviewRisk"),
        reviewEffort: t("pipeline.candidate.stageR.nextActions.reviewEffort"),
        needStageK: t("pipeline.candidate.stageR.nextActions.needStageK"),
      },
    },
    stageRuns: {
      label: t("pipeline.candidate.section.stageRuns.label"),
      title: t("pipeline.candidate.section.stageRuns.title"),
      stageLabel: t("pipeline.candidate.stageRuns.stage"),
      statusLabel: t("pipeline.candidate.stageRuns.status"),
      createdLabel: t("pipeline.candidate.stageRuns.created"),
      startedLabel: t("pipeline.candidate.stageRuns.started"),
      finishedLabel: t("pipeline.candidate.stageRuns.finished"),
      inputLabel: t("pipeline.candidate.stageRuns.input"),
      outputLabel: t("pipeline.candidate.stageRuns.output"),
      errorLabel: t("pipeline.candidate.stageRuns.error"),
    },
    artifacts: {
      label: t("pipeline.candidate.section.artifacts.label"),
      title: t("pipeline.candidate.section.artifacts.title"),
      kindLabel: t("pipeline.candidate.artifacts.kind"),
      kindSnapshotHtml: t("pipeline.candidate.artifacts.kind.snapshotHtml"),
      kindSnapshotPng: t("pipeline.candidate.artifacts.kind.snapshotPng"),
      uriLabel: t("pipeline.candidate.artifacts.uri"),
      createdLabel: t("pipeline.candidate.artifacts.created"),
      openLabel: t("pipeline.candidate.artifacts.open"),
    },
    artifactUpload: {
      label: t("pipeline.candidate.artifactUpload.label"),
      title: t("pipeline.candidate.artifactUpload.title"),
      stageRunLabel: t("pipeline.candidate.artifactUpload.stageRun"),
      kindLabel: t("pipeline.candidate.artifactUpload.kind"),
      fileLabel: t("pipeline.candidate.artifactUpload.file"),
      submitLabel: t("pipeline.candidate.artifactUpload.submit"),
      loadingRuns: t("pipeline.candidate.artifactUpload.loadingRuns"),
      emptyRuns: t("pipeline.candidate.artifactUpload.emptyRuns"),
      successMessage: t("pipeline.candidate.artifactUpload.success"),
      errorMessage: t("pipeline.candidate.artifactUpload.error"),
    },
    cooldown: {
      label: t("pipeline.candidate.section.cooldown.label"),
      title: t("pipeline.candidate.section.cooldown.title"),
      activeLabel: t("pipeline.candidate.cooldown.active"),
      noneLabel: t("pipeline.candidate.cooldown.none"),
      noneMessage: t("pipeline.candidate.cooldown.noneMessage"),
      reasonLabel: t("pipeline.candidate.cooldown.reason"),
      severityLabel: t("pipeline.candidate.cooldown.severity"),
      recheckLabel: t("pipeline.candidate.cooldown.recheck"),
      whatWouldChangeLabel: t("pipeline.candidate.cooldown.whatWouldChange"),
      submitLabel: t("pipeline.candidate.cooldown.submit"),
      successMessage: t("pipeline.candidate.cooldown.success"),
      errorMessage: t("pipeline.candidate.cooldown.error"),
      severityShort: t("pipeline.candidate.cooldown.severity.short"),
      severityLong: t("pipeline.candidate.cooldown.severity.long"),
      severityPermanent: t("pipeline.candidate.cooldown.severity.permanent"),
      activeMessage: t("pipeline.candidate.cooldown.activeMessage"),
    },
    gates: {
      label: t("pipeline.candidate.gates.label"),
      blockingLabel: t("pipeline.candidate.gates.blockingLabel"),
      actionLabel: t("pipeline.candidate.gates.actionLabel"),
      whyLabel: t("pipeline.candidate.gates.whyLabel"),
      whyStageT: t("pipeline.candidate.gates.whyStageT"),
      whyStageS: t("pipeline.candidate.gates.whyStageS"),
      stageTBlocked: t("pipeline.candidate.gates.stageTBlocked"),
      stageTNeedsReview: t("pipeline.candidate.gates.stageTNeedsReview"),
      stageSBlocked: t("pipeline.candidate.gates.stageSBlocked"),
    },
    fields: {
      candidateId: t("pipeline.candidate.fields.candidateId"),
      stageStatus: t("pipeline.candidate.fields.stageStatus"),
      decision: t("pipeline.candidate.fields.decision"),
      decisionReason: t("pipeline.candidate.fields.decisionReason"),
      leadTitle: t("pipeline.candidate.fields.leadTitle"),
      leadSource: t("pipeline.candidate.fields.leadSource"),
      leadUrl: t("pipeline.candidate.fields.leadUrl"),
      leadStatus: t("pipeline.candidate.fields.leadStatus"),
    },
    notAvailable: t("pipeline.common.notAvailable"),
  };

  return (
    <Stack gap={6}>
      <PageHeader
        badge={t("pipeline.candidate.badge")}
        title={t("pipeline.candidate.title")}
        subtitle={t("pipeline.candidate.subtitle")}
      />
      <CandidateDetailClient candidateId={resolvedParams.id} strings={strings} />
    </Stack>
  );
}
